### ISSUE TITLE
我想问一个简单的问题，图片上传后，怎么显示出来

### ISSUE THREAD

**Issue by mozibrand** [CollectionFS/Meteor-CollectionFS#1006]
我看了很多资料和官方的教程说明，都说在
{{#each images}}  < i m g  src='{{this.url}}' > {{/each}}

就可以显示出来，但是，不管是程序默认的还是设置了 /data目录，他都是 /cfs...这种格式的，并且根本显示不出来，请问怎么解决，求给一段能用的代码或告诉方法，到底是怎么才能显示出来，已经研究一整天了，都没有办法

==============================

I looked at a lot of information and the official instructions, and they all said

{{#each images}}  < i m g  src='{{this.url}}' > {{/each}}

It can be displayed, but whether it's the default or set/data directory, he's/CFS... This format, and the ultimate show not to come out, how can I solve, can give a of the code or tell method, how to display, has been studying all day long, all have no way

![12121212212121212](https://user-images.githubusercontent.com/24447931/27013149-f9d67954-4f10-11e7-871d-209fdda758d5.jpg)

![123](https://user-images.githubusercontent.com/24447931/27013175-762c1fc2-4f11-11e7-942d-6eedd1b900a5.jpg)

![32](https://user-images.githubusercontent.com/24447931/27013178-7e7bd33e-4f11-11e7-8aa0-f6682930804f.jpg)

![14](https://user-images.githubusercontent.com/24447931/27013183-850ac854-4f11-11e7-9292-c3f8691196b9.jpg)

**Comment by nooitaf** [comment]
You try to get the image from the `thumbs` store..
```html
<img src={{this.url store="thumbs"}}>
```
...but only the `images` store got created..
```js
stores:[new FS.Store.Filesystem("images")]
```
## Solution 1:  
..use the one store you created
```html
<img src={{this.url store="images"}}>
```

## Solution 2:  

.. add a `thumbs` store
from https://github.com/CollectionFS/Meteor-CollectionFS#basic-example
```js
var createThumb = function(fileObj, readStream, writeStream) {
  // Transform the image into a 10x10px thumbnail
  gm(readStream, fileObj.name()).resize('10', '10').stream().pipe(writeStream);
};

Images = new FS.Collection("images", {
  stores: [
    new FS.Store.FileSystem("thumbs", { transformWrite: createThumb }),
    new FS.Store.FileSystem("images"),
  ],
  filter: {
    allow: {
      contentTypes: ['image/*'] //allow only images in this FS.Collection
    }
  }
});
```

**Comment by mozibrand** [comment]
这是对的，我已经解决显示的问题，感谢你
==============================
That's right. I've solved the problem. Thank you very much~!!
