### ISSUE TITLE
Cannot install the package.

### ISSUE THREAD

**Issue by habib786** [CollectionFS/Meteor-CollectionFS#1021]
`meteor add cfs:standard-packages` The standard package install successfully but I am getting an error while installing `meteor add cfs:gridfs` package. 

The error is : 

> C:\Users\appbakerz\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
>       throw error;
>       ^
> 
> Error: EPERM: operation not permitted, unlink 'C:\Users\APPBAK~1\AppData\Local\Temp\mt-id8kde.e3pjq\npm\node_modules\mongodb\node_modules\bson'
>  => awaited here:
>     at Promise.await (C:\Users\appbakerz\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
>     at Object.files.rm_recursive.path [as rm_recursive] (C:\tools\fs\files.js:310:7)
>     at Object.files.rename (C:\tools\fs\files.js:1748:13)
>     at Object.files.renameDirAlmostAtomically.Profile [as renameDirAlmostAtomically] (C:\tools\fs\files.js:984:15)
>     at C:\tools\isobuild\meteor-npm.js:368:13
>     at Array.forEach (<anonymous>)
>     at Object.rebuildIfNonPortable (C:\tools\isobuild\meteor-npm.js:349:17)
>     at _.each (C:\tools\isobuild\bundler.js:422:19)
>     at Function._.each._.forEach (C:\Users\appbakerz\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
>     at Function.readDirsFromJSON (C:\tools\isobuild\bundler.js:421:9)
>     at C:\tools\isobuild\isopack.js:1099:10
>     at Array.forEach (<anonymous>)
>     at Function._.each._.forEach (C:\Users\appbakerz\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
>     at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:969:7)
>     at _.each (C:\tools\packaging\tropohouse.js:521:21)
>     at Array.forEach (<anonymous>)
>     at Function._.each._.forEach (C:\Users\appbakerz\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
>     at buildmessage.enterJob (C:\tools\packaging\tropohouse.js:520:13)
>     at C:\tools\utils\buildmessage.js:359:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at C:\tools\packaging\tropohouse.js:515:22
>     at C:\tools\utils\buildmessage.js:359:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at Object.download (C:\tools\packaging\tropohouse.js:427:20)
>     at C:\tools\packaging\tropohouse.js:600:22
>     at C:\tools\utils\buildmessage.js:359:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at exports.Tropohouse.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:597:20)
>     at C:\tools\project-context.js:814:25
>     at C:\tools\utils\buildmessage.js:359:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at C:\tools\project-context.js:813:20
>     at C:\tools\packaging\catalog\catalog.js:100:5
>     at C:\tools\utils\buildmessage.js:271:13
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
>     at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:812:13)
>     at C:\tools\project-context.js:285:9
>     at C:\tools\utils\buildmessage.js:359:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:352:34
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:350:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
>     at ProjectContext._completeStagesThrough (C:\tools\project-context.js:275:18)
>     at Profile.run (C:\tools\project-context.js:267:12)
>     at Function.run (C:\tools\tool-env\profile.js:490:12)
>     at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:266:13)
>     at C:\tools\cli\commands-packages.js:2155:20
>     at C:\tools\utils\buildmessage.js:271:13
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:264:29
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:262:18
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at C:\tools\utils\buildmessage.js:253:23
>     at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
>     at Object.capture (C:\tools\utils\buildmessage.js:252:19)
>     at Command.func (C:\tools\cli\commands-packages.js:2154:27)
>     at C:\tools\cli\main.js:1522:15

**Comment by harryadel** [comment]
What's the meteor version you're currently running? I'd appreciate it if you can provide us with a boilerplate to further examine this problem, thanks!

**Comment by habib786** [comment]
I used GridFs package and it is working fine.
