### ISSUE TITLE
update file 

### ISSUE THREAD

**Issue by pociej** [CollectionFS/Meteor-CollectionFS#114]
Hi is it possible to update file which is stored in collection ? I want to change file but leave id and meta. 

thx in advance

**Comment by neerbeer** [comment]
Any update to this issue ? My users can have only a single image and I thought I could upsert ... but that didn't work. Any updates ?

**Comment by leizard** [comment]
I have the same usecase and want to update my file

**Comment by PolGuixe** [comment]
+1

**Comment by pwldp** [comment]
+1

**Comment by kokokenada** [comment]
+1 

@leizard - were you able to preserve the ID's with a new FS File?
