### ISSUE TITLE
Question: dependent collections

### ISSUE THREAD

**Issue by cramhead** [CollectionFS/Meteor-CollectionFS#119]
I’m wondering do you guys have a plan on how to subscribe to the images collection when the image is reference by something else and that some is what is queried.

For example, if blog posts had images the app would query for the posts. The posts would have a reference to the image via the image’s id. This would seemingly imply that some processing has to be done be correctly publish the appropriate images. 

Would something like the pseudocode below be what's expected or do you have a better approach?

``` javascript
Meteor.publish('posts', function(paging, otherParameters){
    var posts = PostCollection.find({},...);
    var imageIds = [];
    foreach(post in posts){
        imageIds.push(post.imageId);
    }); 
    return [
        posts,
        images.find({_id: $in images});
    ];
}
```

Thank,
Marc

**Comment by digz6666** [comment]
@aldeed How did you solved url is undefined issue?
I use following code to display images, but url is undefined.

```html
{{# each cars }}
    {{# each images }}
        <li>
            <img src="{{ this.url }}" width="800" height="400" alt="">
        </li>
    {{/ each }}
{{/ each }}
```

Car collection has images property.
![bla](https://cloud.githubusercontent.com/assets/1736110/9134524/d060c4ec-3d3f-11e5-98c6-227540e1d117.png)

**Comment by digz6666** [comment]
I read following post and get the idea what's the URL structure is like:
https://groups.google.com/forum/#!topic/meteor-talk/gCxihZUm4HQ

I updated my code according to it, which feels like a hack:
```html
{{# each cars }}
    {{# each images }}
        <li>
            <img src="/cfs/files/images/{{ this._id }}" width="800" height="400" alt="">
        </li>
    {{/ each }}
{{/ each }}
```

And it worked, I don't know what's wrong.

**Comment by cramhead** [comment]
An alternative solution would be to use the cfs-ui package which as a url helper, i.e. https://github.com/CollectionFS/Meteor-CollectionFS#url

**Comment by digz6666** [comment]
@cramhead I've installed cfs:ui package but it's still same.

**Comment by digz6666** [comment]
Created new issue here #778
