### ISSUE TITLE
Question: encrypting a file before storing it in the db

### ISSUE THREAD

**Issue by tanis2000** [CollectionFS/Meteor-CollectionFS#189]
Hi,

I'd like to know if the following scenario is manageable with CollectionFS.

I'd like to let the user upload a file. The file should be encrypted with AES256 before being written to mongo.

Of course, that same file should be decrypted before being passed back to the client when downloading it.

Is this achievable with CollectionFS? Can you point me to a similar example, if any?
Thanks in advance!

**Comment by dguedry** [comment]
I realize this is an old thread, but does the transform work on the client yet?  Was there any plan to do it?  I've been working on an encryption library for all things Meteor.  The focus is on encrypting client-side prior to uploading.  If I read the docs correctly, this is not currently supported using built-in CollectionFS hooks?
