### ISSUE TITLE
Publish FS.Collection using cursor.observe

### ISSUE THREAD

**Issue by copleykj** [CollectionFS/Meteor-CollectionFS#198]
I'm trying to publish records from an FS.Collection using an cursor observer in my publish function.. Everything in my publish function seems to be working correctly but calling the publications added() method does not seem to send them down the the client like they should be.

**Comment by jeanfredrik** [comment]
I'm not sure if this is related to your issue, or if this still is an issue, but I had problem publishing a FS.Collection using cursor.observe as well. The solution for me was that I had to use "cfs.images.filerecord" instead of "images" as name for the published collection:

```js
Images = new FS.Collection("images")

Meteor.publish('images', function() {
	// return images.find();
	var pub = this;
	var handle = images.find().observeChanges({
		added: function (id, fields) {
			console.log('added', id)
			pub.added('cfs.images.filerecord', id, fields);
		},
		changed: function (id, fields) {
			pub.changed('cfs.images.filerecord', id, fields);
		},
		removed: function (id) {
			pub.removed('cfs.images.filerecord', id);
		}
	});
	pub.ready();
	pub.onStop(function() {
		handle.stop();
	});
});
```

**Comment by Oizor** [comment]
@jeanfredrik Thx for the contribution, this works for me!

**Comment by Nesvet** [comment]
Wasted a lot of time. Thanks, @jeanfredrik, – that's absolutely right. Additionally, original Mongo collection lies under "files" property, so you can find desired name calling Images.files._name. Wow.

**Comment by yoh** [comment]
thanks for this tips @jeanfredrik !
