### ISSUE TITLE
fromURl serverside upload - how to with new API?

### ISSUE THREAD

**Issue by ghost** [CollectionFS/Meteor-CollectionFS#203]
What's the proper approach for using fromUrl for a server side upload using the new APIs, I've created a simple example, and I'm experiencing the following problem:  has no method 'fromUrl' 

Is there any obvious mistake in the approach below, or is it because the devel version is still in flux?

APPROACH:

creating a test meteor application
- with collectionFS devel on blaze-rc0
- for testing server upload .fromUrl
  - reason: I'm experiencing an error
# 

mrt --release blaze-rc0 create test-fromUrl

..edit smart.json
---result---
{
  "packages": {
    "iron-router": {
      "git": "https://github.com/EventedMind/iron-router.git",
      "branch": "blaze-integration"
    },
    "blaze-layout": {
      "git": "https://github.com/EventedMind/blaze-layout.git",
      "branch": "devel"
    },
    "collectionFS": {
      "git": "https://github.com/CollectionFS/Meteor-CollectionFS.git",
      "branch": "devel"
    },
    "cfs-gridfs": {
      "git": "https://github.com/CollectionFS/Meteor-cfs-gridfs.git",
      "branch": "master"
    },
    "cfs-filesystem": {
      "git": "https://github.com/CollectionFS/Meteor-cfs-filesystem.git",
      "branch": "master"
    },
    "cfs-handlebars": {
      "git": "https://github.com/CollectionFS/Meteor-cfs-handlebars.git",
      "branch": "shark"
    },
    "cfs-graphicsmagick": {
      "git": "https://github.com/CollectionFS/Meteor-cfs-graphicsmagick.git",
      "branch": "master"
    }
  }
## }

meteor remove autopublish insecure
mrt add iron-router
mrt add blaze-layout
mrt add collectionFS
mrt add cfs-gridfs
mrt add cfs-filesystem
mrt add cfs-handlebars
mrt add cfs-graphicsmagick
mrt update

..edit test-fromUrl.js
---result---
// common.js
var Images = new FS.Collection("images", {
    stores: [new FS.Store.FileSystem("images", {path: "~/uploads"})]
});

if (Meteor.isClient) {
  Template.hello.greeting = function () {
    return "Welcome to test-fromUrl.";
  };

  Template.hello.events({
    'click input': function () {
      // template data, if any, is available in 'this'
      if (typeof console !== 'undefined')
        console.log("You pressed the button");
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
    var fileObj = FS.File.fromUrl('http://www.fourwinds10.net/resources/uploads/images/meteor-shower-nightsky-jpl-nasa-gov.jpg', 'image.jpg');
    Images.insert(fileObj);
  });
## }

meteor
---output---
user@localhost:~/devel/test-fromUrl# meteor
[[[[[ ~/devel/test-fromUrl ]]]]]

=> Started proxy.
=> Meteor 0.7.1.2 is available. Update this project with 'meteor update'.
=> Started MongoDB.
W20140317-15:21:25.468(1)? (STDERR) Failed to load c++ bson extension, using pure JS version
I20140317-15:21:25.689(1)? TempStore: /tmp/cfs
W20140317-15:21:25.794(1)? (STDERR)
W20140317-15:21:25.795(1)? (STDERR) /users/user/.meteor/tools/6c38ffe2fb/lib/node_modules/fibers/future.js:173
W20140317-15:21:25.796(1)? (STDERR)                                             throw(ex);
W20140317-15:21:25.798(1)? (STDERR)                                                   ^
W20140317-15:21:25.802(1)? (STDERR) TypeError: Object function (ref, createdByTransform) {                                                                 // 9
W20140317-15:21:25.802(1)? (STDERR)   var self = this;                                                                                            // 10
W20140317-15:21:25.803(1)? (STDERR)                                                                                                               // 11
W20140317-15:21:25.803(1)? (STDERR)   self.createdByTransform = !!createdByTransform;                                                             // 12
W20140317-15:21:25.804(1)? (STDERR)                                                                                                               // 13
W20140317-15:21:25.804(1)? (STDERR)   if ((typeof File !== "undefined" && ref instanceof File) ||                                                 // 14
W20140317-15:21:25.805(1)? (STDERR)     (typeof Blob !== "undefined" && ref instanceof Blob)){                                                    // 15
W20140317-15:21:25.805(1)? (STDERR)     self.attachData(ref);                                                                                     // 16
W20140317-15:21:25.805(1)? (STDERR)   } else {                                                                                                    // 17
W20140317-15:21:25.806(1)? (STDERR)     if (typeof ref !== 'object') {                                                                            // 18
W20140317-15:21:25.806(1)? (STDERR)       ref = {};                                                                                               // 19
W20140317-15:21:25.806(1)? (STDERR)     }                                                                                                         // 20
W20140317-15:21:25.807(1)? (STDERR)                                                                                                               // 21
W20140317-15:21:25.807(1)? (STDERR)     // Extend self with filerecord related data                                                               // 22
W20140317-15:21:25.807(1)? (STDERR)     _.extend(self, FS.Utility.cloneFileRecord(ref));                                                          // 23
W20140317-15:21:25.808(1)? (STDERR)   }                                                                                                           // 24
W20140317-15:21:25.808(1)? (STDERR) } has no method 'fromUrl'
W20140317-15:21:25.809(1)? (STDERR)     at app/test-fromUrl.js:24:30
W20140317-15:21:25.809(1)? (STDERR)     at /users/user/devel/test-fromUrl/.meteor/local/build/programs/server/boot.js:159:61
W20140317-15:21:25.810(1)? (STDERR)     at Array.forEach (native)
W20140317-15:21:25.810(1)? (STDERR)     at Function._.each._.forEach (/users/user/.meteor/tools/6c38ffe2fb/lib/node_modules/underscore/underscore.js:79:11)
W20140317-15:21:25.811(1)? (STDERR)     at /users/user/devel/test-fromUrl/.meteor/local/build/programs/server/boot.js:159:5
=> Exited with code: 8

**Comment by vuhpham** [comment]
@Rebolon Same to me

**Comment by nikhildaga** [comment]
I am experiencing the same.
