### ISSUE TITLE
cfs-s3: Not all store copies are present in file.copies after upload

### ISSUE THREAD

**Issue by ghost** [CollectionFS/Meteor-CollectionFS#208]
Hi,

I have a FS.Collection with two S3 stores. One store has an transformer (thumbnail store) and one doesn't have a transformer (full size store). The store with the transformer is the one with the highest priority. When I upload a photo, only the copy of the full size store is in file.copies. When I restart Meteor, the second copy (thumbnail) gets added.

I debugged it but couldn't pinpoint what exactly is the source of the problem.
I found out that https://github.com/CollectionFS/Meteor-cfs-storage-adapter/blob/master/storageAdapter.server.js#L108 is called twice for the full size store, that is the one that is present in file.copies after the upload.

This is my server code:

``` javascript
var _ = Meteor.require('lodash');

FS.debug = true;

/**********************************************
 * File storages
 **********************************************/

var s3options = {
  region: Meteor.settings.AWS.region,
  accessKeyId: Meteor.settings.AWS.accessKeyId,
  secretAccessKey: Meteor.settings.AWS.secretAccessKey,
  bucket: 'eventport-photos',
  ACL: 'public-read'
};

var fullSizeFolder = 'full/';
var thumbnailSizeFolder = 'thumbnail/';

var s3eventPhotos = new FS.Store.S3('eventPhotos', _.extend({}, s3options, {
  folder: fullSizeFolder
}));

var thumbnailFormat = Meteor.settings.photoFormats.eventPhoto.formats[0];
var s3eventPhotosThumbnails = new FS.Store.S3('eventPhotosThumbnails', _.extend({}, s3options, {
  folder: thumbnailSizeFolder,
  transformWrite: function(file, readStream, writeStream) {
    this.gm(readStream, file.name)
      .resize(thumbnailFormat.width, thumbnailFormat.height + '^')
      .gravity('Center')
      .crop(thumbnailFormat.width, thumbnailFormat.height + '^')
      .stream()
      .pipe(writeStream);
  }
}));

/**********************************************
 * File collections
 **********************************************/

var defaultPhotoFilter = {
  maxSize: 5242880, // 5 MB
  allow: {
    contentTypes: ['image/*']
  }
};

eventPhotos = new FS.Collection('eventPhotos', {
  stores: [s3eventPhotosThumbnails, s3eventPhotos],
  filter: defaultPhotoFilter
});
```

**Comment by sahanDissanayake** [comment]
@Sanjo Did you get this to work ? I may be having the same issue
https://github.com/CollectionFS/Meteor-CollectionFS/issues/912

Only way I could fix this was to use two different buckets

**Comment by Menda** [comment]
I confirm I have the same issues, or even worst.

I'm using:

```
cfs:access-point@0.1.49
cfs:autoform@2.2.1
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:graphicsmagick@0.0.18
cfs:gridfs@0.0.33
cfs:http-methods@0.0.30
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:s3@0.1.3
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.3
cfs:tempstore@0.1.5
cfs:ui@0.1.3
cfs:upload-http@0.0.20
cfs:worker@0.1.4
```

So basically I'm uploading files and some of them appear cut up, not the whole. Second thing is that using in both thumbnails and images store, only it's storing in the images one (both in same bucket). Third thing is that some files which should be the original appear resized, and some not.

**Comment by Menda** [comment]
OK, so I dedicated another bucket for the thumbs and not **works**. Anyway I think there should be a bug report regarding this issue, because you cannot point two different storages to the same bucket.

Greetings.
