### ISSUE TITLE
[1.2.0] decouple dependency on the cfs-worker package

### ISSUE THREAD

**Issue by raix** [CollectionFS/Meteor-CollectionFS#220]
Have the core collectionFS work without the FileWorker - but when installed it should shift to file worker.

**Comment by rhyslbw** [comment]
Can this be closed since it seems no longer part of the plan?

> We had an idea about a super slim package combination - but the worker enables scalability and should also improve single instance setups (those would prop. be rare)

https://github.com/CollectionFS/Meteor-CollectionFS/issues/214#issuecomment-90822573

**Comment by raix** [comment]
Yep, thanks :)
