### ISSUE TITLE
[1.2.0] Add a db backing spinal queue for PQ

### ISSUE THREAD

**Issue by raix** [CollectionFS/Meteor-CollectionFS#236]
We should have a spinal queue for the power-queue that resides in the db.
It should be possible to have multiple instances of power-queue accessing the same task collection - without any overlap, a task should only be performed once.

Properties of a db spinal queue:
* [ ] It should be able to lock a task in the db, making sure only one instance is handling the task
* [ ] There should also be a mechanism for releasing (unlocking) and release by timeout
* [ ] We should be able to have the spinal queue trigger `auto run` in the pq - could be by observing the task collection - if a task is added from another collection

There are some things to think about :)

**Comment by rhyslbw** [comment]
Right now my highest priority for contribution within cfs is to improve the worker package. [I've been assisting](https://github.com/vsivsi/meteor-job-collection/issues/59) @vsivsi with testing of [job-collection](https://github.com/vsivsi/meteor-job-collection) to support remote workers, and would like to raise the idea of using it over pq. Here's why I think this is a good idea:

- Super powerful and configurable to meet all the requirements listed above (Pretty sure the second option could be done within the worker function manually).
- Reduce the development overhead of cfs, get the benefit of existing job-collection user's testing and feedback.
- It's one issue away from being [production ready](https://github.com/vsivsi/meteor-job-collection/issues/31)
- Test suites on both the job class and [job-collection](https://github.com/vsivsi/meteor-job-collection/blob/master/job_collection_tests.coffee) 
- It's also possible to run the workers outside of the Meteor environment, although this is more of a point of interest for this use case.

I've created a [repo](https://github.com/rhyslbw/jc-remote-worker-observer) demonstrating a remote observer-based worker.

Thoughts?

**Comment by raix** [comment]
I think the PQ is built for pushing tasks while job-collection is doing pulling? if so I'm for job-collection.

The pattern I wanted was to have worker instances request a job when they have ressources. One super simple pattern is to have a collection for workers to lookup any "pending" tasks.
If the worker finds a task it should "book" the task and set a timeout for the booking.

Could be really basic like:

```js
var jobCollection = new Mongo.Collection('worker-jobs');

var timeout = 30 * 1000; // ms
var isProcessing = 0;

Meteor.setInterval(function() {
  // Don't lookup db if processing
  if (isProcessing > 0) return;
  isProcessing++;

  var task = jobCollection.findOne({ status: 'pending' }, { sort: { createdAt: -1 } });

  if (task) {
    // Great found a task, try to reserve
    var reserved = jobCollection.update({
      $and: [
        { _id: task._id },
        { status: 'pending' },
      ]
    }, {
      $set: {
        status: 'processing',
        timeout: new Date( (new Date()).getTime() + timeoutMs)
      }
    });
  }

  if (reserved) {
    // Do job
    work(task);

    // Update task unless its timed out
   var ok = jobCollection.update({ $and: [
    { _id: task._id },
    { status: 'processing' }
   ] }, { $set: { status: 'done' } });

   if (!ok) {
    // We didn't make it? report low timeout
   }
  }

  isProcessing--;
}, 1000);

// Help reset jobs that timeout
Meteor.setInterval(function() {
  // Maybe use some backoff?
  jobCollection.update({ timeout: { $lt: new Date() } }, { $set: { status: 'pending' } });
}, 5000);
```

**Comment by rhyslbw** [comment]
A job-collection can have multiple worker groups configured on the client or server. They can either be polling the collection for `ready` jobs that match their assigned `jobType` or can be observing the collection for changes using a collection.find() to restrict the triggering based on any number of conditions. The workers can create jobs that get dropped back into the collection, so the result of the job can dictate the flow of the process. You can also create multiple job-collections, and even link the collection to a dedicated database and/or a separate ddp server.

By pushing do you mean something like the uploader? I've not looked at the uploader code for a while so I'm talking generally eith the following. The result of each insert on the job collection could be a new job with a jobType of 'upload'. The client-side worker group observes this change to the collection and triggers a worker to complete it. At the end of this job once completed, the next job could be added to the queue, with a server-side worker group observing the collection for tasks they are assigned to. In the mix here are a range of controls you'd expect from queues, so priority, backoff, retries etc are all there. A single server side worker queue could handle all of these other tasks, in tunable way. 

Now let's consider scaling. Remote workers can be configured to establish a connection to the job-collection living on another server or app via ddp, and subscribe to the triggering publications with some straightforward SHA hashed authentication. This starts to get really interesting when files live in a cloud solution like S3, as no one server is managing the files. Using something like meteorhacks:cluster gives us a layer to manage the cluster of apps and take advantage of multi-core servers.

I've really only just touched on the major points here, so if your ears are pricking up I'd suggest going over the [job-collection docs](dev) to get a sense for the thought that's gone into it. Please note that I've linked to the dev branch, which should be released as 1.0 any day now

**Comment by vsivsi** [comment]
Hi @rhyslbw & @raix   FYI, version 1.0.0 of [job-collection](https://atmospherejs.com/vsivsi/job-collection) just went up on Atmosphere. Enjoy!

**Comment by rhyslbw** [comment]
Thanks for the heads up, nice timing :-)

**Comment by aldeed** [comment]
@vsivsi haven't tried it yet, but it looks like an amazing tour de force. It does not support job scheduling with laterjs, does it? `percolate:synced-cron` works well for me in a few apps for sending emails and doing other work at specific times times on specific days, but it would be nice to have the flexibility of using some simple nodejs workers to do it if the same laterjs parsing could be used.

Not to get off topic. Also looks cool for CFS. :)

**Comment by vsivsi** [comment]
@aldeed  Sorry, no support for later.js yet. The focus is a little less on cron-like scheduling, and more on queuing up tons of work and parceling it out to distributed workers to achieve scalability. It does support delayed jobs, and jobs that recur, etc. But alas, not with the expressiveness of later.js.  I'm sure it could be added if there is sufficient demand; you're not the first to ask...  ;-) 

```js
var job = new Job(jc, 'dailyEmail', { <data> })
   .after(new Date( <whenever> ))
   .repeat({ wait: 24*60*60*1000 })
   .save()
```

**Comment by aldeed** [comment]
No worries. It's easy enough to schedule a synced cron that in turn schedules an immediate JC job.

**Comment by vsivsi** [comment]
Or perhaps better yet, to use later.js in your worker to compute the next time to run and schedule the next future job from there. This is essentially what happens automatically with the `.repeat()` modifier, but currently it only supports `wait` and `unitl`. It would be straightforward to add a `later` option, and have it calculate the next time to run, rather than using the current options.

**Comment by vsivsi** [comment]
Or, rather than chage repeat, I'd probably just add a `later()` modifier method to use instead.

**Comment by aldeed** [comment]
Yeah, that makes sense to me.

**Comment by raix** [comment]
@vsivsi cool thanks!
@rhyslbw we could give it a try

**Comment by rhyslbw** [comment]
@raix copy

**Comment by vsivsi** [comment]
@aldeed   I added experiemental support for later.js in scheduling repeating jobs on this branch.  
https://github.com/vsivsi/meteor-job-collection/tree/laterJS

**Comment by raix** [comment]
Mental note: See if node package `worker-farm` can be of any help

**Comment by rhyslbw** [comment]
I'm going to close this for now to keep the focus on a job-collection implementation. Discussion ahead of the PR is in https://github.com/CollectionFS/Meteor-CollectionFS/issues/214

**Comment by raix** [comment]
:+1:
