### ISSUE TITLE
Better way to get copy info from fileObj

### ISSUE THREAD

**Issue by aldeed** [CollectionFS/Meteor-CollectionFS#261]
We should deprecate fileObj.getCopyInfo (or make it internal if we still need it), and change name, size, and type props into prototype functions instead. Similar to `url`, they should accept an optional store name and return that info instead.

``` js
fileObj.size();
fileObj.size({store: 'thumbs'});
fileObj.type();
fileObj.type({store: 'thumbs'});
fileObj.name();
fileObj.name({store: 'thumbs'});
// also setters
fileObj.setSize(100);
fileObj.setSize(100, {store: 'thumbs'});
fileObj.type('image/png');
fileObj.type('image/png', {store: 'thumbs'});
fileObj.name('pic.png');
fileObj.name('pic.png', {store: 'thumbs'});
// store original file props with _ instead
fileObj._size;
fileObj._type;
fileObj._name;
```

Easy to use as UI helpers, too:

``` html
{{#with fileObj}}
  Original size: {{this.size}}
  {{#if this.hasCopy 'thumbs'}}
    Thumbnail size: {{this.size store='thumbs'}}
  {{/if}}
{{/with}}
```

**Comment by ubald** [comment]
I don't think it getCopyInfo should be totally deprecated. When saving the image dimensions in a copy, for example, it is still needed to retrieve that information.
