### ISSUE TITLE
Delete element from collection during upload

### ISSUE THREAD

**Issue by Chaosbohne** [CollectionFS/Meteor-CollectionFS#263]
Whats the best practise to delete files of a CollectionFS that are still uploading?

Szenario:
I want to have filevalidation (size,type etc.) if a user picks a file. The validation is set with filters inside my collection. Now i pass this file to the collection with an insert, because i havent found a method that gives me the possibilty to make a simple isValidCheck() without uploading.

Now when a user decides to change the image. I had to delete the older image out of CollectionFS and if the image is still uploading there are some ugly error messages in console. The client still tries to upload while he cant because the file was already deleted.

Is there a method to tell the fileObj that i want to stop upload before deleting the image?

Iam using dev-branch.

Whats best practise?

**Comment by sksourou** [comment]
hi @bitomule did u find a solution delete during the upload ?

**Comment by bitomule** [comment]
I don't remember. I was using a fork that allowed multiple server setups and cancel worked better. I'm not doing a lot of meteor now but I won't use CollectionFS again. I'll try to do something smaller using packages for different parts.
