### ISSUE TITLE
upload track and do something after upload complete

### ISSUE THREAD

**Issue by yozawiratama** [CollectionFS/Meteor-CollectionFS#277]
Hi everyone,
I have a problem about reactivity and unfinished upload process.
this is my simple code

```
<input type="file" class="myFileInput" />
<img src="{{imgsource}}" height="200px" alt="thumbnail" />

 Images = new FS.Collection("images", {
stores: [new FS.Store.FileSystem("images", FS.Store.rootPath)]
});


Template.hello.imgsource = function () {
    var img = Images.files.findOne({_id :Session.get('uploadedfileId')});
    console.log(img);
    if (img)
        return '/cfs/files/images/' + img._id + '/' + img.name + '?store=images';
};
Template.hello.events({
    'change .myFileInput': function (event, template) {
        FS.Utility.eachFile(event, function (file) {
            Images.insert(file, function (err, fileObj) {
                //Inserted new doc with ID fileObj._id, and kicked off the data upload using HTTP
                Session.set('uploadedfileId', fileObj._id);
            });
        });
    }
});
```

in this case, after the event 'change' run, 
1. write data to collection
2. HTTPUploadTransferQueue Autostart 
3. GET http://localhost:4000/cfs/files/images/yKnvtHfL2YhT3D9L3/Photo.jpg?store=images 503 (Service Unavailable) 
4. HTTPUploadTransferQueue RELEASED
5. HTTPUploadTransferQueue ENDED 

it make my can't show because 503 service unavailable.
how to solve this case?
in my mind, i must wait until upload ended and after that update Session, but how to do it? or is there any other way?
please help me :+1:

**Comment by Cyval** [comment]
Is there any support for react here?
