### ISSUE TITLE
Deploy on meteor.com – cfs:graphicsmagick could not find gm or im

### ISSUE THREAD

**Issue by nooitaf** [CollectionFS/Meteor-CollectionFS#299]
Just tried to do a deploy to the meteor.com server and got this error, any idea how to solve this? Did i miss something? 

```
[Fri May 02 2014 10:36:53 GMT+0000 (UTC)] INFO STATUS starting -> running
[Fri May 02 2014 10:36:54 GMT+0000 (UTC)] WARNING Failed to load c++ bson extension, using pure JS version
[Fri May 02 2014 10:36:54 GMT+0000 (UTC)] WARNING WARNING:
cfs:graphicsmagick could not find "graphicsMagic" or "imageMagic" on the
system.

I just checked PATH to see if I could find the GraphicsMagick or ImageMagic
unix/mac os/windows binaries on your system, I failed.

Why:
1. I may be blind or naive, help making me smarter
2. You havent added the path to the binaries
3. You havent actually installed GraphicsMagick or ImageMagick

*** Make sure "$PATH" environment is configured "PATH:/path/to/binaries" ***

Installation hints:
* Mac OS X "brew install graphicsmagick" or "brew install imagemagick"
* Linux download rpm or use packagemanager
* Centos "yum install GraphicsMagick"* Windows download the installer and run
[Fri May 02 2014 10:36:54 GMT+0000 (UTC)] WARNING Failed to load c++ bson extension, using pure JS version
```

**Comment by travisdahl** [comment]
Are there any resize options/alternatives that will work on the free meteor servers? I know both `im` and `gm` have many valuable features on top of resizing but I would imagine the most popular use case for `collectionfs` is probably resizing before upload. And I would imagine resizing may be a solvable problem without depending on `gm/im`, maybe by using html canvas? Just curious if there were any alternatives that you knew of for the meteor servers.

**Comment by aldeed** [comment]
http://camanjs.com/

**Comment by travisdahl** [comment]
@aldeed Thanks for the quick reply, how were you proposing that to be used? On the client or the server? I am using the S3 storage adapter. So Im guessing I would need to use caman on the server and do the transformation in the `beforeWrite` or `transformWrite` functions? Is this what you were thinking?

I see that there is node methods for caman but couldnt find any meteor packages for it. There was one but it only contained the frontend portions of caman

**Comment by aldeed** [comment]
I was thinking client since that frees up your server resources, but if you need to be sure the resizing happens, then server is the only safe way. You could also do client first, server as backup.

You can drop the caman files in /lib to try it out and make a package if necessary. I haven't used it yet, but we've talked about adding some kind of package or official support for it in CFS.

**Comment by MilosStanic** [comment]
This is very interesting (caman.js). I mean freeing server resources to do resizing on client is a tempting idea. The problem I see is the following use case: 
1. I select image to upload in browser
2. Browser accepts it.
3. caman.js creates a thumbnail (or any other transform)
4. Upload original and thumbnail to server and insert them to, say, `Images` collection, one in the `original` store, and the other in the `thumbnail` store. 

I don't see here how to upload both and tell Meteor to save them to separate stores of the same collection. 

Is this possible?
