### ISSUE TITLE
Hang and failed uploads

### ISSUE THREAD

**Issue by cramhead** [CollectionFS/Meteor-CollectionFS#309]
When I attempt to upload multiple files at a time the uploads hang.
When I turn on FS.debug I see 

```
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
token: eyJhdXRoVG9rZW4iOiJxbXBCXzhocTI4R2dBU1dlejNDVmhVTUVoOUFZeHJ6MW1GSWtNaGxaSGJKIn0=
```

After a long while an upload finishes, but the other uploads fail. The database entries are there but the files are not in the filesystem.

**Comment by neopostmodern** [comment]
Would it be possible that when the error gets thrown, there is a reference to this thread? Or some other information page?  
Intuitively one assumes it's a problem with CollectionFS and doesn't dig into the NGINX config...

**Comment by aldo235** [comment]
have the solution? couse in my local i can upload 4MB image but in server if upload more then 1MB got errors

**Comment by raix** [comment]
@aldo235 What errors are you getting - I'm thinking latency?

**Comment by aldo235** [comment]
im using PM2 meteor for deploy,  
`Error: "Queue" failed [413] <html>
 <head><title>413 Request Entity Too Large</title></head>`
like that
