### ISSUE TITLE
Mongo Backups

### ISSUE THREAD

**Issue by ccorcos** [CollectionFS/Meteor-CollectionFS#330]
I found [this](http://stackoverflow.com/questions/16816860/meteor-how-can-i-backup-my-mongo-database) post which talks about using `mongodump` for backing up. But I haven't found much for backing up the filesystem or gridfs. Any ideas?

**Comment by clarkritchie** [comment]
So it should be possible to ```mongodump``` / ```mongorestore```?  I just did this from my hosting provider to my localhost and all my images are broken.  Any recommendations?
