### ISSUE TITLE
URL Availability in Insert Callback

### ISSUE THREAD

**Issue by jacksondc** [CollectionFS/Meteor-CollectionFS#351]
I'm using `CollectionFS`, `cfs-gridfs`, `cfs-ejson-file`. In the callback after I insert a file into a collection, I can call the `url` method of the file object, but all I get is null. If I wait for one second, the URL will be available. A similar problem is that if I load a page that displays files (using the `url` method as a handlebars helper) before the URL is available, the files won't load until I refresh the page.

Is there a callback when the URL gets assigned, or a way to reactively monitor the url?

**Comment by robwatkin** [comment]
Hi @aldeed ,

I'm not sure if this is a problem with CollectionFS or summernote but any advice would be appreciated.

Following your comment above from last Jul 31 I am doing...
    
    fileObj.on("uploaded", function() {
            console.log('editPage onImageUpload CmsImages.insert fileObj.on uploaded...');
            imageURL = '/cfs/files/cms-images/' + fileObj._id;
            $dom = $("<img>").attr('src',imageURL);
            $summernote.summernote("insertNode", $dom[0]);

and then passing imageURL to summernote's insert method whic then throws

    GET http://localhost:3000/cfs/files/cms-images/mZsMWhrF5oZwQFbdG 503 (Service Unavailable)

After a page refresh everything looks ok.

Thanks

**Comment by leizard** [comment]
Hi @aldeed , I have problem when using fileObj.on("stored", func) on the server . I use CollectionFS S3. This is what I have done on the server

```
Files.insert(fsFile, function (err, fileObj) {
            if (err) {
               server.log(err);
            } else {
                fileObj.on("stored", function() {
                    server.log('good');
                });

            }
        });
```

and it has following error : 

```
W20151119-15:38:53.774(7)? (STDERR) /home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/request.js:32
W20151119-15:38:53.774(7)? (STDERR)           throw err;
W20151119-15:38:53.775(7)? (STDERR)                 ^
W20151119-15:38:53.778(7)? (STDERR) NoSuchKey: The specified key does not exist.
W20151119-15:38:53.779(7)? (STDERR)     at Request.extractError (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/services/s3.js:328:35)
W20151119-15:38:53.779(7)? (STDERR)     at Request.callListeners (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
W20151119-15:38:53.779(7)? (STDERR)     at Request.emit (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
W20151119-15:38:53.779(7)? (STDERR)     at Request.emit (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/request.js:604:14)
W20151119-15:38:53.780(7)? (STDERR)     at Request.fsm.setupStates.transition (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/request.js:21:12)
W20151119-15:38:53.780(7)? (STDERR)     at AcceptorStateMachine.runTo (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/state_machine.js:14:12)
W20151119-15:38:53.780(7)? (STDERR)     at /home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/state_machine.js:26:10
W20151119-15:38:53.780(7)? (STDERR)     at Request.fsm.setupStates.err.domainEmitter (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/request.js:22:9)
W20151119-15:38:53.781(7)? (STDERR)     at Request.AWS.Request.inherit.emitEvent (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/request.js:606:12)
W20151119-15:38:53.781(7)? (STDERR)     at Request.callListeners (/home/duonglei/Namsoft/Projects/SEN/.meteor/local/isopacks/cfs_s3/npm/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
=> Exited with code: 8

```

Don't know what is the cause of this. My best guess is something related to S3 policies ?

**Comment by travisdahl** [comment]
@leizard did you ever find the solution to your problem? I am getting the same error when deployed to heroku but not when i am running locally or on the meteor servers. Also using S3

**Comment by boostbob** [comment]
same issue, thanks.
It fixed i move the db insert codes the fileObj uploaded event callback.
