### ISSUE TITLE
Best/Correct way to store images in public dirrectory and get their url in the callback?

### ISSUE THREAD

**Issue by SylvainBigonneau** [CollectionFS/Meteor-CollectionFS#355]
I am trying to store a facebook profile picture from the user when he first logs in using facebook, and save the url to that uploaded picture on my server. I am facing a couple issues:
- First off, here is how I define my image collection, in collections/images.js:

``` javascript
Images = new FS.Collection("images", {
  stores: [new FS.Store.FileSystem("images", {path: process.env.PWD+'/public/uploads'})]
});
```

This raises an error on the client due to the fact that this code is not just executed on serverside:
`ReferenceError: process is not defined`

Is there a better solution for this? Or should I only define this collection in my server folder?

Then here is my biggest problem: on every user creation, I want to create an image and store its url pointing to the image on my server (for anonymity purposes):

``` javascript
Accounts.onCreateUser(function(options, user) {
    if (options.profile) {
        Images.insert("http://graph.facebook.com/" + user.services.facebook.id + "/picture/?width=300&height=300", function (err, fileObj) {
            options.profile.picture = fileObj.url({store: 'images'});
            user.profile = options.profile;
        });
    }
    return user;
});
```

Problem is: that call to url method returns null, no matter what... Is there something I am missing there?

I should mention that the image is correctly downloaded and created in my public/uploads folder

**Comment by rushikeshandroid** [comment]
If a store/delete an image from public directory, then the" =>Client modified -- refreshing" appears on server console and the web page is refreshed.... What to do to avoid this ?

**Comment by nooitaf** [comment]
@rushikeshandroid simple answer: dont store files inside your meteor project.
