### ISSUE TITLE
Add fileObj.copyData(fromStore, toStore)

### ISSUE THREAD

**Issue by copleykj** [CollectionFS/Meteor-CollectionFS#371]
So basically I have a whole bunch of files that I've stored using the gridFS adapter and I was wondering if there is a way that I could use CFS to transition into using the AWS S3 adapter. I seem to remember some talk of CFS creating new copies being created for stores that didn't previously exist but I could be completely mistaken..

**Comment by mxab** [comment]
Hi,
I started working on this issue, I made a copyData(sourceStore,targetStore) method that takes the pipes it the data from the source store to the read store
https://github.com/mxab/Meteor-cfs-file/compare/CollectionFS:master...master?diff=split&name=master

It kind of works in the way that some data is then in the target store, but I cannot access it, actually if I refresh the page the application crashes
see this example app
https://github.com/mxab/cfs-copy-data-example

Any suggestion what I need to add?

**Comment by mxab** [comment]
ok I crashed because the "copies.<targetstore>" values were wrong. it now works but I still need to refresh the page before I see the images from the new store.

anything else i missed?

**Comment by aldeed** [comment]
@mxab, looks good. I commented on the PR.

**Comment by mxab** [comment]
@aldeed @raix I think I want to extend the copyData so that I can take the targets store transformWrite into account
so instead of 
```targetStorage.adapter.createWriteStreamForFileKey(targetKey);```
i would do
```fileObj.createWriteStream(targetStoreName);```

any thoughts on that?

**Comment by raix** [comment]
@mxab Make sense,

I think your pattern makes it more predicable in terms of whats going to happen - so its easier to reason about, and thats a good thing.

Would it still make sense to have a `rawCopy`/`replicate` eg. copying the data 1:1? - or is the `copy` using the transformRead and transformWrite all we need.

-

Mental note thinking about the future feature:

@aldeed + me have been talking about sync way back - in the case of doing sync with a storage. *(relevant when adding dropbox/google drive etc. as SA's)*

We talked about having a `reverseTransform` (or transformToOriginal) - it has some complications, not sure we ever agreed 100% *(its a while back)*

We might introduce a `fileObj.syncFrom(sourceSA, [destinationSA])` and add the option of a `reverseTransform` that, if set, the source would stream to before going to the destination SA(s).

*(so we dont need the rawCopy in the case of sync)*

**Comment by aldeed** [comment]
I agree it's a good idea to pass through transformWrite in most cases, but I guarantee someone will also want a `skipTransform` option, so you should probably just add that right away.

You could change the `move` arg into an options object, e.g.

```js
fileObj.copyData(fromStore, toStore);
fileObj.copyData(fromStore, toStore, {move: true});
fileObj.copyData(fromStore, toStore, {move: true, skipTransform: true});
fileObj.copyData(fromStore, toStore, {skipTransform: true});
```

Sync support is a can of worms. But we'll have to figure it out at some point.
