### ISSUE TITLE
filename option with url helper don't work with download=true

### ISSUE THREAD

**Issue by elbowz** [CollectionFS/Meteor-CollectionFS#376]
Sorry if I'm testing your patience ;)

there is also this little bug (as described in the subject)

{{url filename='ciao' download=true}}

Filename is ignored...

I don't know where I have to see (file/package), and where you have register the server route. you are more speedy of me, of course!

thanks :)

**Comment by adamsidiali** [comment]
Thanks for the great PR & feature. Makes things so simple!
