### ISSUE TITLE
Binary File Transfers Corrupted? Truncated?

### ISSUE THREAD

**Issue by petrocket** [CollectionFS/Meteor-CollectionFS#41]
I'm using meteorite 0.4.9, meteor 0.6.x and the latest collectionFS and when I upload any files (.jpg and .png tested) the resulting files are corrupt and shorter.  Could this be an encoding issue?  I did a file comparison and besides being a bit shorter the saved file also had a lot of characters that were different (in hex).

I'm hoping coffeescript doesn't have something to do with it because all my server code uses that and meteor 0.6.x got rid of global variables so it has caused some minor issues declaring collection instances.

**Comment by maitrid** [comment]
i'm using Meteor 1.2, and have the same problem. i'm using 'binary' as encoding,
