### ISSUE TITLE
Error in method "/cfs/files/:value/:value/:value/", Error: TypeError: Cannot read property 'pdfs' of undefined

### ISSUE THREAD

**Issue by krishnaff** [CollectionFS/Meteor-CollectionFS#430]
Hello everyone, 

I'm getting this weird error only once in a while - 
Error in method "/cfs/files/:value/:value/:value/", Error: TypeError: Cannot read property 'pdfs' of undefined
    at Object.httpGetHandler (packages/cfs:access-point/access-point-handlers.js:61)
    at Object.accessPoint.get (packages/cfs:access-point/access-point-server.js:175)
    at packages/cfs:http-methods/http.methods.server.api.js:493 

I'm using gridFS to upload some PDFs to a server. The collection file name is 'pdfs' as you can see above.
The file uploads as usual, it even shows up in the collection, but when i access it from the browser, it throws the above issue. 

This happens at random; some files are uploaded and accessible perfectly well. But some are mysteriously throwing this error. If i re-upload the same file, then there's no problem. Which means, there's nothing wrong with the file or the filename. 

Any help/ideas will be greatly appreciated!  Thank you!

**Comment by okpatil4u** [comment]
I am having a similar problem.

Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'original' of undefined
    at Object.httpGetHandler (packages/cfs:access-point/access-point-handlers.js:157:1)
    at Object.accessPoint.get (packages/cfs:access-point/access-point-server.js:175:1)
    at packages/cfs:http-methods/http.methods.server.api.js:575:1

What does one have to do to check if the file has synced properly ?

**Comment by tdhz77** [comment]
My issue was with deployment and something going wrong after deploying with MUP. 
mup stop
mongo [app name]
use Database
db.dropDatabase();

I deleted my mup config. 
Reinitialize with mup init
mup setup
mup deploy

and it worked.
I switched from FS Collection to GridFS which may have caused some error with the db.

**Comment by gregory** [comment]
seems like there is a `uploadedAt` field that you can rely on when it's uploaded, to prevent rendering image before it's being uploaded.
