### ISSUE TITLE
Missing uploaded files

### ISSUE THREAD

**Issue by kenken17** [CollectionFS/Meteor-CollectionFS#431]
Hi, I am having issue on uploading the files to Digital Ocean. I am able to complete the upload process, so far no error logs. But I could not find the image being uploaded at all. Anyone has the same issue?
DB in the mongo, successfully capture the file data.

I am having the path point to process.env.PWD + '/uploads/photos'.

**Comment by digz6666** [comment]
Why it needs 777 permission?

**Comment by flanamacca** [comment]
The bigger issue is why a folder created by your running app is not available to that same running app (ie what users are changing? permissions?)

**Comment by austin4perezident** [comment]
@kenken17 I know that this issue is closed. I am also facing this issue however. Could you elaborate on how you fixed this permission issue?

**Comment by kenken17** [comment]
I set all folders (/uploads) to 777 (recursive). I know that is not a good idea. But i have to move on....
