### ISSUE TITLE
Meteor._wrapAsync

### ISSUE THREAD

**Issue by alearcy** [CollectionFS/Meteor-CollectionFS#435]
Hi! I upgraded Meteor to 0.9.3 version and now on startup I read this error:
Meteor._wrapAsync has been renamed to Meteor.wrapAsync

I've read that Meteor changed this syntax and now developers  must update their packages code.

Thanks!

**Comment by victorbstan** [comment]
Still an issue Meteor._wrapAsync has been renamed to Meteor.wrapAsync

**Comment by rhyslbw** [comment]
Please just subscribe to this issue to be notified of the resolution. As @aldeed has mentioned, the depreciated Meteor._wrapAsync will get updated with other dev changes

**Comment by tacoe** [comment]
Before anyone starts fixing and PR-ing (like I did), that was already done and merged to devel, just waiting for a release to kick off.

**Comment by aldeed** [comment]
Closing since it's fixed in `devel` as @tacoe said.
