### ISSUE TITLE
A way to add an index?

### ISSUE THREAD

**Issue by bradvogel** [CollectionFS/Meteor-CollectionFS#437]
Is there a way to add a db index for metadata on the file object? For example:

```
      var file = new FS.File(file);
      file.myMetaData = ...;
      MyCollection.insert(file);
```

And I'm querying it via:

```
      MyCollection.find({
        myMetaData: ...
      });
```

And I'd like to add an index to that query using `_ensureIndex`, but this doesn't exist:

```
    MyCollection._ensureIndex({
        myMetaData: 1
    }
```

Is there a way to add the index?

**Comment by digz6666** [comment]
How can I access myMetaData from meteor template?
