### ISSUE TITLE
Rewriting images url 

### ISSUE THREAD

**Issue by shtefcs** [CollectionFS/Meteor-CollectionFS#438]
Hi there,

Is there anyway we can rewrite images url instead of example.com/cfs/files/postImages/kubkP8AfHDKbXxJRA/10534575_312955768864706_896283957167497396_n.jpg?token=eyJhdXRoVG9rZW4iOiJMaVFKWW02eWJjU2FCSHNTNzlSU2M3VHJReWdwdjNIZzFHNVFVancyV2Z2In0%3D&store=originalPostImages

to show example.com/i/s65dsd67 or something like that.

Peace,

**Comment by nooitaf** [comment]
closing this, feel free to reopen
