### ISSUE TITLE
How to use Meteor's standard `transform` function

### ISSUE THREAD

**Issue by jagi** [CollectionFS/Meteor-CollectionFS#439]
Hi, I have problem with generating url of thumbnail. I have some files saved in `FS.Collection`. Now when fetching this documents I would like to transform each record and add extra field `thumbnailUrl`. This attribute would have image thumbnail if given file is image or some icon if it's not image. I don't want to store `thumbnailUrl` in collection, so I would need feature like standard `transform` function. But when I use it it breaks FS package.

```js
MyFiles.find({}, {
  transform: function (file) {
    file.thumbnailUrl = 'test';
    return file;
  }
};
```

Return file has `thumbnailUrl` filed but it doesn't have FS functions like `name`, `url` etc. How to deal with this, without changing file objects after fetching. I would like to hook up to the process of object's transformation.

**Comment by zda** [comment]
Would love this feature. Forked to see if I could make it work but haven't yet.
