### ISSUE TITLE
doesn't create collections 

### ISSUE THREAD

**Issue by raniafekry** [CollectionFS/Meteor-CollectionFS#440]
Here is my instant collection ,
StudentFiles = new FS.Collection("studentFiles", {
  stores: [new FS.Store.FileSystem("studentFiles", {path: "~/advising-old/uploads"})]
})
I included it in both client and server .js 
but it doesn't create any collections , so  it doesn't insert any files , what I am doing worng 

Thanks

**Comment by rhyslbw** [comment]
Reopen if you're still having a problem
