### ISSUE TITLE
How to migrate data from collectionFS 0.3.7 to cfs 0.4.x ?

### ISSUE THREAD

**Issue by Rebolon** [CollectionFS/Meteor-CollectionFS#441]
I have an existing app using collectionFS 0.3.7 on a meteor 0.8.3
Now i try to update to meteor 0.9.x and so i have to update collectionFS to 0.4.x
Unfortunately it seems that 0.4 doesn't reuse the collections created by previous version. Even if i set the same name.

Imagine a CollectionFS with 'dataFile' collection name. Under 0.3.7 it will creates 2 mongo collections : 
- dataFile.chunks
- dataFile.files

Then you update to 0.4.x, and modify all required code. Then it won't use the 2 previous collections but it will create following : 
- cfs.dataFile.filerecord
- cfs_gridfs.dataFile.chunks
- cfs_gridfs.dataFile.files

What is the best way to upgrade my dataFile ? Is there any procedure ?

**Comment by jimmiebtlr** [comment]
I'm having trouble understanding how you're getting the file.  As far as I understand 0.3.7 allowed using a get call to a url, but how is the URL calculated?


I'm going through an update of a meteor application from version 0.3.7.
