### ISSUE TITLE
Error: use "new" to construct a Mongo.Collection

### ISSUE THREAD

**Issue by praneybehl** [CollectionFS/Meteor-CollectionFS#450]
I am getting this error:

W20141016-17:36:19.917(11)? (STDERR)
    W20141016-17:36:19.918(11)? (STDERR) /Users/User/.meteor/packages/meteor-tool/.1.0.34.127wjeq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20141016-17:36:19.918(11)? (STDERR)                                            throw(ex);
W20141016-17:36:19.918(11)? (STDERR)                                                  ^
    W20141016-17:36:19.929(11)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20141016-17:36:19.930(11)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:29)
W20141016-17:36:19.930(11)? (STDERR)     at Package (packages/cfs:tempstore/tempStore.js:31)
W20141016-17:36:19.930(11)? (STDERR)     at /Users/User/projects/Meteor/projects/sampii.com/app/.meteor/local/build/programs/server/packages/cfs_tempstore.js:402:4
W20141016-17:36:19.930(11)? (STDERR)     at /Users/User/projects/Meteor/projects/sampii.com/app/.meteor/local/build/programs/server/packages/cfs_tempstore.js:409:3
W20141016-17:36:19.930(11)? (STDERR)     at /Users/User/projects/Meteor/projects/sampii.com/app/.meteor/local/build/programs/server/boot.js:168:10
W20141016-17:36:19.931(11)? (STDERR)     at Array.forEach (native)
W20141016-17:36:19.931(11)? (STDERR)     at Function._.each._.forEach (/Users/User/.meteor/packages/meteor-tool/.1.0.34.127wjeq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141016-17:36:19.931(11)? (STDERR)     at /Users/User/projects/Meteor/projects/sampii.com/app/.meteor/local/build/programs/server/boot.js:82:5
    => Exited with code: 8   

How can this be solved? Looks like it coming for the cfs_tempstore package.

**Comment by radik** [comment]
@praneybehl I have the same error.
Meteor 1.1

**Comment by nooitaf** [comment]
closing this, feel free to reopen
