### ISSUE TITLE
Path to file when deployed on meteor.com not working

### ISSUE THREAD

**Issue by cmeethree** [CollectionFS/Meteor-CollectionFS#452]
Hi I've been looking everywhere for information on how to save images to the file system and then retrieve them and display to the client.

On my local machine it works ok (even though I have to hard code a file path). For example I can set the path to:
stores: [new FS.Store.FileSystem("images", {path: "../../../../../public/upload/img/places"})] 

and then access that image at http://localhost:3000/upload/img/places/images-7wF4JXAkNJB8FEm9a-hero-image-5.jpg

I want to do the same thing when I deploy but it's really not working as I thought.

But when I deploy it doesn't. Here is the path:

stores: [new FS.Store.FileSystem("images", {path: "upload/img/places"})]

But where is this saving? If I go to mydomain.meteor.com/upload/img/places/<filename> it doesn't find the file. I've tried everything and it's killing me.

I know it's saving the image somewhere because if I open image in a new tab I see it actually created a file with a filename. But again have no idea WHERE it's creating it.

Have tried ALL of these and more:

stores: [new FS.Store.FileSystem("images", {path: "../web.browser/app/upload/img/places"})]

stores: [new FS.Store.FileSystem("images", {path: "../../web.browser/app/upload/img/places"})]

stores: [new FS.Store.FileSystem("images", {path: "../app/upload/img/places"})]

**Comment by rdewolff** [comment]
Am having the exact problem but cannot reach the files on the server.
What's the best & cleanest way to do that?

**Comment by cmeethree** [comment]
Did you ever get an answer?

> On Aug 13, 2015, at 12:12 PM, Romain de Wolff <notifications@github.com> wrote:
> 
> Am having the exact problem but cannot reach the files on the server.
> What's the best & cleanest way to do that?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CollectionFS/Meteor-CollectionFS/issues/452#issuecomment-130745466>.
> 

Chaz Mee
Inventor, Storyteller, Strategist.

work: http://chazmee.com/work <http://chazmee.com/work>
linkedin: http://www.linkedin.com/in/chazmee <http://www.linkedin.com/in/chazmee>
medium: https://medium.com/@cmeethree <https://medium.com/@cmeethree>
