### ISSUE TITLE
No uploads from cordova app. CORS from http://meteor.local?

### ISSUE THREAD

**Issue by zhenyasav** [CollectionFS/Meteor-CollectionFS#463]
Just tried cfs from a cordova app on meteor 1.0:

Looks like the mobile client runs from `http://meteor.local` (android, not sure how it's done on iphone) and when inserting images from the client, httpCall PUT to `/cfs/files/..`. ends up not reaching the server.

Tried setting `FS.HTTP.uploadUrl` to something better like `__meteor_runtime_config__.ROOT_URL + FS.HTTP.uploadUrl.slice(1)` and ran into this CORS issue. Sounds like `HTTP.publish` needs to allowOrigin `http://meteor.local` at least? Also, http-methods doesn't seem to have explicit OPTIONS support at the moment? What's the best way to tackle this? Thanks!

**Comment by adamgins** [comment]
@raix I seem to be getting a similar issue with wkview 

```
015-08-02 23:05:51.872 Buzzy[95475:22710162] ERROR: Error: "Queue" network [undefined], errorClass@http://localhost:12344/packages/meteor.js?4dc9757b244a30bdf37a732ac4db4026ce56fb6b:558:24
http://localhost:12344/packages/cfs_upload-http.js?cf37b2941c8cdbfd85cdc3948f57fed4bb429081:379:32
http://localhost:12344/packages/cfs_upload-http.js?cf37b2941c8cdbfd85cdc3948f57fed4bb429081:105:15
http://localhost:12344/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:801:24
onreadystatechange@http://localhost:12344/packages/cfs_upload-http.js?cf37b2941c8cdbfd85cdc3948f57fed4bb429081:164:19
```
https://github.com/CollectionFS/Meteor-CollectionFS/issues/760

Just wondering if this is a similar issue for `http://localhost:12344` instead of `meteor.local`?

I tried adding App.accessRules and browser-policy settings for the localhost domain... but could not seem to get this to work.

Any ideas welcome.

**Comment by Batistleman** [comment]
@adamgins  try adding App.accessRule("blob:*"); to your mobile-config.js

**Comment by projectn00b** [comment]
The upload window doesn't open on my phone at all. Works on desktop. I added the blob to the config but nothing still.
