### ISSUE TITLE
Thumb image not found

### ISSUE THREAD

**Issue by boboci9** [CollectionFS/Meteor-CollectionFS#468]
Hi,
I am using the CollectionFS package to create my profile picture, when I upload a new picture I want to create a small thumb that I can use in the header, but the thumb picture is nowhere to be found.

```js
// server side
Images = new FS.Collection("profilepicture", {
  stores: [new FS.Store.FileSystem("profilepicture"),
  new FS.Store.GridFS("thumbnailprofilepic", {
    transformWrite: function(fileObj, readStream, writeStream) {
      fs = Npm.require('fs');
      if (gm.isAvailable) {
        gm(readStream).resize("10", "10" + '^').stream('PNG').pipe(writeStream);
      } else {
        readStream.pipe(writeStream);
      }
    },
  })],
  filter: {
    allow: {
      contentTypes: ["image/*"]
    }
  }
});

Images.allow({
  insert: function (userId, file) {
      // can only create posts where you are the author
      return file.metadata.userId === userId;
    },
    update: function (userId, file) {
      // can only create posts where you are the author
      return file.metadata.userId === userId;
    },
    remove: function (userId, file) {
      // can only delete your own posts
      return file.metadata.userId === userId;
    },
    download: function (userId, file) {
      // can only delete your own posts
      return file.metadata.userId === userId;
    }
  });

// client side

Template.eltImageUploader.events({
	'click #elt-btn-upload': function(){
		$("#profile-files").click();
	},
	'change #profile-files': function(event, template) {
		var files = event.target.files;
		profileObj = Images.findOne({'metadata.userId':Meteor.user()._id});
		if (files[0] != undefined) {
			var fileObj = new FS.File(files[0]);
			fileObj.metadata = new Object();
			fileObj.metadata.userId = Meteor.user()._id;
			var profileImageId = null;

			if(profileObj != undefined)
			{
				
				profileImageId = profileObj._id;
				Images.remove({_id: profileImageId}, function (err, fileObjDeleted)
				{
					if (err) {
						Alerts.removeSeen();
						Alerts.add("Profile update failed " + err , "danger");
						return;
					}
				});
			}
			Images.insert( fileObj, function (err, fileObjInserted) {
				if (err) {
					Alerts.removeSeen();
					Alerts.add("Profile update failed " + err , "danger");
				}
				else{
					Alerts.removeSeen();
            	//	Alerts.add("Profile update successfully.", "success");
  					//SECOND ISSUE fileObjInserted.url() is not yet calculated only if I stop the script here with the debugger keyword
  					Meteor.users.update({_id:Meteor.user()._id}, 
  						{$set:{
  							"profile.picture":fileObjInserted.url() 
  						}}); 
  				}
  			});

			

			
		};
	}


});
```

Therefore I have two issues:
1) The fileObject gets inserted correctly and I can get the image back next time I load the page and I can display the image but the thumb is nowhere to be found, and the fileObj.url({stores: 'thumbnailprofilepic'}) is returnin the same result as the fileObj.url();
2) I don't have the url only if I stop the execution with a debugger or if I reload the page, how can I get the url after the upload has finished.

Thanks in advance for helping,

**Comment by travisdahl** [comment]
You should be using 

`fileObj.url({store: 'thumbnailprofilepic'}) `

`store` not `stores`

**Comment by boboci9** [comment]
Thank you but console.log(fileObjInserted.url({store: 'thumbnailprofilepic'})); still shows me null
Images.insert( fileObj, function (err, fileObjInserted) {
				if (err) {
					Alerts.removeSeen();
					Alerts.add("Profile update failed " + err , "danger");
				}
				else{
					Alerts.removeSeen();
            		Alerts.add("Profile update successfully.", "success");
  					console.log(fileObjInserted.url({store: 'thumbnailprofilepic'}));
  					// Meteor.users.update({_id:Meteor.user()._id}, 
  					// 	{$set:{
  					// 		"profile.picture":fileObjInserted.url() 
  					// 	}}); 
  				}
  			});

**Comment by aldeed** [comment]
Pass `{brokenIsFine: true}` to `url`. By default it returns `null` until the upload is done. Otherwise wait until upload is complete before you call `url`. See #323

**Comment by harshdeepHD** [comment]
Images = new FS.Collection("files", {
	chunkSize: 1024*1024,
    stores: [
    new FS.Store.FileSystem("thumbs", { 
	
      beforeWrite: function (fileObj) {
		return {
			extension: 'jpg',
			type: 'image/jpg'
		};
	},
	transformWrite: function(fileObj, readStream, writeStream) {
		gm(readStream, fileObj.name()).resize('100', '100').stream().pipe(writeStream);
        }
    }),
    new FS.Store.FileSystem("files"),
  ],
});
thumbnail was create o byte
