### ISSUE TITLE
In AWS, 5Mb above file size throw error

### ISSUE THREAD

**Issue by Maheshwaranravibose** [CollectionFS/Meteor-CollectionFS#481]
In my aws server, I have a file called index.php. it run perfectly when the file size was below 5mb but after some line of code i added it throws error. In the same, i checked in shared server i run perfectly.
what is the problem?

advance thanks

**Comment by tom2strobl** [comment]
On my EC2 instance I had to change the ```nginx.conf``` and add ```client_max_body_size``` in the ```http``` block.

**Comment by aldeed** [comment]
Fixed by CollectionFS/DEPRECATING-cfs-s3#44
