### ISSUE TITLE
Image upload URL using Summernote with CollectionFS

### ISSUE THREAD

**Issue by sangyoo91** [CollectionFS/Meteor-CollectionFS#489]
Hi.

I'm working on a project using Meteor.js, Summernote and Collection FS.

First of, here is my code.

    Template.postSubmit.rendered = function() {
       $('#summernote').summernote({
            height: 400,
            maxHeight:800,
            minHeight:250,
            onImageUpload: function(files, editor, $editable) {
            Images.insert(files[0], function (err, fileObj) {
                editor.insertImage($editable, fileObj.url());    
            });
          }
       });
The image when inserted does successfully go into the specified URL for image storage. Here is the CollectionFS javascript.

    Images = new FS.Collection("images", {
      stores: [new FS.Store.FileSystem("images", {path: "~/img"})]
    });
    
    Images.allow({
      insert: function() {
        return true;
      },
      update: function() {
        return true;
      },
      remove: function() {
        return true;
      },
      download: function() {
        return true;
      }
    });
I was wondering if anyone could guide me in the right direction. I've been told the URL on callback is not defined. So, I've been asked to try this code, using a setTimeout function. However, I've still had no luck.

    onImageUpload: function(files, editor, $editable) {
            Images.insert(files[0], function (err, fileObj) {
              setTimeout(function() {
                editor.insertImage($editable, fileObj.url());
              }, 300)
            });
          }
Has anyone succeeded through using summernote in this manner in Meteor.js and collectionFS?

If so, please help me. If this gets solved, I'll be posting a tutorial for many meteor.js users. I believe it will be a great contribution.

Also, even if you're not using Meteor.js or CollectionFS, if you can pitch in your two cents, it would be greatly appreciated.

Thanks!

**Comment by daslicht** [comment]
@nooitaf  When I try to run your code I get:
```
Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'images' of undefined
    at Object.httpGetHandler (packages/cfs:access-point/access-point-handlers.js:157:1)
    at Object.accessPoint.get (packages/cfs:access-point/access-point-server.js:175:1)
    at packages/cfs:http-methods/http.methods.server.api.js:575:1
```

After inserting the Image I can see the following url logged to the Browser console:

 http://localhost:3000/cfs/files/images/gtwLy5sYQu83uusZS
However it fails when trying to insert the image with the following error:

GET http://localhost:3000/cfs/files/images/gtwLy5sYQu83uusZS 503 (Service Unavailable) 
But I can open the image in a new tab.

I noticed that the type in the network developer panel is shown as : text/plain

Do we need to define the type somehow to make that work ?

**Comment by daslicht** [comment]
I think we have to use Meteor call to invoke the image insert on the server side.
If we do the Insert on the client the insert callback logically dont know when the upload finished.

I tried it like to following:
Server:
```
if(Meteor.isServer){
	Meteor.methods({
		insertImage: function(files) {
			Images.insert(files[0], function (err, fileObj) {
				console.log("after insert:",fileObj._id);
				return fileObj.url();
			});
		}
	});
}
```

on the Client:
```

 onImageUpload: function(files, editor, $editable) {

		    	Meteor.call("insertImage", files, function(err, data){
		    		console.log("Server Retuned:", err, data);
		    	});
```
But now I get the following error:
Exception while invoking method 'insertImage' Error: DataMan constructor received data that it doesn't support

So do we have to prepair the ***files*** before invoking the server-side Method?

**Comment by daslicht** [comment]
Wrong guess, it should be indeed client side:
https://github.com/CollectionFS/Meteor-CollectionFS#using-insert-properly

**Comment by daslicht** [comment]
Here is what works for me:

```
	Template.blogList.rendered = function() {
		var template = this;
		$('#summernote').summernote({
		    height: 400,
		    maxHeight:800,
		    minHeight:250,
		    onImageUpload: function(files, editor, $editable) {

		    	Images.insert(files[0], function (err, fileObj) {
					console.log("after insert:", fileObj._id);
					template.autorun(function (c) {
			          fileObj = Images.findOne(fileObj._id);
			          var url = fileObj.url();
			          if (url) {
			          	$("#summernote").summernote("insertImage", fileObj.url(), "Image Title"); 
			            //editor.insertImage($editable, url);
			            c.stop();
			          }
			        });
				});
		  
		  	}	
		});
	}
```

**Comment by nooitaf** [comment]
closing this, feel free to reopen
