### ISSUE TITLE
No compatible build found for cfs:gridfs@0.0.26

### ISSUE THREAD

**Issue by zhenyasav** [CollectionFS/Meteor-CollectionFS#493]
Is anyone getting this as well? When I do `meteor show cfs:gridfs` i can see a `0.0.26`

**Comment by jegodard** [comment]
Hello, I am evaluating the preview version of meteor on Windows : 0.1.7 and met the same issue 
 meteor add cfs:gridfs => Errors while adding packages

While checking for cfs:gridfs@0.0.27:
error : No compatible build found

This is the only issue I met to make meteoris project run on a windows machine.

Thanks

**Comment by aldeed** [comment]
@jegodard, are there docs somewhere for how to install Meteor preview on Windows? If they are going to officially support Windows now, we should build for it, but `meteor admin get-machine` command does not have a Windows machine available.

**Comment by jegodard** [comment]
Hi, thanks for your answer. Actually, there is an initiative to support windows. A preview version is available on https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

**Comment by aldeed** [comment]
@jegodard, thanks. I posted a question about it [here](https://github.com/meteor/windows-preview/issues/45).

**Comment by ganySA** [comment]
I have had this problem with a number of packages (now Windows 0.3 pre release).

For those that need a solution is simply to download the repository into the packages directory, then manually add the reference to the .meteor/package.conf and meteor should build the package and grab all the npm dependencies for your build.

**Comment by jayohh1237** [comment]
I am having the same issue from above using a MacOS ... what is your suggestion?

**Comment by wollardj** [comment]
Same problem as @jayohh1237 - OS X 10.10.5
```
meteor add cfs:gridfs
 => Errors while adding packages:             
                                      
While checking for cfs:gridfs@0.0.29:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

FWIW, `meteor ad cfs:filesystem` works just fine.

**Comment by msio777** [comment]
Same problem with 0.0.29 like wollardj - OS X 10.10.5

**Comment by lgertel** [comment]
Same here on osx

**Comment by nooitaf** [comment]
Just tested clean install with 10.10.5, no problems.
Did you try 0.0.33 ?

```text
$ meteor create cfstest

Created a new Meteor app in 'cfstest'.     
  
$ cd cfstest

$ meteor add cfs:standard-packages

Changes to your project's package version selections:

cfs:access-point        added, version 0.1.49 
cfs:base-package        added, version 0.0.30
cfs:collection          added, version 0.5.5
cfs:collection-filters  added, version 0.2.4
cfs:data-man            added, version 0.0.6
cfs:file                added, version 0.1.17
cfs:http-methods        added, version 0.0.30
cfs:http-publish        added, version 0.0.13
cfs:power-queue         added, version 0.9.11
cfs:reactive-list       added, version 0.0.9
cfs:reactive-property   added, version 0.0.4
cfs:standard-packages   added, version 0.5.9
cfs:storage-adapter     added, version 0.2.3
cfs:tempstore           added, version 0.1.5
cfs:upload-http         added, version 0.0.20
cfs:worker              added, version 0.1.4
mongo-livedata          added, version 1.0.9
raix:eventemitter       added, version 0.1.3

cfs:standard-packages: Filesystem for Meteor, collectionFS
                                              
$ meteor add cfs:gridfs

Changes to your project's package version selections:
                                              
cfs:gridfs  added, version 0.0.33             
cfs:gridfs: GridFS storage adapter for CollectionFS
                                              
$ meteor

[[[[[ ~/space/cfstest ]]]]]                  

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

**Comment by Artform** [comment]
Starting a new project works for me. The must be a package that is inhibiting the installation for us. Here's my list:
`accounts-facebook                       1.0.6  Login service for Facebook accounts
accounts-password                       1.1.4  Password support for accounts
accounts-twitter                        1.0.6  Login service for Twitter accounts
alanning:roles                          1.2.14  Authorization package for Meteor
aldeed:autoform                         5.8.1  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:autoform-bs-datepicker           1.1.1  Custom bootstrap-datepicker input type for AutoForm
aldeed:collection2                      2.8.0  Automatic validation of insert and update operations on the client and server.
aldeed:geocoder                         0.3.8  Easy geocoding by way of the node-geocoder package
audit-argument-checks                   1.0.4  Try to detect inadequate input sanitization
blaze-html-templates                    1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
cfs:standard-packages                   0.5.3* Filesystem for Meteor, collectionFS
cfs:ui                                  0.1.3  CollectionFS, provides UI helpers
check                                   1.1.0  Check whether a value matches a pattern
dburles:google-maps                     1.1.5  Google Maps Javascript API v3
ejson                                   1.0.7  Extended and Extensible JSON library
fortawesome:fontawesome                 4.5.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
ian:accounts-ui-bootstrap-3             1.2.89  Bootstrap-styled accounts-ui with multi-language support.
insecure                                1.0.4  (For prototyping only) Allow all database writes from the client
iron:router                             1.0.12  Routing specifically designed for Meteor
jeremy:geocomplete                      1.6.5_11  Geocoding and Google Places Autocomplete Plugin
jquery                                  1.11.4  Manipulate the DOM using CSS selectors
kyleking:customizable-bootstrap-stylus  3.6.3  Highly configurable bootstrap-stylus integration.
logging                                 1.0.8  Logging facility.
mdg:geolocation                         1.1.0* Provides reactive geolocation on desktop and mobile.
meteor-base                             1.0.1  Packages that every Meteor app needs
meteortoys:allthings                    2.3.1  Insanely Handy Development Tools
mobile-experience                       1.0.1  Packages for a great mobile user experience
mongo                                   1.1.3  Adaptor for using MongoDB and Minimongo over DDP
mrt:flash-messages                      1.0.1  A package to display flash messages to the user
rajit:bootstrap3-datepicker             1.5.0  Meteor packaging of eternicode/bootstrap-datepicker for Bootstrap 3
random                                  1.0.5  Random number generator and utilities
reload                                  1.1.4  Reload the page while preserving application state.
sacha:spin                              2.3.1  Simple spinner package for Meteor
service-configuration                   1.0.5  Manage the configuration for third-party services
session                                 1.1.1  Session variable
spacebars                               1.0.7  Handlebars-like template language for Meteor
standard-minifiers                      1.0.2  Standard minifiers used with Meteor apps by default.
stolinski:stylus-multi                  1.4.3  Stylus, w/ Nib, Rupture, Axis and PostCSS with Lost & Rucksack
tracker                                 1.0.9  Dependency tracker to allow reactive callbacks
yogiben:autoform-file                   0.4.2* File upload for AutoForm
yogiben:autoform-map                    0.2.0  Edit location coordinates with autoForm
`

**Comment by Artform** [comment]
Removing _all_ packages and adding CFS items first helped. I was then able to update several packages to their latest versions without a problem.
