### ISSUE TITLE
image manipulation not working

### ISSUE THREAD

**Issue by dasmodel** [CollectionFS/Meteor-CollectionFS#497]
I have an SVG blob which I'm uploading to an FS.Collection and would like to convert to other formats using `transformWrite`. Each time I try to convert my svg to a different format (doesn't matter which one) it uploads an empty Zero byte file. I tried logging the server error and I found the following:
`gm convert: Improper image header (/var/folders/vp/663j98ps5r15kkrbd774ws8r0000gn/T/gmdIu24b).`

Any idea what could be causing this issue and how I can fix it?
thanks

**Comment by victorbstan** [comment]
I have the same issue with any image file. I don't see any errors logged, but GM does not generate thumbnails.

**Comment by nooitaf** [comment]
closing this, feel free to reopen
