### ISSUE TITLE
Image upload orientation

### ISSUE THREAD

**Issue by ccorcos** [CollectionFS/Meteor-CollectionFS#504]
I'm having this issue where if I upload an image from my iPhone by taking a picture (a portrait picture), then when it gets upload, it displays sideways. Apparently this is an issue with the fact that the image contains metadata about the orientation of the image. 

Apparently there is a way of [accounting for this](http://stackoverflow.com/questions/9353629/images-turning-sideways-upside-down-after-being-uploaded-via-phonegap-ios), but I'm not sure if this is something CollectionFS may be capable of.

**Comment by copleykj** [comment]
You can correct this by adding a write transform to your storage adapter
and using graphicsmagick's autoOrient option.

transformWrite: function(fileObj, readStream, writeStream) {
    gm(readStream, fileObj.name).autoOrient().stream().pipe(writeStream);
}

**Comment by ccorcos** [comment]
Interesting. I found a javsascript solution and made a package:

https://github.com/ccorcos/meteor-clientside-image-manipulation

**Comment by raix** [comment]
The cloudfs packages plays around with client side gm
