### ISSUE TITLE
Need Help with Setup

### ISSUE THREAD

**Issue by b14ckkn19ht** [CollectionFS/Meteor-CollectionFS#507]
Hi i have tried to setup CollectionFS with my little test project for several hours now and having serious issues.

First the documentation on the homepage and here differs in many ways, which I think should be marked on the homepage (maybe it is and I oversaw, but it should be the first sentence refering to this github).

I installed:
cfs:standard-packages
cfs:filesystem
cfs:ui

Next I am having a collection called rooms which stores a room with a name, for a user:

``` rooms.js
Rooms = new Mongo.Collection("rooms");

var imageStore = new FS.Store.FileSystem("roomImageStore", {
    path: "upload", //optional, default is "/cfs/files" path within app container
    maxTries: 5 //optional, default 5
});

RoomFS = new FS.Collection('roomImages', {
    stores: [imageStore],
    filter: {
        allow: {
            contentTypes: ['image/*']
        }
    }
});

RoomFS.allow({
    insert: function () {
        return true;
    },
    update: function () {
        return true;
    },
    remove: function () {
        return true;
    },
    download: function () {
        return true;
    }
});
```
Inserting a room functions well (I have taken it from the microscope example). Each room has a number of images. I first tried to give the FS.Collection the same name of the room, in respect to the websites documentation which says, the FS.Collection then will extend the rooms collection, which came out as wrong.

I also tried making RoomFS a local var but this also made problems like insert couldn't find the collection etc.

My publications.js
```
Meteor.publish('rooms', function() {
    return Rooms.find();
});

Meteor.publish('singleRoom', function(id) {
    check(id, String);
    return Rooms.find(id);
});

Meteor.publish('roomImages', function(roomId){
    check(roomId, String);
    return RoomFS.find({roomId: roomId});
});
```

I have a room_edit.html page where the user would be able to upload his pictures:
```
<template name="roomEdit">
    <form class="main form">
        <input name="files" type="file" class="fileUploader" multiple>
        {{#each images}}
            {{#unless this.isUploaded}}
                {{> FS.UploadProgressBar bootstrap=true}}
            {{/unless}}
        {{/each}}
</form>
</template>
```
I took the function off the documentation in the readme here: 
```
Template.roomEdit.events({
    'change .fileUploader': function (event, template) {
        FS.Utility.eachFile(event, function(file) {
            RoomFS.insert(file, function (err, fileObj) {
                //Inserted new doc with ID fileObj._id, and kicked off the data upload using HTTP
            });
        });
    });
```
Now in my collections there are
cfs._tempstore.chunks
cfs.roomImages.filerecord

after trying to upload one image (the progress bar is not showing) cfs.roomImages.filerecord has the file as collection item, but the uploads folder keeps being empty, therefore I think the file is not uploaded, also if I don't give a path, the default folder is not generated. What am I doing wrong?

Also I tried to give the file a roomid via a function i found on the website

```
Template.roomEdit.events({
    'change .fileUploader': function (event, template) {
        FS.Utility.eachFile(event, function(file) {
            RoomFS.insert(file, {roomId: this._roomid});
        });
    });
```
But this also doesn't work like expected - no roomid is added to the file in collection. Therefore the next i will try to do is giving my room an array of picture-references.

**Comment by mxab** [comment]
Instead of ```` RoomFS.insert(file, {roomId: this._roomid});````
try
````
var fileObj = new FS.File(file)
fileObj.roomId = theRoomId
RoomFS.insert(fileObj)
````

also since i don't see any bind statement I guess this._roomid would be undefined

**Comment by rhyslbw** [comment]
I'm going to close this due to the lack of response
