### ISSUE TITLE
How to zip an image

### ISSUE THREAD

**Issue by ccorcos** [CollectionFS/Meteor-CollectionFS#511]
I'm trying to download a zip including the images using this package:

https://atmospherejs.com/udondan/jszip

I can't seem to find any way to get the image data. Any thoughts?

**Comment by ccorcos** [comment]
OK. So I've been messing around with `meteor shell` and I think this is the right direction:

`r = Receipts.findOne().createReadStream()`

Now I just need some way of getting the binary data so I can write it with JSZip.

```
zip.file('folder/image.jpg', binaryContent);
zip.file('folder/document.pdf', binaryContentBase64Encoded, {base64: true});
```

I was looking around and saw `r.once` is probably what I'm looking for, but I'm not sure what event to listen to. Is this documented somewhere or is there some convention with streams that I don't know about?

Thanks

**Comment by aldeed** [comment]
You could potentially use the data-man pkg to convert to binary, but it's always better for memory if you keep everything a stream. You could try using [zip-stream](https://www.npmjs.com/package/zip-stream) instead, which appears to take a read stream as data.

**Comment by ccorcos** [comment]
How do I get the dataman object from CollectionFS?

**Comment by ccorcos** [comment]
Hey man, sorry to bug you, but I've been unable to figure out how to get the DataMan object from my CollectionFS fileObj.

**Comment by raix** [comment]
You could use streams in transform read/write

**Comment by ccorcos** [comment]
Ok, so on the server...

`img = Images.findOne()`

How do I get the image data from `img`?

**Comment by nooitaf** [comment]
This looks like it gives you a readstream..
https://github.com/CollectionFS/Meteor-cfs-file/blob/master/api.md#fsfilecreatereadstreamstorenameserver

**Comment by raix** [comment]
The transform read/write gives you:
```js
var zlib = require('zlib');
var gzip = zlib.createGzip();
// ...
transformRead: function(fileObj, readStream, writeStream) {
  // Unzip from store
  readStream.pipe(gzip).pipe(writeStream);
},
transformWrite: function(fileObj, readStream, writeStream) {
  // Zip to store
  readStream.pipe(gzip).pipe(writeStream);
}
```

**Comment by nooitaf** [comment]
If i understood correctly, he's trying to combine multiple files in one zip.

**Comment by raix** [comment]
You can be explicit about it too:
```js
var zlib = require('zlib');
// ...
transformRead: function(fileObj, readStream, writeStream) {
  // Unzip from store
  readStream.pipe(zlib.createInflate()).pipe(writeStream);
},
transformWrite: function(fileObj, readStream, writeStream) {
  // Zip to store
  readStream.pipe(zlib.createGunzip()).pipe(writeStream);
}
```

**Comment by raix** [comment]
Ok, in that case you have to write some logic creating the joined stream when all files are ready or updated. I havent checked npmjs out - but the should be some archive packages allowing one to insert file entries and use streaming.

```js
var readStream = Images.findOne().createReadStream(/* optional store name*/);
```

**Comment by nooitaf** [comment]
As @aldeed mentioned, [zip-stream](https://www.npmjs.com/package/zip-stream) works with streams. I even played with it a little, but failed to get a decent logic done if there are multiple files. If you staticly know its going to be 2 or 3 its fine, like in the npm example, but more files ask for some more cb stream logics.

**Comment by raix** [comment]
zip-stream looks ok - one could add some sync api to that making things easier to work with

**Comment by ccorcos** [comment]
Ok. Finally figured it out. Using meteorhacks:async package, I've used this:

```
@getReceiptData = (receiptId) ->

  something = Async.runSync (done) ->
    img = ''
    Receipts.findOne(receiptId).createReadStream().on 'data', (data) ->
        img += data.toString('base64')
      .on 'end', () -> 
        done(null, img)
  return something.result
```
