### ISSUE TITLE
on EC2: error: Forever detected script exited with code: 8 - related to cfs:filesystem

### ISSUE THREAD

**Issue by tintoverano** [CollectionFS/Meteor-CollectionFS#519]
hello guys,

after successful mup  to an ec2 instance the mup log tells:

````
at new FS.Store.FileSystem (packages/cfs:filesystem/filesystem.server.js:29:1)
    at app/labident.js:8:12
    at app/labident.js:540:3
    at /opt/labident/app/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/labident/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/labident/app/programs/server/boot.js:116:5
error: Forever detected script exited with code: 8
````

any ideas what is wrong?

thanks a lot

tinto

**Comment by nooitaf** [comment]
https://github.com/CollectionFS/Meteor-cfs-filesystem/blob/master/filesystem.server.js#L29
````javascript
throw new Error('FS.Store.FileSystem unable to resolve "~" in path');
````

Should have thrown an error too.

**Comment by tintoverano** [comment]
hi,

I had that one earlier and it threw the error:

````
Error: FS.Store.FileSystem unable to resolve "~" in path
````

I fixed it, did a new mup and got the forever detected error.

I guess I repeat mup again

cheers,

tinto

**Comment by nooitaf** [comment]
I might suggest using a full path like this 
`/opt/cfs/images/original`
and then log into the server and give `meteoruser` access to write to the folder with 
`sudo chmod -R 775 /opt/cfs/images/`
because the collection folders get created by `root`, but the app is running as `meteoruser` so if it tries to write it will fail. If you use a relative path like `./uploads` it will be overwritten as soon as you deploy again iirc.

**Comment by tintoverano** [comment]
thanks @nooitaf 

I'll try and get back with the update on this

tinto

**Comment by tintoverano** [comment]
thanks @nooitaf 

I'll try and get back with the results here

tinto

**Comment by tintoverano** [comment]
hello,

I  made the changes as you suggested, local version works fine, but I'm still not able to test the app

first I had to fix an issue with locale (http://askubuntu.com/questions/536875/error-in-installing-mongo-in-virtual-machine), because mongo was not runnig

now I have mongo running fine, tested on remote

I get this npm error, so far I couldn't find any working solution

````
at [object Object].<anonymous> (/opt/labident/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/opt/labident/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/opt/labident/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
````

do you have any idea?

thanks again,

tinto

**Comment by nooitaf** [comment]
quick reply: 
isnt mup installing mongodb for you?
you can also to `FS.debug = true` to see more stuff about collectionFS.

**Comment by tintoverano** [comment]
yes, mup installed mongodb, but I got that error after with locale

I'll try turning on debugging...

thanks

**Comment by tintoverano** [comment]
I've checked the app log after reboot at /var/log/upstart/ and I still get the "~" related error, so it seems mup update didn't work as expected

I'll try to manually remove the app and use mup again

**Comment by tintoverano** [comment]
delete remote app folder reinstall server and app did the trick

thanks for the support!

**Comment by ryparty** [comment]
@nooitaf your suggestion to chmod that shit was awesome, saved me at least an hour. i basically just logged into my server and mkdir'd /opt/cfs and then /opt/cfs/uploads, chmodded that with the command you gave, which obviously with the recursive flag allowed me to change the FS.Store.FileSystem path in my local project to /opt/cfs/uploads/images (i'm anticipating wanting a different 'videos' folder in uploads in the future, else you could nix the '/images' part) and mup deploy voila.

i'm obviously not writing this process for the benefit of @nooitaf but rather if someone else comes across it and wants the process that worked for me on my digital ocean server. thanks again you rock!
