### ISSUE TITLE
Hack collection .allow?

### ISSUE THREAD

**Issue by comerc** [CollectionFS/Meteor-CollectionFS#522]
hacker may change the metadata.userId to access the photos:
```coffee
Photos.allow
  update: (userId, file, fieldNames, modifier) ->
    userId and file.metadata?.userId is userId
```

or I do not understand... 😎

**Comment by nooitaf** [comment]
The first `userId` comes from the server and cant be changed clientside. The `file.metadata.userId` can be changed cient-side at insert-time, but if a "hacker" might change that to, lets say, the admins user-id he wont be able to update or remove it if you do the checking you did in the `update`, `remove` or `download` method.
`````javascript
if (userId && fileObj.owner && fileObj.owner === userId) {
  return true;
} else {
  return false;
}
`````

**Comment by aldeed** [comment]
This doesn't seem like a CFS question. It works the same as with normal Meteor collections.
