### ISSUE TITLE
Anyone looked into EXIF parsing?

### ISSUE THREAD

**Issue by rhyslbw** [CollectionFS/Meteor-CollectionFS#525]
I'm going to look into parsing EXIF from image files to primarily store some key data as fields in the FS.File doc. There are a number of npm packages that will probably do the trick, but I'm keen to know if anyone has done some research or has any specific packages to refer.

**Comment by bensmeets** [comment]
Have tried some, but settled on using this https://github.com/blueimp/JavaScript-Load-Image since I only needed it for client side resizing and such (needs the orientation).
