### ISSUE TITLE
Define helpers on the CollectionFS

### ISSUE THREAD

**Issue by rhyslbw** [CollectionFS/Meteor-CollectionFS#526]
I'm really missing the ability to define helpers on CollectionFS collections using dburles:collection-helpers. I'll do some investigation into what options there are to pass in custom definitions for the CollectionFS transform to run, but if anyone else has made a start let me know.

**Comment by aldeed** [comment]
Since CFS already applies a transform, it would not be a good idea to use collection helpers. You should be able to do pretty much the same thing by extending the `FS.File` prototype with your own functions, though.

**Comment by rhyslbw** [comment]
Ta, probably just easier to do that than look at ways to unify the api. I'll close this ticket for now
