### ISSUE TITLE
Image Collection 'resets' when meteor deploy is used

### ISSUE THREAD

**Issue by platelet** [CollectionFS/Meteor-CollectionFS#529]
I use image uploading on my app, and it works fine on my local version. Upload, restart server, and its still there.

When I deploy, I can upload an image and view it, but if I deploy again the old uploads can be viewed. They are still in the collection, but the url associated to them returns a 503 error.

**Comment by nooitaf** [comment]
You could use the GridFS storage. It saves the files in your mongodb which should be persistend on 'meteor deploy'.

**Comment by platelet** [comment]
So the upload directory for cfs:filesystem is overridden with 'meteor deploy'?

**Comment by nooitaf** [comment]
Yes, the complete appfolder gets overwritten with your new deploy. As you cant access the filesystem on meteor.com anyway, there should not be any difference for you using the [GridFS Storage adapter](https://github.com/CollectionFS/Meteor-cfs-gridfs). 

Also everthing is optional, so you could just do something like this: 
`````shell
meteor add cfs:gridfs
`````
`````javascript
var imageStore = new FS.Store.GridFS("images");

Images = new FS.Collection("images", {
  stores: [imageStore]
});
`````

**Comment by platelet** [comment]
Cheers for the help

**Comment by rhyslbw** [comment]
… but the meteor.com platform isn't intended for anything permanent. Try Modulus or Meteor Up with a Digital Ocean box
