### ISSUE TITLE
Disable automatic updating of existing file records when new stores are introduced

### ISSUE THREAD

**Issue by szimmer1** [CollectionFS/Meteor-CollectionFS#536]
We have some legacy files and recently started using a few more S3 stores. We noticed that for these files, the new store code writes new 0 byte copies to the database in cfs.filestore and then writes 0 byte files to S3, in some cases overwriting our old S3 files with 0 byte files. 

We backed up our S3 before the migration :) But is there any way to prevent cfs creating 0 byte copies for old file records whenever new stores are introduced?

**Comment by rhyslbw** [comment]
This will most likely be addressed in the changes to the worker in https://github.com/CollectionFS/Meteor-CollectionFS/issues/536
