### ISSUE TITLE
Meteor CollectionFS Developers Hangout

### ISSUE THREAD

**Issue by raix** [CollectionFS/Meteor-CollectionFS#539]
Hi all,

We want to invite all interested to a hangout next week wed the 18th feb 2015, at CET 23.00 - a "Developers talk about CollectionFS"

Current agenda:
* Welcome
* How we can make it easier to contribute to cfs
* Status / where we are heading at
* Next hangout?

Both Eric (@aldeed) and I (@raix) will be there, focus is about getting cfs development up in gear so we all can start to using it in production.

If you want to be part of the hangout please reach out to @raix at mh(at)gi2.dk on google plus or mail - I'll add you.

Trello: https://trello.com/b/iFsuP745/meteor-collectionfs (WIP overview of the project)

cc. *(in alphabetic order)*
@aaronjudd, @abditus113, @almogdesign, @comerc, @copleykj, @cramhead, @czeslaaw, @dandv, @DanielDornhardt, @dmitriyles, @DouglasUrner, @elbowz, @emgee3, @eprochasson, @flanamacca, @floo51, @gerwinbrunner, @GuillaumeZuff, @hitchcott, @isaaki, @jchristman, @karabijavad, @kevohagan, @lleonard188, @lukasvan3l, @maomorales, @matthewsimo, @mikeschaekermann, @mitar, @mxab, @nhibner, @nooitaf, @petrocket, @rhyslbw, @Sanjo, @tanis2000, @theduke, @timLoewel, @trymbill, @vsivsi, @wearhere, @wursttheke, @yogiben, @zda, @zhenyasav

You guys have all contributed to cfs, a big thanks!

I'm also adding you here since you of all might have some input on how we can do better - If for some reason your not mentioned please poke me and I'll correct it :)

If you read this issue and have been close to contributing, please give some feedback on how we can make it easier/safer etc. we would value your input.

Kind regards Morten

**Comment by nooitaf** [comment]
\o/

**Comment by raix** [comment]
missed a `f` :)

**Comment by DanielDornhardt** [comment]
Cool, thanks, will see if I can make it!

Daniel Dornhardt, Daniel Dornhardt Development
daniel@dornhardt.com
+49 152 - 56 17 22 61

**Comment by hitchcott** [comment]
I would like to make it but unfortunately the timing is pretty bad for Hong Kong. 

Will you be able to record the audio?

**Comment by eprochasson** [comment]
OMG, another developer in Hong Kong on the same thread (the other being me). What are the odds. That calls for some beers/local gathering!

**Comment by raix** [comment]
Sorry about the timing - I planned it really late in my timezone hoping more devs could attend

I'll see if we can record or something (honestly it's the first hangout I'm hosting and I haven't read up on the basics yet - so let me know if we can do something clever)

**Comment by hitchcott** [comment]
No worries @raix -- it's a good time to pick because there's likely to be devs in the US. I've never used hangouts but there might be an option to upload it to youtube or something?

@eprochasson -- yes, there are more than one us! You should check out the Meetup page :smile:

**Comment by nooitaf** [comment]
Damn i missed it. I could eat my foot. harr

**Comment by raix** [comment]
We missed you @nooitaf :)

We have created a hackpad at https://meteorcfs.hackpad.com everyone is welcome to give input,
I'm starting the first phase of merging some core packages into one main repo - we loose the finer-grained team control - but hopefully we get a more easy maintainable package cluster.

We also have a trello board at https://trello.com/b/iFsuP745/meteor-collectionfs - comment/vote etc. we'll try to keep this updated too.

-

I hope we have a new hangout once we get a bit more settled, this could be on air. We will have problems reaching globally, but we'll try to be flexible :)

**Comment by theduke** [comment]
Do you guys hang out in the IRC #meteor channel on freenode?

**Comment by raix** [comment]
Gitter badge added

**Comment by raix** [comment]
I'm closing this - We are on gitter/trello/github and hopefully we'll have a hangout not to far away in the future.

I've merged core packages into the main repo and added issues with things still needing to be done.

I hope you will find 5 min to check out trello, issues and the devel branch,

Kind regards Morten

**Comment by aaronjudd** [comment]
@raix did you setup a gitter room, or was that my imagination?

**Comment by raix** [comment]
It's linked in the packages/standard-packages readme - we should prop. merge parts of that read me to the main readme

**Comment by raix** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/tree/devel/packages/standard-packages
