### ISSUE TITLE
createReadStream works locally but crashes app in meteor deploy

### ISSUE THREAD

**Issue by cfsamson** [CollectionFS/Meteor-CollectionFS#546]
I have struggeled with this, and cannot find the base of the problem here. When retrieveing a file stored with GridFS in Mongodb, and then creating a read stream to pipe it to the response, the app crashes in meteors own hosting service at meteor.com.

The line that seems to cause the crash is: 

    file.createReadStream();

The log looks like this:

Tue Feb 17 2015 22:26:17 GMT+0000 (UTC)] WARNING Error:
54e3c00906619b00002a1cbe does not exist
at
/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:216:26
at
/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:738:35
at Cursor.close
(/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:959:5)
at Cursor.nextObject
(/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:738:17)
at commandHandler
(/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/cursor.js:713:14)
at
/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/db.js:1806:9
at Server.Base._callHandler
(/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
at
/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
at [object Object].MongoReply.parseBody
(/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
at [object Object].<anonymous>
(/meteor/containers/5934181d-eda4-3f1c-611f-4f5d5f183eda/bundle/programs/server/npm/cfs:gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
[Tue Feb 17 2015 22:26:17 GMT+0000 (UTC)] INFO STATUS running -> starting
[Tue Feb 17 2015 22:26:17 GMT+0000 (UTC)] NOTICE Starting application on port
21877
[Tue Feb 17 2015 22:26:17 GMT+0000 (UTC)] ERROR Application crashed with code:
8
[Tue Feb 17 2015 22:26:17 GMT+0000 (UTC)] INFO STATUS starting -> running
[Tue Feb 17 2015 22:26:18 GMT+0000 (UTC)] INFO Meteor._wrapAsync has been
renamed to Meteor.wrapAsync

**Comment by aldeed** [comment]
Be sure the file is done being saved to the store before calling it. You could listen for "stored" event.

**Comment by cfsamson** [comment]
The file is stored in gridfs already if thats what you think about. This happens to files that i uploaded yesterday even, and only on meteor deploy not locally.

I assume collectionfs streams it right from mongodb and does not use some kind of disk temporary storage (which could explain why it works locally but not on meteor deploy due to file system access issues - but i just rule this out as an option since it doesn't make sense that a stream should do that).

I'll paste more of the code here so you'll se the whole segment.


Router.route('/files/:_id', function () {
    var self = this;
    var file = AppFileupload.Files.findOne(this.params._id);

    // this is where it crashes, tried to remove everything else and it does not crash
    var stream = file.createReadStream('files');
    
    this.response.writeHeader(200, {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Header': 'Origin, X-Requested-With, Content-Type, Accept',
        'Content-Type': file.original.type,
        'Content-Length': file.original.size,
        'Content-Disposition': 'attachment; filename=' + file.copies.files.name
    });
    
    stream.pipe(this.response);

}, {name: 'getFile', where: 'server'});

This works locally on all browsers, but fails on meteor deploy.

**Comment by cfsamson** [comment]
On the other hand, thinking about it, there might be an issue when saving the file as you mention and not the download itself. This working locally might actually be because the file is uploaded much much faster, and somehow the upload failes and/or is not finished when uploading remotely and the problem might be an unfinished upload.

This problem seems to only happen to large files (> 4mb), so that makes sense.  I'll investigate and get back to this.

**Comment by cfsamson** [comment]
Ok, so I got this working. Aldeed was right that it was the upload that hadn't finished and there was no problem with the download.

I tried listening to the "stored" event, but this seems to be a server side event and I need to prevent the client from closing or navigate away before the upload has finised. After quite a bit of checking around, I found that there is a client side event, and that I can use it like this:

    Files.insert(fileToUpload, function (err, fileObj) {
    // You can display a spinner/progress or message to the user that file is uploading here

        fileObj.once('uploaded', function () {
        // This event fires when the file is uploaded. You can disable spinner/progress and do the actions you
        // want to do after the file has uplodaded here
        }
    }

**Comment by vuhpham** [comment]
@cfsamson Is that client side event is the same with isUploaded here: https://github.com/CollectionFS/Meteor-CollectionFS#isuploaded
