### ISSUE TITLE
Are there any plans to implement Azure Storage or cloudinary?

### ISSUE THREAD

**Issue by alexzaporozhets** [CollectionFS/Meteor-CollectionFS#547]
http://azure.microsoft.com/en-us/services/storage/
http://cloudinary.com/

**Comment by raix** [comment]
Its possible, we have a ton of work still - but its the general idea that you should be able to connect to any service using a storage-adapter for it.

**Comment by rhyslbw** [comment]
Closing as the question has been answered.
