### ISSUE TITLE
Add new README.md

### ISSUE THREAD

**Issue by raix** [CollectionFS/Meteor-CollectionFS#556]
At the moment the readme is pretty black on the devel branch. We need to have a short version / teaser on the front to introduce the project and to guide the visitor into the docs folder etc.

There could be some inspiration in the `packages/standard-packages`

**Comment by stewartmccoy** [comment]
+1

**Comment by kodamirmo** [comment]
+1

**Comment by tagrudev** [comment]
+1

**Comment by wursttheke** [comment]
Documentation is back online. With examples and how-tos in the [wiki](https://github.com/CollectionFS/Meteor-CollectionFS/wiki).

**Comment by raix** [comment]
Great work!
