### ISSUE TITLE
Add support for audit-argument-checks package

### ISSUE THREAD

**Issue by aldeed** [CollectionFS/Meteor-CollectionFS#560]
*Original post by @pburke in cfs:file repo:*

The audit-argument-checks package is used to enforce validating data submitted from the client. It seems to be an emerging best practice among Meteor developers. 

With the autit-argument-checks package installed, when I try to upload a file from the client by passing a URL, I get the following error:

```
Exception while invoking method '_cfs_getUrlInfo' Error: Did not check() all arguments during call to '_cfs_getUrlInfo'
```

Removing the package solves the problem, but it would be nice if that were not necessary.

**Comment by rhyslbw** [comment]
Completed in https://github.com/CollectionFS/Meteor-CollectionFS/pull/627

**Comment by stevenova** [comment]
I don't know if you should reopen this issue. I'm still having issue when uploading image from client, getting the same error, but on 
> Exception while invoking method '/cfs.images.filerecord/insert' Error: Did not check() all arguments during call to '/cfs.images.filerecord/insert'

Don't know if it is related.
