### ISSUE TITLE
does meteor.com delete my files?

### ISSUE THREAD

**Issue by giggioz** [CollectionFS/Meteor-CollectionFS#561]
My app stores in the filesystem some images, locally it works fine.

When i deploy the app on myapp.meteor.com and i upload an image i have the following behaviour :

* i see the uploaded image in my app - everything is fine
* after an unpredictable amount of time (usually hours) if i go to check this image on my app i discover that the image is not present anymore

From chrome (console tab) i see : 

GET http://MYAPP.meteor.com/cfs/files/attachments/JwpSAEwqeKLmCoSxQ/zzz.jpg?t…NaTkdBQ01RUnJLOXVDZlVJUUtCS0dCaVMyYmFhY1htVGxhVXY5In0%3D&store=attachments 503 (Service Unavailable)

 GET http://MYAPP.meteor.com/cfs/files/attachments/JwpSAEwqeKLmCoSxQ/zzz.jpg?t…NaTkdBQ01RUnJLOXVDZlVJUUtCS0dCaVMyYmFhY1htVGxhVXY5In0%3D&store=attachments net::ERR_CONTENT_LENGTH_MISMATCH

* other recent images uploaded in the same view WORK!

I also compared the headers of the two network requests (image ok and image not ok) and they are the same.

Any comment will be really appreciated, thanks!

**Comment by nooitaf** [comment]
Yes, you also lose all files on redeploy. 

The only thing persistent is the MongoDB, so you could use the [GridFS Storage Adapter](https://github.com/CollectionFS/DEPRECATING-cfs-gridfs/tree/master/packages/gridfs).

`````text
meteor add cfs:gridfs
`````

`````javascript
var imageStore = new FS.Store.GridFS("images");
Images = new FS.Collection("images", {
  stores: [imageStore]
});
`````

**Comment by giggioz** [comment]
I looked for this information through a lot of pages... and i did not find it, thank you a lot!

I think it would be extremely helpful to underline this somewhere (maybe in the docs of cfs:filesystem?)
