### ISSUE TITLE
Package update broken for 0.0.28

### ISSUE THREAD

**Issue by tekknikk** [CollectionFS/Meteor-CollectionFS#568]
$ meteor update
This project is already at Meteor 1.0.3.2, the latest release.
=> Errors while upgrading packages:

While checking for cfs:gridfs@0.0.28:
error: No compatible build found

**Comment by PEM--** [comment]
Ouch! Me too :worried:

**Comment by raix** [comment]
what os?

**Comment by PEM--** [comment]
OSX

**Comment by PEM--** [comment]
@tekknikk, In the mean time, you can force specifying the package number like so:
```bash
meteor add cfs:gridfs@=0.0.27
```

**Comment by PEM--** [comment]
@raix, I think this is the issue:
https://github.com/CollectionFS/Meteor-CollectionFS/blob/devel/packages/gridfs/package.js#L5

**Comment by PEM--** [comment]
@raix: PR: #570

BTW, I got a failed build on Travis. Seems like `rake` is not imported properly.

**Comment by raix** [comment]
not sure @PEM--  it's an optional field - I'm thinking if... rake?? investigating...

**Comment by aldeed** [comment]
Oh, this is my fault. I was trying to build for the Windows preview, but apparently there are some bugs with that process that they're still figuring out. I can build for the other architectures tomorrow, but just pin to 0.0.27 for now.

**Comment by tekknikk** [comment]
@aldeed ahhh understand re builds.  I wondered as I saw that comment in my search before posting.

**Comment by aldeed** [comment]
There should be a working 0.0.29 now.

**Comment by antalakas** [comment]
Just received the same message with 0.0.29

updated to Meteor 1.0.3.2.
=> Errors while upgrading packages:

While checking for cfs:gridfs@0.0.29:
error: No compatible build found
