### ISSUE TITLE
CollectionFS suitable for production?

### ISSUE THREAD

**Issue by brylie** [CollectionFS/Meteor-CollectionFS#574]
As of 2014-3-31, the filesystem component was described as [not suitable for production](https://github.com/CollectionFS/Meteor-CollectionFS/blob/devel/packages/filesystem/README.md). Is this still the case?

We are building a beta app and are considering whether CollectionFS is suitable for our project going forward.

**Comment by wursttheke** [comment]
@brylie Let me answer again. :)

There's a current effort to get this project production ready. Read the discussion about it here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/534

**Comment by brylie** [comment]
Again, thanks @wursttheke :-)
