### ISSUE TITLE
cfs:gridfs - 0.29 breaks this.url access

### ISSUE THREAD

**Issue by deanmckee** [CollectionFS/Meteor-CollectionFS#575]
I upgraded cfs:gridfs from 0.27 to 0.29 this morning and my application now has broken images with HTTP 503 errors with existing image files in GRIDFS (I'm displaying them using img tags with src={{this.url}}).  If I downgrade back to 0.27 everything works fine again.

**Comment by aldeed** [comment]
afaik, no code changed between 0.27 and 0.29. Only the version number changed because we're trying to figure out some publishing issues. @raix any ideas here? Maybe a dependency issue?

**Comment by Ethaan** [comment]
Im Getting this error when creating a new project.
```javascript
mini-de-ethan:padonde Ethaan$ meteor add cfs:gridfs
 => Errors while adding packages:             
                                              
While checking for cfs:gridfs@0.0.29:
error: No compatible build found
```

**Comment by aldeed** [comment]
What OS? I did `publish-for-arch` for all types and it seemed to work.

**Comment by Ethaan** [comment]
```javascript
$ sw_vers -productVersion
10.9.2
```

**Comment by Ethaan** [comment]
@aldeed on the `0.29 gridFs {{this.url}}` stop working for me.

**Comment by raix** [comment]
odd - I'll do a check

**Comment by willemx** [comment]
Same problem here:

    kantoor:youtopx willem$ meteor add cfs:gridfs
     => Errors while adding packages:             
                                              
    While checking for cfs:gridfs@0.0.29:
    error: No compatible build found

    kantoor:youtopx willem$ sw_vers -productVersion
    10.10.2

**Comment by fishdude** [comment]
Experiencing the same issue running on osx 10.10.3. I've tried pinning to both 0.0.29 and 0.0.27 with no luck. Works fine for me on linux though.

```
fishBook:gridfsTest fish$ meteor add cfs:gridfs
 => Errors while adding packages:             
                                              
While checking for cfs:gridfs@0.0.29:
error: No compatible build found

fishBook:gridfsTest fish$ meteor add cfs:gridfs@0.0.29
 => Errors while adding packages:             
                                              
While checking for cfs:gridfs@0.0.29:
error: No compatible build found

fishBook:gridfsTest fish$ meteor add cfs:gridfs@0.0.27
 => Errors while adding packages:             
                                              
While checking for cfs:gridfs@0.0.29:
error: No compatible build found

fishBook:gridfsTest fish$ sw_vers -productVersion
10.10.3

```

**Comment by rhyslbw** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/issues/581
