### ISSUE TITLE
How to use cfs:gridfs?

### ISSUE THREAD

**Issue by guitchicken** [CollectionFS/Meteor-CollectionFS#576]
Just updated an older app to 1.0.3.2. That uses cfs:gridfs. An error occurs for cfs:gridfs saying "no compatible build found." Looking at the repo for it, it says it has been merged into the core package but running the app, it still looks for the gridfs package. I have removed and installed cfs:standard-packages and have the most up to date version but no luck.

**Comment by aldeed** [comment]
It is still a separate package. It's in the core repo, but published separately. Try pinning to 0.0.29 or 0.0.27 version of cfs:gridfs. It ended up in some weird state due to some publishing issues.

**Comment by guitchicken** [comment]
Got it. I tried pinning to 0.0.29 and 0.0.28 and had the same issue. I just tried 0.0.27 and it's working fine now. Thanks.

**Comment by etmarch** [comment]
I am actually having the same issue - no matter what version I try to add (and no version), i get this error: 
```
While checking for cfs:gridfs@0.0.29:
error: No compatible build found
```
Any ideas how I can add gridfs back to my project? It was working fine a few days ago. 
Thanks.
