### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by wursttheke** [CollectionFS/Meteor-CollectionFS#577]
I'm currently working through the code. I'm 'starting' to get an overview of what is going on. :)

One question: Is [this file](https://github.com/CollectionFS/Meteor-CollectionFS/blob/devel/packages/upload-http/http-call-client.js) essentially the same as [this package](https://github.com/aldeed/meteor-http-extras) from @aldeed?

Could that be thrown out and replaced by the package (which seems to have some test)?

**Comment by raix** [comment]
I think it is - It would make sense to use Erics separate package (we can hope that it would be migrated into meteor core at some point)

**Comment by aldeed** [comment]
I agree we can switch to depending on the package. Probably did that before I created the package.

**Comment by wursttheke** [comment]
I already resolved this in https://github.com/CollectionFS/Meteor-CollectionFS/commit/dd3e57f72581ecb61b69fdd85e42414350574373. It's now using https://github.com/aldeed/meteor-http-extras.
