### ISSUE TITLE
Get the tests running again

### ISSUE THREAD

**Issue by wursttheke** [CollectionFS/Meteor-CollectionFS#579]
Although it says 'build passing' on the front page, the test aren't actually run at all. :smile: 

How can we get the test running again? Can there be a single travis.yml file at root for all packages?

**Comment by raix** [comment]
maybe we could have it run test for all packages at once - would make sense now we have it all under one repo - something worth investigating

**Comment by rhyslbw** [comment]
@wursttheke @raix Maybe this is better managed on the Trello board?

**Comment by wursttheke** [comment]
agree!
