### ISSUE TITLE
upload to s3 doesnt work with cfs:s3

### ISSUE THREAD

**Issue by nickmacia** [CollectionFS/Meteor-CollectionFS#583]
I followed the instructions on (https://github.com/CollectionFS/DEPRECATING-cfs-s3/blob/master/packages/s3/README.md) nearly verbatim and it fails to upload to my s3 instance. The collections, however, do work. I could be making a simple mistake since this is my first time using collectionFS. Here's the relevant code.

server side:

    var myStore = new FS.Store.S3("name", {
      region: "xxx-xxx-x",
      accessKeyId: "xxxx",
      secretAccessKey: "xxxx",
      bucket: "my-bucket",
      ACL: 'public-read-write', //just for debugging purposes
      folder: 'folder/',
      transformWrite: function(fileObj, readStream, writeStream) {
        gm(readStream, fileObj.name()).resize('250', '250').stream().pipe(writeSteam);
      }
    });

    Media = new FS.Collection("media", {
      stores: [myStore],
      filter: {
      allow: {
           contentTypes: ['image/*'],
           extensions: ['png', 'PNG', 'jpg', 'JPG', 'jpeg', 'JPEG']
        }
      }
    });

client side: 

    var myStore = new FS.Store.S3('name');

    Media = new FS.Collection("media", {
      stores: [myStore],
      filter: {
        allow: {
          contentTypes: ['image/*'],
          extensions: ['png', 'PNG', 'jpg', 'JPG', 'jpeg', 'JPEG']
        }
      }
    });

and the event code: 

    Template.myTemplate.events({
      'change #myInput': function(e, tpl) {
       //set up fview
       var fview = FView.from(tpl);
       //prevent reload
       e.preventDefault();
      //send the files to s3
       var files = event.target.files;
       for (var i = 0; i < files.length; i++) {
        Media.insert(files[i], function(err, fileObj) {
          if (err) {
            console.log(err);
          }
          else {
            console.log('worked');
          }
        });
      }
    }
    }); 

In addition, I followed the steps by creating a new user and attaching a custom policy. However, the policy that is provided on the docs is invalid. Amazon requires you to also include a version value, so I used: 

     {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket"
          ],
          "Resource": "arn:aws:s3:::*"
        },
        {
          "Action": [
            "s3:PutObject",
            "s3:PutObjectAcl",
            "s3:GetObject",
            "s3:GetObjectAcl",
            "s3:DeleteObject",
            "s3:DeleteObjectAcl"
          ],
          "Effect": "Allow",
          "Resource": [
            "arn:aws:s3:::my-bucket/*" 
          ]
        }
      ]
    }

**Comment by timfam** [comment]
I did exactly the same thing and tried with and with Fview.  ```/.meteor/packages/cfs_s3/.0.1.2.1g4c0ae++os+                                               web.browser+web.cordova/npm/node_modules/aws-sdk/lib/request.js:32
W20150304-23:22:12.134(0)? (STDERR)           throw err;
W20150304-23:22:12.134(0)? (STDERR)                 ^
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20150304-23:22:12.150(0)? (STDERR) Error: Error storing file to the s3Large sto                                               re: The specified bucket does not exist
W20150304-23:22:12.154(0)? (STDERR)     at [object Object].<anonymous> (packages                                               /cfs:collection/common.js:88:1)```

the bucket does exist and I even tried with a user with full access to all buckets

**Comment by nickmacia** [comment]
Do you think Fview makes a difference?

**Comment by timfam** [comment]
Same result without fview. What error are you getting?

**Comment by nickmacia** [comment]
Ok. So I just retried uploading to S3 and it worked; get rid of the transformWrite function on the tail end of the server instance of your store and it should work.
