### ISSUE TITLE
CFS-Example Broken: Client looking for image file in wrong place

### ISSUE THREAD

**Issue by KristerV** [CollectionFS/Meteor-CollectionFS#587]
I can upload to server, but can't fetch the image, because of filepath issues.

![screenshot_2015-03-05_13-15-44](https://cloud.githubusercontent.com/assets/2750622/6504011/245da7ec-c33b-11e4-998f-88bb710c7de7.png)

I got my code from the Readme.md.

```
Images = new FS.Collection("images", {
  stores: [new FS.Store.FileSystem("original", {path: "~/uploads"})]
});
```
The server gets the file and saves it just fine. But the client is still looking for the image in `website.com/cfs/files/images/hash/image.png` but it just aint there. No cfs folder exists anywhere.

When I add `FS.HTTP.setBaseUrl('/uploads');` to the mix, then the client is searching for the image in `website.com/uploads/files/images/hash/image.png`, still no good.

What am I missing?

**Comment by KristerV** [comment]
can be connected to #567

**Comment by KristerV** [comment]
I took the [cfs-example](https://github.com/CollectionFS/cfs-example) and there is the same issue. To reproduce:

1. Clone and run repo
2. Upload image
3. Download image

This was my result:
![screenshot_2015-03-05_13-33-22](https://cloud.githubusercontent.com/assets/2750622/6504124/7183de6e-c33c-11e4-8940-6d9eb9004041.png)

**Comment by KristerV** [comment]
I found the debug enable switch, here's what my server says about the upload (and why it refreshes)
```
I20150305-14:32:59.313(2)? token: eyJhdXRoVG9rZW4iOiIifQ==
I20150305-14:32:59.316(2)? HTTP PUT (update) handler received chunk:  0
I20150305-14:32:59.317(2)? GET FILERECORD: 4XLt77WuxqdhrGNvL
I20150305-14:32:59.350(2)? createWriteStream _tempstore, internal: true
I20150305-14:32:59.351(2)? createWriteStreamForFileKey _tempstore
I20150305-14:32:59.359(2)? -----------FINISH STREAM _tempstore
I20150305-14:32:59.361(2)? SA FileSystem - DONE!! fileKey: "images-4XLt77WuxqdhrGNvL-0.chunk"
I20150305-14:32:59.362(2)? -----------STORED STREAM _tempstore
I20150305-14:32:59.364(2)? -----------CLOSE STREAM _tempstore
I20150305-14:32:59.366(2)? TempStore progress: Received 1 of 1 chunks for Meet_cyberdemon.png
I20150305-14:32:59.367(2)? UPDATE: {"$set":{"uploadedAt":"2015-03-05T12:32:59.367Z"},"$unset":{"chunkCount":1,"chunkSum":1,"chunkSize":1}}
I20150305-14:32:59.369(2)? Meet_cyberdemon.png was successfully uploaded. You are seeing this informational message because you enabled debugging and you have not defined any listeners for the "uploaded" event on the images collection.
I20150305-14:32:59.375(2)? FileWorker ADDED - calling saveCopy original for 4XLt77WuxqdhrGNvL
I20150305-14:32:59.376(2)? saving to store original
I20150305-14:32:59.377(2)? createWriteStream original, internal: false
I20150305-14:32:59.378(2)? createWriteStreamForFileKey original
I20150305-14:32:59.381(2)? FS.TempStore creating read stream for 4XLt77WuxqdhrGNvL
I20150305-14:32:59.385(2)? createReadStream _tempstore
I20150305-14:32:59.386(2)? createReadStreamForFileKey _tempstore
I20150305-14:32:59.390(2)? -----------FINISH STREAM original
I20150305-14:32:59.391(2)? -----------FINISH STREAM original
I20150305-14:32:59.394(2)? SA FileSystem - DONE!! fileKey: "images-4XLt77WuxqdhrGNvL-Meet_cyberdemon.png"
I20150305-14:32:59.399(2)? -----------STORED STREAM original
I20150305-14:32:59.399(2)? -----------STORED STREAM original
I20150305-14:32:59.400(2)? SA original stored images-4XLt77WuxqdhrGNvL-Meet_cyberdemon.png
I20150305-14:32:59.400(2)? FS.File._saveChanges: original
I20150305-14:32:59.401(2)? UPDATE: {"$set":{"copies.original":{"name":"Meet_cyberdemon.png","type":"image/png","size":184608,"key":"images-4XLt77WuxqdhrGNvL-Meet_cyberdemon.png","updatedAt":"2015-03-05T12:32:59.000Z","createdAt":"2015-03-05T12:32:59.000Z"}}}
I20150305-14:32:59.402(2)? FS.File._saveChanges: _original
I20150305-14:32:59.405(2)? UPDATE: {"$set":{"original":{"name":"Meet_cyberdemon.png","updatedAt":"2015-03-05T08:48:29.000Z","size":184608,"type":"image/png"}}}
I20150305-14:32:59.408(2)? Meet_cyberdemon.png was successfully saved to the original store. You are seeing this informational message because you enabled debugging and you have not defined any listeners for the "stored" event on the images collection.
I20150305-14:32:59.408(2)? -----------CLOSE STREAM original
I20150305-14:32:59.409(2)? -----------CLOSE STREAM original
I20150305-14:32:59.420(2)? FileWorker ADDED - calling deleteChunks for 4XLt77WuxqdhrGNvL
I20150305-14:32:59.423(2)? ---SA REMOVE
=> Client modified -- refreshing
```

I guess the server refreshes, because the project files get updated when the app tries to add files into cfg/files. how the hell do I change this path? :)

**Comment by KristerV** [comment]
when I run my app I get this:
```
I20150305-14:16:01.857(2)? FS.HTTP.unmount:
I20150305-14:16:01.859(2)? {}
I20150305-14:16:01.860(2)? Registered HTTP method URLs:
I20150305-14:16:01.860(2)? /cfs/files/:collectionName/:id/:filename
I20150305-14:16:01.860(2)? /cfs/files/:collectionName/:id
I20150305-14:16:01.860(2)? /cfs/files/:collectionName
```
So I'm guessing I can change this path somehow...

**Comment by KristerV** [comment]
i found in the source, that FS.HTTP.mount() can be used to write your own mountPoints. Well, server didn't like that:

```
I20150305-14:52:02.278(2)? FS.HTTP.unmount:
I20150305-14:52:02.280(2)? { '~/uploads/:collectionName/:id/:filename': false,
I20150305-14:52:02.280(2)?   '~/uploads/:collectionName/:id': false,
I20150305-14:52:02.280(2)?   '~/uploads/:collectionName': false }
I20150305-14:52:02.281(2)? Registered HTTP method URLs:
I20150305-14:52:02.281(2)? /cfs/files/:collectionName/:id/:filename
I20150305-14:52:02.281(2)? /cfs/files/:collectionName/:id
I20150305-14:52:02.281(2)? /cfs/files/:collectionName
```

**Comment by KristerV** [comment]
okay, problem is solved by using the code
```
Images = new FS.Collection("images", {
	stores: [new FS.Store.FileSystem("original", {path: "~/uploads/"})]
});

FS.HTTP.setBaseUrl('uploads');
```
So the path can't be in Meteors public folder and it has to be in a place where the server-user has write permissions.

So going to use GridFS instead, looks simpler to use. 

---

I'm going to leave this issue open as the example is still broken and the documentation should say something about how this thing is really supposed to be used.

**Comment by aldeed** [comment]
@KristerV, the URL isn't supposed to match the file path. The URL is an abstract address that the access-point package sets up and then retrieves the requested file from wherever it lives (filesystem, S3 bucket, GridFS, etc.).

I don't see any problems in your logs. It seems like the only issue is the forbidden error. Two things you can try:

1. If you call `setBaseUrl`, make sure it is in common code, otherwise server will set up the URL in one place and client will request it in another.
2. Make sure you have download `allow/deny` set up to allow downloads.

**Comment by aldeed** [comment]
In general, filesystem SA doesn't work with most hosting providers, at least not simply, because the filesystem does not persist. It's fine for local testing, but we recommend S3 or GridFS (or create your own storage adapter) if you're deploying to a hosting provider. Some hosting providers, like Modulus, provide a special filesystem path that is a persistent "cloud drive", in which case you can use the filesystem SA and point it to that path.

**Comment by KristerV** [comment]
oh my god download has to be allowed? how did I miss this... let me just adjust the readme a bit...

**Comment by KristerV** [comment]
and I did get my program running. Now it's just a question of why the example isn't running.
