### ISSUE TITLE
Qustion: Generate missing stores

### ISSUE THREAD

**Issue by KristerV** [CollectionFS/Meteor-CollectionFS#595]
Say I've got an image gallery site and added a new store with thumbnails. How do I generate thumbnails for the images that have already been uploaded?

I have already saved the original under the store name 'original'. Not sure if this was necessary, but here it is :)

**Comment by rhyslbw** [comment]
Yest it's a good idea to define and `originals` store if you plan to build out other copies at a later stage, as they are not saved by default. Pretty sure you will have to stream out of the originals store and then into the new store. I've not actually done this myself yet, but have seen it mentioned in the documentation, codebase, and discussion.

**Comment by raix** [comment]
// The initial version of cfs did actually rebuild new SA's but its not trivial in the new arch - eg. how to translate/transform data from one SA to another. There is work being done adding a copy function - making it easy to write a migrate function copying data from one SA to another.

**Comment by rhyslbw** [comment]
Work on this feature is being tracked in this PR https://github.com/CollectionFS/Meteor-CollectionFS/pull/559
