### ISSUE TITLE
Wrong filetype when changing the extension

### ISSUE THREAD

**Issue by delportd** [CollectionFS/Meteor-CollectionFS#598]
Hi,

I'm using gm (graphicmagick) package with your nice CollectionFS package for meteor, gm can only compress images. So I actually use the filtering who you are providing to deny anything except jpeg and png :

---
```javascript
Collections.Images = new FS.Collection("images", {
  stores: [
    Stores.images
  ],
  filter: {
    maxSize: 5 * 1024 * 1024, // 5 Mo
    allow: {
      contentTypes: ['image/png', 'image/jpeg']
    },
    onInvalid: function(message) 
    {
    ...
    }
  }
});
```
---
```javascript
Stores.images = new FS.Store.FileSystem("images", {
	path: "/var/www/uploads",
    transformWrite: function(fileObj, readStream, writeStream) 
    {
		gm(readStream, fileObj.name()).autoOrient().quality(40).stream().pipe(writeStream);
    }
});
```
---

**The problem is when someone evil change the file extension !**
For example, download a little AVI file (like that one http://www.mysticfractal.com/video/fp.avi) just change the file fp.avi in fp.png and tada the file is allowed to be uploaded :/

When I upload fp.png file the filetype is wrong :
```
I20150308-11:16:34.738(0)? { createdByTransform: true,
I20150308-11:16:34.739(0)?   original: 
I20150308-11:16:34.739(0)?    { name: 'fp.png',
I20150308-11:16:34.739(0)?      updatedAt: Sun Mar 08 2015 10:34:24 GMT+0000 (UTC),
I20150308-11:16:34.739(0)?      size: 318464,
I20150308-11:16:34.739(0)?      type: 'image/png' },
I20150308-11:16:34.739(0)?   uploadedAt: Sun Mar 08 2015 11:16:27 GMT+0000 (UTC),
I20150308-11:16:34.739(0)?   _id: 'jzvkKcMSraf5hPozH',
I20150308-11:16:34.739(0)?   collectionName: 'images',
I20150308-11:16:34.739(0)?   copies: { images: { name: 'fp.png', type: 'image/png', size: 318464 } } }
```

I wish I could do filetype checking like the "file" unix command do, is it possible ?
With the fp.avi file the file command shows :
```bash
[yam@yam-linux Téléchargements]$ file fp.avi 
fp.avi: RIFF (little-endian) data, AVI, 320 x 240, 15.00 fps, video:
[yam@yam-linux Téléchargements]$ mv fp.avi fp.png
[yam@yam-linux Téléchargements]$ file fp.png 
fp.png: RIFF (little-endian) data, AVI, 320 x 240, 15.00 fps, video:
```

Thank's again,
Sorry for my bad english.

**Comment by aldeed** [comment]
I guess your OS must change the content type when the extension is changed. I didn't know that would happen.

It is possible to try to sniff actual file type from the stream data, but we haven't provided a great way to reject the upload based on that. For example: https://www.npmjs.com/package/stream-mmmagic

**Comment by delportd** [comment]
Is it possible to reject the insertion in the database server side if i manage to use the extension you gave me ?

In other words i would like to do : 
1) The client upload his picture
2) The server checks the real filetype (and not the extension) by looking with stream-mmmagic
    If the filetype is not an image deny image insertition
    Else go on with gm compressing the image

In other words does your plugin provide a way to check someting before insert it in the mongo databse ?

Thank you so much !

**Comment by aldeed** [comment]
Currently you can access the incoming stream only in a `transformWrite` function, and you could simply not pipe it, which would not upload it. However, I don't think we truly support that behavior right now, meaning the code expects it always to be piped and I don't know what will happen if you don't. This is what I mean when I say we don't have a great way to do this right now. It might be possible to have something like `this.reject()` that you can call in a `transformWrite`. cc @raix

**Comment by delportd** [comment]
I'm stuck again, trying to follow your advices, there is my new code : 
```javascript
Stores.images = new FS.Store.FileSystem("images", {
	path: "/var/www/uploads",
    transformWrite: function(fileObj, readStream, writeStream) 
    {
		var magic = Meteor.npmRequire('stream-mmmagic');
		 
		magic(readStream, function (err, mime, output) 
		{
			if (err) throw err;

			if ((mime.type == 'image/jpeg') || (mime.type == 'image/png') ) 
			{
				gm(readStream, fileObj.name()).autoOrient().quality(40).stream().pipe(writeStream);
			}
			else
			{
				console.log('Evil guy is trying to do stupid things :', mime.type);
				//We will see later what we do with the bad file
				//Maybe delete the database entry ??
				/*
				Images.remove({
					id : fileObj._id
				});
				*/
			}
		});
	}
});
```

The stream-mmmagic npm is working so well, it successfully detected the bad file, but now it seems that I can use only once the readStream pointer.
What I am doing wrong ?

Thank's !

**Comment by aldeed** [comment]
Yeah, so that's the part that I think we'd need `this.reject()` for. But MAYBE you can simply do `fileObj.remove()`. But I kind of doubt that will work perfectly.

**Comment by delportd** [comment]
The remove is not working because the library needs to use Meteor.bindEnvironment ... I will try that !

I tried to add another metadata entry called "safe" initialy set to "unknown" : 
```javascript
'change input.images': FS.EventHandlers.insertFiles(Collections.Images, 
    {
      metadata: function (fileObj) 
      {
        return {
          ecole: Session.get('ecole') ? Session.get('ecole') : "Inconnue",
          displayed: "no",
          safe: "unknown"
        };
      },
      after: function (error, fileObj)
...
    })
```

Then in the store file I'm trying to modify the safe value : 
```javascript
    transformWrite: function(fileObj, readStream, writeStream) 
    {
		var magic = Meteor.npmRequire('stream-mmmagic');

		magic(readStream, function (err, mime, output) 
		{
			if (err) throw err;

			if ((mime.type === 'image/jpeg') || (mime.type === 'image/png')) 
			{
				fileObj.safe = "yes";
				//Collections.Images.update({ _id: fileObj._id}, {$set: {'safe': "yes"}});
				gm(output, fileObj.name()).autoOrient().quality(40).stream().pipe(writeStream);
			}
			else
			{
				fileObj.safe = "no";
				//Collections.Images.update({ _id: fileObj._id}, {$set: {'safe': "no"}});
				console.log('Evil guy is trying to do stupid things :', mime.type);
				//output.pipe(writeStream);
				fileObj.remove();
			}
		});
	}
```

But the change is not persisted, so I tried with Collections.Images.update, and the problem is the same Meteor tell me to use Meteor.bindEnvironment.
Could you help me with that i'm not very confident about the use of that fonction.

Thank's a lot !

**Comment by delportd** [comment]
I eventually managed to make the damn thing work, I post the solution just in case someone needs it : 

```javascript
if (Meteor.isClient) 
{
	Stores.images = new FS.Store.FileSystem("images", {
		path: "/var/www/uploads"
	});
}
else
{
	Stores.images = new FS.Store.FileSystem("images", {
	  path: "/var/www/uploads",
	  transformWrite: function(fileObj, readStream, writeStream) 
	  {
	  	var Fiber = Npm.require('fibers');
	  	Fiber(function() {
	      var magic = Meteor.npmRequire('stream-mmmagic');
	      magic(readStream, Meteor.bindEnvironment(function (err, mime, output) 
	      {
          if (err) throw err;

          if ((mime.type === 'image/jpeg') || (mime.type === 'image/png')) 
          {
              fileObj.update({$set: {'safe': "yes"}});
              gm(output, fileObj.name()).autoOrient().quality(40).stream().pipe(writeStream);
          }
          else
          {
              console.log('Evil guy is trying to do stupid things :', mime.type);
              fileObj.update({$set: {'safe': "no"}});
              output.pipe(writeStream);
          }
				}));
			}).run();
    }	
	});
}
```

Thank you very much @aldeed for taking me in the right direction !

**Comment by digz6666** [comment]
@delporte Thanks for solving and sharing your fix.
