### ISSUE TITLE
Question: is there a way to generate the token or give access to some files without security?

### ISSUE THREAD

**Issue by adamgins** [CollectionFS/Meteor-CollectionFS#600]
Hi, I am trying to improve performance of an app that displays a list of documents and each of these has a thumbnail. I have it all working, but the cross-lookup of my "images" collection based on the stored "thumbnail" id seems expensive. 

I could save the CFS "key" when the image is created and generate the URL to the image, thus not requiring me to subscribe to the "images" collection for that specific page. The missing bit is the token at the end of the URL. 

So just wondering, is this a bad bad thing? If not, is there a way to programmatically do what I want and get the relative URL to the image at save time with the token?

**Comment by raix** [comment]
I think the file-ejson is the pattern that would be ideal - but not sure if its still working.
I converts a file into a reference of "collectionName" and "fileId" in eg. your blog collection. When you retrieve the blog post the image reference will be transformed into a FS.File object again, with regular helpers etc. - this is all without actually subscribing to the file record it self.
