### ISSUE TITLE
Question: How to wait until writeStream finished?

### ISSUE THREAD

**Issue by lugaru90** [CollectionFS/Meteor-CollectionFS#602]
Hey,

i'm uploading an image, later on let the user crop the image and use the following command to update the Thumbnail image:
```javascript
var imageFile = Images.findOne({'metadata.user': Meteor.user()._id, 'metadata.isNew':true});
var readStream = imageFile.createReadStream('thumbs');
var writeStream = imageFile.createWriteStream('thumbs');
gm(readStream, imageFile.name()).resize('100', '100').stream().pipe(writeStream);
```

Afterwards call the Update Function to set a metadata active Flag. This works fine but shows a not found image on the Template, until the User refreshs.

So is there a way to wait until the writestream is finished?

EDIT ADD: Also the Browser/Meteor (idk)  don't recognize that the Image has resized and uses the Old Image... Any fix for this?

**Comment by raix** [comment]
Please read the official node js documentation on streams - you could use events
