### ISSUE TITLE
Uploading big video crashes app

### ISSUE THREAD

**Issue by bitomule** [CollectionFS/Meteor-CollectionFS#604]
I've uploaded a 35mb video to my app and it crashed. It can't even reboot (using meteor up). I think the crash is related to trying to transform the video to create a thumbnail (I want to do it with images)

Is it possible to filter files based on store or to cancel a file write inside transformWrite or beforeWrite?

Thanks.

**Comment by bitomule** [comment]
Tried again to upload and got this error:

FATAL ERROR: Evacuation Allocation failed - process out of memory

I've created a swap partition and now I'm trying with a bigger file but the question is, how much ram could the upload to amazon S3 take?

**Comment by aldeed** [comment]
The upload is most likely not using much RAM since everything is streams. I would suspect something in your transformWrite.

**Comment by bitomule** [comment]
I've removed the store with transformWrite just to test if that's the problem and still got the error. I'm uploading a 2GB file now with the swap enabled.

**Comment by rhyslbw** [comment]
If there is still an issue please share a demo repository that isolates the issue. Thanks
