### ISSUE TITLE
regression: Exception in queued task: TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by acemtp** [CollectionFS/Meteor-CollectionFS#605]
I had no problem until I updated to a recent version (I tried with the latest one).
When uploading an image, I have this error on the server:

I20150312-16:34:10.764(1)? Exception in queued task: TypeError: Cannot read property 'start' of undefined
I20150312-16:34:10.765(1)?     at Object.FS.StorageAdapter.createReadStream (packages/cfs:gridfs/gridfs.server.js:78:1)
I20150312-16:34:10.765(1)?     at Object.self.adapter.createReadStreamForFileKey (packages/cfs:storage-adapter/storageAdapter.server.js:71:1)
I20150312-16:34:10.765(1)?     at Object.self.adapter.createReadStream (packages/cfs:storage-adapter/storageAdapter.server.js:79:1)
I20150312-16:34:10.765(1)?     at packages/cfs:tempstore/tempStore.js:364:1
I20150312-16:34:10.765(1)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150312-16:34:10.765(1)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150312-16:34:10.765(1)?     at CombinedStream._getNext (/Users/acemtp/.meteor/packages/cfs_tempstore/.0.1.4.u6y54i++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:83:3)
I20150312-16:34:10.765(1)?     at CombinedStream.resume (/Users/acemtp/.meteor/packages/cfs_tempstore/.0.1.4.u6y54i++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:132:10)
I20150312-16:34:10.765(1)?     at CombinedStream.pipe (/Users/acemtp/.meteor/packages/cfs_tempstore/.0.1.4.u6y54i++os+web.browser+web.cordova/npm/node_modules/combined-stream/lib/combined_stream.js:64:8)
I20150312-16:34:10.765(1)?     at saveCopy (packages/cfs:worker/fileWorker.js:176:1)

**Comment by acemtp** [comment]
Seems a `options = options || {};` is missing in the beginning of `createReadStream` here https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/gridfs/gridfs.server.js#L68

**Comment by phsultan** [comment]
I had the same issue, and it turned out to be fixed in the 'devel' branch of the cvs:gridfs package. You'll get more information there : #588.

Cheers.

**Comment by evliu** [comment]
+1
