### ISSUE TITLE
cURL post request

### ISSUE THREAD

**Issue by samu79** [CollectionFS/Meteor-CollectionFS#606]
Good morning,

I tried to upload a file from my Desktop to a GridFS collection named "Files" with the following command:

**curl -v -X POST 'http://localhost:3000/cfs/files/Files/' -F 'file=@"download.jpeg";type=image/jpeg'**

and this is the answer:

* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
* > POST /cfs/files/Files/ HTTP/1.1
* > User-Agent: curl/7.37.1
* > Host: localhost:3000
* > Accept: */*
* > Content-Length: 5626
* > Expect: 100-continue
* > Content-Type: multipart/form-data; boundary=------------------------955a67d5c4b2f2c4
* > 
* < HTTP/1.1 100 Continue
* < HTTP/1.1 501 Not Implemented
* < vary: Accept-Encoding
* < access-control-allow-origin: http://meteor.local
* < access-control-allow-methods: PUT
* < access-control-allow-headers: Content-Type
* < date: Thu, 12 Mar 2015 14:25:55 GMT
* < connection: keep-alive
* < transfer-encoding: chunked
* HTTP error before end of send, stop sending
< 
* Closing connection 0

Could you please explain me where is the error?

This is the source code:

```javascript
var fileStore = new FS.Store.GridFS("fileStore");
Files = new FS.Collection("Files", {
  stores: [fileStore]
});

if (Meteor.isClient) {
  Template.demo.helpers({
    files: function() {
      var objs = Files.find();
      return Files.find();
    }
  });

  Template.demo.events({
    'change #file': function(e, t) {
      if (this.userId) {
        var file = t.find('#file').files[0];
        console.log(file.name);
        var newFile = new FS.File(file);
        fsFile.owner = this.userId;
        newFile.metadata = {
          fn: "filename" 
        };
        Files.insert(newFile, function (err, fileObj) {
          if (!err) {
            var _fId = newFile._id;
            var _fn = file.name;
            var _collectionName = newFile.collectionName;
            var _basePath = "/cfs/files/";
            var _downloadPath = _basePath + _collectionName + "/" + _fId;
            console.log(this.userId);

            FileList.insert({
              _id: this.userId,
              fileId: _fId,
              fileName: _fn,
              collectionName: _collectionName,
              basePath: _basePath,
              downloadPath: _downloadPath
            });
          }
        });
      }
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    if (Meteor.users.find({}).count() === 0) { 
      Accounts.createUser({
        email : "demo@demo.it",
        password : "password",
        profile  : {
          //publicly visible fields like firstname goes here
        }
      });
    }

    // code to run on server at startup
    console.log("Set Restivus");
    Restivus.configure({
      useAuth: true,
      prettyJson: true
    });

    Restivus.addCollection(FileList, {
      excludedEndpoints: ['deleteAll'],
      routeOptions: {
        authRequired: true
      },
    });

    Restivus.addCollection(Files, {
      excludedEndpoints: ['deleteAll'],
      routeOptions: {
        authRequired: true
      },
    });

    Files.allow({
      insert: function(userId, fileObj) {
        return true;
      }
    });
  });
}
```

Thank you

**Comment by TeachMeFly** [comment]
It seems cfs:access-point not suppert post requests
https://github.com/CollectionFS/Meteor-CollectionFS/blob/devel/packages/access-point/access-point-server.js#L136

**Comment by samu79** [comment]
So, this means that there are no way to upload a file through cURL command?

Or maybe there is another way to do that? 
This is a very important part of my project.

Thank you.

**Comment by TeachMeFly** [comment]
cfs use put requests for upload files, think there is no difference what make this request. So just use curl -v -X PUT.

**Comment by samu79** [comment]
With 

*curl -X PUT 'http://127.0.0.1:3000/cfs/files/Files' -H 'Content-Type: image/jpeg' -H 'X-Auth-Token: N_75fhQi2Rt7_HuJ9RNBAY4XbGRA1W7WAZsx1xjNykM' -H 'X-User-Id: cfqShcgPhJkB5FdpB' -T "download.jpeg"*

I get the following error:

Error in method "/cfs/files/:value/", Error: ReferenceError: file is not defined
    at Object.httpPutInsertHandler (packages/cfs:access-point/access-point-handlers.js:223:1)
    at Object.accessPoint.put (packages/cfs:access-point/access-point-server.js:151:1)
    at packages/cfs:http-methods/http.methods.server.api.js:551:1

**Comment by rhyslbw** [comment]
Continued here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/611
