### ISSUE TITLE
While checking for cfs:gridfs@0.0.31 error: No compatible build found

### ISSUE THREAD

**Issue by bluebay** [CollectionFS/Meteor-CollectionFS#607]
Using latest version Windows Preview Release.
While trying to install cfs:gridfs, I get the error described in title.

**Comment by aldeed** [comment]
We tried publishing for Windows but ran into problems. Waiting for confirmation that things are working better before we try that again.

**Comment by bluebay** [comment]
@aldeed 
What do you mean by better?
Can I help you in any way?
If you could point me to some modifications, I could try doing those in my machine and check.

Thank you :)

**Comment by rhyslbw** [comment]
@bluebay I'm pretty sure the problems are with the Meteor codebase and the packaging system. A quick search in this repo's issues will surface more details discussion on the matter.

**Comment by aldeed** [comment]
@bluebay see https://github.com/meteor/windows-preview/issues/45

**Comment by rhyslbw** [comment]
Seems like this one can be closed
