### ISSUE TITLE
Error: Access denied. No allow validators set on restricted collection for method 'insert'. [403]

### ISSUE THREAD

**Issue by dooart** [CollectionFS/Meteor-CollectionFS#608]
When calling `insert` to upload images to S3 I'm getting this error message as the result of the RPC call: "Access denied. No allow validators set on restricted collection for method 'insert'. [403]"

Both autopublish and insecure were already removed.

I dug a little bit into the code and found out that if I called `allow` to configure `insert` and `update` after creating the collection, the error would go away and the file would be uploaded, but the documentation doesn't mention it anywhere:
````
	var collection = new FS.Collection("profilePictures", {
		// ...
	});

	ProfilePictures = collection.allow({
		insert: function() {
			return true;
		},
		update: function() {
			return true;
		}
	})
````

I feel like I'm probably configuring something wrong, but can't figure out what. Any ideas?

This is the code without the workaround: http://pastebin.com/j4BRza0f

**Comment by rhyslbw** [comment]
It's a requirement to define these rules in server code just like a normal Mongo.Collection, documented under [Security](https://github.com/CollectionFS/Meteor-CollectionFS#security), but it is a little buried. The project's codebase and documentation is currently in flux, so I'm hesitant to submit a PR, but it's likely a more complete example of the full basic configuration will be higher up the page, or in a dedicated guide once things settle down.

I've just answered a [question on SO](http://stackoverflow.com/questions/29064876/meteor-not-able-to-upload-image-to-s3-using-collectionfs/29066560#29066560) that may help clarify.

**Comment by dooart** [comment]
Ok, thanks. :)

I had some more problems to actually get the url after the upload. The result object's url field was `null` so I figured I'd have to call `find()` on the collection, but it was empty. Does this have anything to do with publications, since I ha?

**Comment by rhyslbw** [comment]
You need to publish the documents as per usual. Your code is a bit wonky though. Try the following, noting that the FS.Collection is now not scoped to the file.

    ProfilePictures = new FS.Collection("profilePictures", {
        // ...
    });

    ProfilePictures.allow({
        insert: function() {
            return true;
        },
        update: function() {
            return true;
        }
    })

**Comment by dooart** [comment]
I'm almost sure I've tried that and it didn't work. I remember that for some reason I had to return the result of the `allow` call for it to work.

But I'll try one more time, thanks.

**Comment by rhyslbw** [comment]
Also note there is a custom rule `download` that you are currently missing
