### ISSUE TITLE
Clean up the Collection when upload failed

### ISSUE THREAD

**Issue by Visudare** [CollectionFS/Meteor-CollectionFS#609]
Hey!

Is there a recommended way to clean up the Collection when an upload failed ?

I am now at the following situation:

When uploading multiple files and while uploading them the internet connection is gone (or I close the Tab while uploading) the FS Document still exists with this information:

```javascript
_events: Object
_id: "zvYcjge8SmNYwNxQv"
_maxListeners: 10
chunkCount: 0
chunkSize: 2097152
chunkSum: 1
collectionName: "files"
createdByTransform: true
domain: null
original: Object
owner: "exsrC8roKDw2TbAdk"
```

Is there a way to read out that this Document failed while uploading ? Or is they any other way ? So I can use a process to clean up the Collection every x-seconds to remove all documents which failed because CollectionFS does not do this by them self.

**Comment by rhyslbw** [comment]
Without being able to confirm if this is expected (it seems like it should be handled internally), does the debug messages reveal anything else?

`FS.debug = true;`

**Comment by Visudare** [comment]
Why this issue is closed ? I am reworking on my project and the problem still exists. It is easy to reproduce if you enable multiple file upload. When you now select (for example) about 15 files to upload and right after the uploading has started close the Tab. When you now reopen your meteor project you will see that all 15 Files was added to your collection but with the fact that no one of this has the "uploadedAt" property because the file itself was not uploaded (you will not be able to show these file with this.url). Its very hard to clean this up for me because I dont know how to check which upload really failed and which upload is just not finished yet.
