### ISSUE TITLE
How to configure direct S3 download link to bypass the Meteor server

### ISSUE THREAD

**Issue by Visudare** [CollectionFS/Meteor-CollectionFS#610]
Is there any way to use the direct link from the specific store for this.url ? My store is S3 and I want to display the direct S3 link so I want to avoid the security allow/deny options from CollectionFS.

**Comment by rhyslbw** [comment]
Would just returning `true

**Comment by raix** [comment]
we use fileKey to generate the filename on the storage: https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/s3/s3.server.js#L122 - so if you have public files in there you could link directly - CFS will be able to redirect securely to S3 files in the future making sure you app server isn't used for downloads

**Comment by Visudare** [comment]
@raix Thanks for this hint but I dont get it ... can you give me an example how do you insert the direct S3 link instead of the /cfs link ?

**Comment by rhyslbw** [comment]
@Visudare Just so it's clear, your goal is not "to avoid the security allow/deny options from CollectionFS" but to load the images directly from S3?

Check [this wiki article](https://github.com/CollectionFS/Meteor-CollectionFS/wiki/How-to:-Customize-the-folders-on-the-filesystem) to see how to generate a custom fileKey, which be a start.

**Comment by Visudare** [comment]
@rhyslbw Thanks for this hint! This looks interesting! I will work with this :) And yes you're right: My goal isnt the security issue.

**Comment by rhyslbw** [comment]
@Visudare No worries. Reopen this ticket if you want to post any working code examples
