### ISSUE TITLE
Update file with cURL not updated 

### ISSUE THREAD

**Issue by samu79** [CollectionFS/Meteor-CollectionFS#611]
Good morning,

I would like to update a file already present in the GridFS Store with the following cURL command:

**curl -v -X PUT 'http://127.0.0.1:3000/cfs/files/Files/pEWwRmvL4Cp7SdTmc' -H 'Content-Type: text/plain' -T "fn2.log"**

The answer is:

* * Hostname was NOT found in DNS cache
* *   Trying 127.0.0.1...
* * Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
* > PUT /cfs/files/Files/pEWwRmvL4Cp7SdTmc HTTP/1.1
* > User-Agent: curl/7.37.1
* > Host: 127.0.0.1:3000
* > Accept: */*
* > Content-Type: text/plain
* > Content-Length: 2423
* > Expect: 100-continue
* > 
* < HTTP/1.1 100 Continue
* * We are completely uploaded and fine
* < HTTP/1.1 200 OK
* < vary: Accept-Encoding
* < access-control-allow-origin: http://meteor.local
* < access-control-allow-methods: PUT
* < access-control-allow-headers: Content-Type
* < content-type: text/html
* < date: Tue, 17 Mar 2015 08:21:42 GMT
* < connection: keep-alive
* < transfer-encoding: chunked
* < 
* * Connection #0 to host 127.0.0.1 left intact

In the server console I get the following output:

* token: undefined
* HTTP PUT (update) handler received chunk:  0
* GET FILERECORD: pEWwRmvL4Cp7SdTmc
* createWriteStream _tempstore, internal: true
* createWriteStreamForFileKey _tempstore
* SA GridFS - DONE!
* -----------STORED STREAM _tempstore
* -----------CLOSE STREAM _tempstore
* TempStore progress: Received 1 of 1 chunks for fn2.log
* UPDATE: {"$set":{"synchronizedAt":"2015-03-17T08:21:42.233Z"},"$unset":{"chunkCount":1,"chunkSum":1,"chunkSize":1}}
* Uploaded pEWwRmvL4Cp7SdTmc in Files collection.

Exploring the database, I see that the file in *cfs_gridfs.fileStoreFile.files* is not updated, but it seems that the file is in *cfs_gridfs._tempstore.files*.

This is my source code:

```javascript
FS.debug = true;

var fileStore = new FS.Store.GridFS("fileStore");

Files = new FS.Collection("Files", {
  stores: [fileStore]
});

Files.allow({
  insert: function () {
    return true;
  },
  update: function () {
    return true;
  },
  remove: function () {
    return true;
  },
  download: function () {
    return true;
  }
});

Files.on('uploaded', function (fileObj) {
  console.log("Uploaded " + fileObj._id + " in Files collection.");
});

if (Meteor.isClient) {
  Template.demo.helpers({
    files: function() {
      var objs = Files.find();
      return Files.find();
    }
  });

  Template.demo.events({
    'change #file': function(e, t) {
      console.log("Event captured");
      var file = t.find('#file').files[0];
      console.log(file.name);
      var newFile = new FS.File(file);
      newFile.owner = this.userId;
      newFile.metadata = {
        fn: "filename" 
      };
      Files.insert(newFile, function (err, fileObj) {
        if (!err) {
          var _fId = newFile._id;
          var _fn = newFile.original.name;
          var _collectionName = newFile.collectionName;
          var _basePath = "/cfs/files/";
          var _downloadPath = _basePath + _collectionName + "/" + _fId;

          FileList.insert({
            //_id: '0',//Meteor.userId(),
            fileId: _fId,
            fileName: _fn,
            collectionName: _collectionName,
            basePath: _basePath,
            downloadPath: _downloadPath
          });
        }
      });
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    if (Meteor.users.find({}).count() === 0) { 
      Accounts.createUser({
        email : "demo@demo.it",
        password : "password",
        profile  : {
          //publicly visible fields like firstname goes here
        }
      });
    }

    // code to run on server at startup
    console.log("Set Restivus");
    Restivus.configure({
      useAuth: true,
      prettyJson: true
    });

    Restivus.addCollection(FileList, {
      excludedEndpoints: ['deleteAll', 'post', 'delete'],
      routeOptions: {
        authRequired: true
      }
    });
  });
}
```

Is there any error? Could you please help me?

Thank you.

Regards

**Comment by rhyslbw** [comment]
Does [Debug mode](https://github.com/CollectionFS/Meteor-CollectionFS/wiki/Troubleshooting) reveal anything?

**Comment by samu79** [comment]
This is the output of debug:

HTTP PUT (update) handler received chunk:  0
I20150319-11:51:30.654(1)? GET FILERECORD: vnGzzrpckd4EeDYky
I20150319-11:51:30.688(1)? createWriteStream _tempstore, internal: true
I20150319-11:51:30.688(1)? createWriteStreamForFileKey _tempstore
I20150319-11:51:30.717(1)? -----------FINISH STREAM _tempstore
I20150319-11:51:30.717(1)? SA FileSystem - DONE!! fileKey: "LogFiles-vnGzzrpckd4EeDYky-0.chunk"
I20150319-11:51:30.718(1)? -----------STORED STREAM _tempstore
I20150319-11:51:30.718(1)? -----------CLOSE STREAM _tempstore
I20150319-11:51:30.721(1)? TempStore progress: Received 1 of 1 chunks for filename5.txt
I20150319-11:51:30.722(1)? UPDATE: {"$set":{"synchronizedAt":"2015-03-19T10:51:30.721Z"},"$unset":{"chunkCount":1,"chunkSum":1,"chunkSize":1}}
I20150319-11:51:30.723(1)? filename5.txt was successfully uploaded. You are seeing this informational message because you enabled debugging and you have not defined any listeners for the "uploaded" event on the LogFiles collection.

Any ideas?

Thank you

**Comment by rhyslbw** [comment]
Hmm. I would suggest creating a simplified app that contains as much standard cfs config to try and isolate this, as there's little to go on with the debug messages.

**Comment by samu79** [comment]
This is the simplified app:

```javascript
FS.debug = true;

var fileStore = new FS.Store.FileSystem("fileStore", {
  path: "~/uploads/FSDemo"
});
Files = new FS.Collection("Files", {
  stores: [fileStore]
});

Files.allow({
    download: function(userId, fileObj) {
        return true
    },
    insert: function(userId, fileObj) {
        return true
    }
});

if (Meteor.isClient) {

  Template.hello.helpers({
    files: function() {
      var objs = Files.find();
      return Files.find();
    }
  });

  Template.hello.events({
    'change #file': function(e, t) {
      var file = t.find('#file').files[0];
      var newFile = new FS.File(file);
      newFile.metadata = {
        fn: "filename" 
      };
      Files.insert(newFile, function (err, fileObj) {
        if (!err) {
          console.log(fileObj);
        }
      });
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    console.log("Server up");
  });
}
```

and this is the server output:

* token: undefined
* I20150319-12:22:30.455(1)? HTTP PUT (update) handler received chunk:  0
* I20150319-12:22:30.455(1)? GET FILERECORD: KfjWNvfYRHGLCWwEG
* I20150319-12:22:30.459(1)? createWriteStream _tempstore, internal: true
* I20150319-12:22:30.459(1)? createWriteStreamForFileKey _tempstore
* I20150319-12:22:30.460(1)? -----------FINISH STREAM _tempstore
* I20150319-12:22:30.462(1)? SA FileSystem - DONE!! fileKey: "Files-KfjWNvfYRHGLCWwEG-0.chunk"
* I20150319-12:22:30.462(1)? -----------STORED STREAM _tempstore
* I20150319-12:22:30.462(1)? -----------CLOSE STREAM _tempstore
* I20150319-12:22:30.465(1)? TempStore progress: Received 1 of 1 chunks for file.txt
* I20150319-12:22:30.465(1)? UPDATE: {"$set":{"synchronizedAt":"2015-03-19T11:22:30.464Z"},"$unset":{"chunkCount":1,"chunkSum":1,"chunkSize":1}}
I20150319-12:22:30.465(1)? file.txt was successfully uploaded. You are seeing this informational message because you enabled debugging and you have not defined any listeners for the "uploaded" event on the Files collection.

But the file is always the same.

**Comment by rhyslbw** [comment]
I don't really understand what you're trying to achieve. If you can link me to a repo where I can download this app, I'll take a look with a local running copy.

**Comment by samu79** [comment]
I'm trying to upload a file via cURL from my desktop to meteor server.
I need to test if it's possible, because the next step will be upload a file from my phone with a native app to meteor.

**Comment by aldeed** [comment]
Hi @samu79, there were a couple bugs with PUT uploads, which I've now fixed. Upload to latest CFS and something like the following should work:

```
curl "http://localhost:3000/cfs/files/files?filename=text.txt" -H "Content-Type: text/plain" -T "text.txt"
```

The "cfs/files/files" piece is CFS base URL (default "/cfs") + "/files/" + collectionName (first arg when creating the collection). The `filename` query string is optional, but file name will be `null` in the database if you don't supply it. The content-type header is required.

If you pre-insert the file some other way (like DDP method requests) and you only want to upload data for it, you can use PUT to upload chunks for it by adding one more piece, "/" + file _id. And `chunk=0`, etc. in the query string. I don't know that we've tested this much, but it might work.

**Comment by patte** [comment]
@aldeed where might I find more information about the PUT upload? Basically I want to set metadata on the file record based on header information.
