### ISSUE TITLE
EventEmitter maxListeners and General Usage

### ISSUE THREAD

**Issue by jchristman** [CollectionFS/Meteor-CollectionFS#612]
I'm writing a library that uses CollectionFS to create a file browser for clients. I'm currently using cfs:filesystem to do this, but I want to have each client's files stored in a directory with the pattern ```~/users/USERNAME/files```. To do this, I am currently doing:

```js
var fileStore = new FS.Store.FileSystem(unique_name, {
    path : '~/users/' + username + '/files'
});
this.FS_COLLECTION = new FS.Collection(unique_name, {
    stores : [fileStore]
});
```

This essentially creates a collection for every single user that I can retrieve based on their username when they are logged in.

The problem is, I am getting the following warning upon creation of my test users:

```
warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```

This seems to stem from your use of [raix:eventemitter](https://github.com/raix/Meteor-EventEmitter). I believe this could be fixed by calling ```EventEmitter.setMaxListeners(0)```, but I cannot figure out how to get a handle to the event emitter for the FS system.

So my question is twofold:
 - Am I being a horrible person for creating an FS.Collection for each person? Is there a better way to do what I want?
 - ~~Is there a way for me to get a handle to the EventEmitter on the storage adapter so that I can call the above line of code? If not, is it possible to create this capability?~~

Thanks!

**Comment by jchristman** [comment]
I was actually able to fix the warning by calling:

```js
Meteor.startup(function() {
    FS.TempStore.setMaxListeners(0);
});
```

so that is how you fix the warning.

I guess my first question still remains. Is this a bad way of doing it?

**Comment by rhyslbw** [comment]
See this wiki article on [How-to:-Customize-the-folders-on-the-filesystem](https://github.com/CollectionFS/Meteor-CollectionFS/wiki/How-to:-Customize-the-folders-on-the-filesystem)

The trick is to attach the user identifier to the file object so you can access it within fileKeyMaker

**Comment by jchristman** [comment]
hmmm... Is there no way to access the userId from inside of the server function? It seems as though I could attach any userId that I could see and it would get uploaded to the wrong place... In other words, how do I verify that the attached userId belongs to the user uploading the document?

**Comment by rhyslbw** [comment]
On the client attach the userId like this:

    Template.myForm.events({
      'change .myFileInput': function(event, template) {
        FS.Utility.eachFile(event, function(file) {
          file.metadata.userId = Meteor.userId();
          Images.insert(file, function (err, fileObj) {
            // Inserted new doc with ID fileObj._id, and kicked off the data upload using HTTP
          });
        });
      }
    });

then within the FS.Store call you can use this to customise the file key, which is the directory path in the case of the Filesystem Storage Adaptor. There are a few existing threads that go over this in more detail, but this should give you a start. In the future it will be easier to define custom fileKeys, but it is possible to achieve right now with a few extra lines of code.

**Comment by jchristman** [comment]
gotcha. k
