### ISSUE TITLE
Restriction on Storage Adapter Names

### ISSUE THREAD

**Issue by jchristman** [CollectionFS/Meteor-CollectionFS#613]
As of right now, "namespacing" storage adapters with dots in the storageName breaks the system. Specifically, [this](https://github.com/CollectionFS/Meteor-CollectionFS/blob/783c9d37de38bead77d73f3701c7ed4adaee7f9d/packages/file/fsFile-common.js#L305) line causes anything with dots to be parsed into a multitiered structure which prevents retrieval of the file at a later time.

My proposal is this. Either:
 - Mention in the documentation that storage adapter names may not have dots. This would have saved me quite some time in debugging
 - Or, maybe auto-convert dots to something else (transparently behind the scenes) so that people can specify any name they want for a storage adapter.

I realize this is not terribly important, but I wanted to prevent someone else from banging their head against the wall for an hour...

Thanks for the awesome library and keep up the good work!

**Comment by aldeed** [comment]
PR #592 was merged recently. Is that good enough?

**Comment by jchristman** [comment]
Ah yes that would do the trick. Any idea when devel is going to be merged into master?
