### ISSUE TITLE
Please publish your package cfs:gridfs for Windows

### ISSUE THREAD

**Issue by stubailo** [CollectionFS/Meteor-CollectionFS#623]
Hi!

This package has binary dependencies, and we wanted to give you a heads up that Meteor 1.1, with support for Windows will be released in a few days.

Now is the time to publish your package for Windows!

It should be very straightforward -- we've added new build machines that run Windows that you can access with the `meteor admin get-machine` command. This is the same as you've done before for the other architectures we support.

For complete directions on how to publish your package for Windows, visit https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview

On behalf of the Meteor team,
@stubailo, @slava and @avital.

**Comment by raix** [comment]
@aldeed Have you tried this?

**Comment by aldeed** [comment]
No. It's on my list for today unless you did it.

**Comment by raix** [comment]
I'm out of time - planning next week :)

**Comment by aldeed** [comment]
This is done. Seemed to publish and build without errors, but I didn't test on Windows.

**Comment by stubailo** [comment]
@aldeed thanks! Hopefully people will submit bug reports if it doesn't work.

**Comment by Rebolon** [comment]
I tried on windows 8.1 and it works in standard way (meteor run) but it's failing when i try to run tests : 

    >meteor test-packages rebolon:watcher-provider-website --settings settings.dist.json
    [[[[[ Tests ]]]]]
    
    => Started proxy.
    => Started MongoDB.
    => Errors prevented startup:
    
       While checking for cfs:gridfs@0.0.0:
       error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

    => Your application has errors. Waiting for file change.

**Comment by stubailo** [comment]
You need to specify a version for gridfs in your package.js file.

**Comment by Rebolon** [comment]
It Works, i did nt know That de could set a package version in a package.js.
Thx

-----Message d'origine-----
De : "Sashko Stubailo" <notifications@github.com>
Envoyé : ‎26/‎07/‎2015 19:31
À : "CollectionFS/Meteor-CollectionFS" <Meteor-CollectionFS@noreply.github.com>
Cc : "Benjamin RICHARD" <benjamin-richard@orange.fr>
Objet : Re: [Meteor-CollectionFS] Please publish your package cfs:gridfs forWindows (#623)

You need to specify a version for gridfs in your package.js file.
