### ISSUE TITLE
FancyBox w/ CollectionFS

### ISSUE THREAD

**Issue by jhmacdon** [CollectionFS/Meteor-CollectionFS#625]
So when trying to use <code>this.url store='thumb'</code> and <code>this.url</code>, I wasn't able to get it to work with FancyBox. When you click on the thumb, it shows fancybox loading and then redirects to the href instead of displaying the image?

I tested this with normal images and everything seems to work well, just CollectionFS images cause this to happen. 

Oh, I should add that i am using GridFS, so I suppose this could be an Iron Router issue as well.

**Comment by slam310** [comment]
This note an Iron Router issue  and :
````html
... this.url store='your_thumb_name_store' ...
````
Is the right setting, but for making the #Fancybox#  works  , you may need to put this piece of code somewhere on your client folder to get it "rendered" correctly :
````javascript
Template.YourTemplateName.rendered = function() {
  $('a[rel=YourRelTagName]').fancybox({
/* some fancyBox options here */});
}
````
And in your template , your link should looks like this : 

````html
<a href="{{this.url store="your_file_name_store" auth=false}}" rel="YourRelTagName">
    <img src="{{this.url store='your_thumb_name_store'}}" />
</a>
````
BTW : You should have also correlty import all the *FancyBox* depencies library in the right , of course ^^

**Comment by jhmacdon** [comment]
Sorry, I actually found this same solution on another issue somewhere on github and was able to implement it, meant to close this.
