### ISSUE TITLE
416 (Requested Range Not Satisfiable)

### ISSUE THREAD

**Issue by fehlix** [CollectionFS/Meteor-CollectionFS#628]
Hi guys,

I am working on an Audio Player in Meteor which uses CFS for uploading audio and image of audio. I can get the image back from CFS very well but for the audio file, which is kinda big, i get back:

`GET urlhere 416 (Requested Range Not Satisfiable)`

My guess is that it doesn't work with big files. Any ideas?

**Comment by rhyslbw** [comment]
cfs is designed to handle large files. Did you get anywhere with this?

**Comment by fehlix** [comment]
Not really, I moved on doing the other parts of the application. 
Once I feel safe, I will come back to this and let you guys know what I have discovered.

**Comment by TeachMeFly** [comment]
I had same problem, for now, current master normally upload files. If you use nginx, you need change storage chunksize to 1Mb (nginx default).

**Comment by fehlix** [comment]
This was it. Thank you so much!
