### ISSUE TITLE
Getting a file that's already on mongodb's gridfs

### ISSUE THREAD

**Issue by simakwm** [CollectionFS/Meteor-CollectionFS#629]
Is there a way to fetch a file object from a gridfs that wasn't created by CollectionFS?

**Comment by rhyslbw** [comment]
Not sure, have you dug into the code at all? I'm not that familiar with GridFS, but if you can pull the binary data out, you can then you can add it back in as per normal. Was the gridfs collection created by cfs?

**Comment by simakwm** [comment]
No. The data was inserted by a nodejs script using gridfs-stream. 
The solution I found was to create a server-side function that uses cfs .insert method to save files while inside the Meteor app. This function is called at startup and periodically using percolate:synced-cron.

**Comment by rhyslbw** [comment]
Thanks for documenting your solution
