### ISSUE TITLE
An error occurred: Policy document must be version 2012-10-17 or greater.

### ISSUE THREAD

**Issue by vertangelx** [CollectionFS/Meteor-CollectionFS#630]
Following the readme for `cfs:s3`, I tried creating a new custom policy as shown below...

    {
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket"
          ],
          "Resource": "arn:aws:s3:::*"
        },
        {
          "Action": [
            "s3:PutObject",
            "s3:PutObjectAcl",
            "s3:GetObject",
            "s3:GetObjectAcl",
            "s3:DeleteObject",
            "s3:DeleteObjectAcl"
          ],
          "Effect": "Allow",
          "Resource": [
            "arn:aws:s3:::myBucketName/*"
          ]
        }
      ]
    }

but I get the error `An error occurred: Policy document must be version 2012-10-17 or greater.`. I'm new to AWS, how can we resolve the error?

**Comment by rhyslbw** [comment]
Where are you getting this error?

**Comment by cameroncruz** [comment]
You need to set the version, like the example below:
`{`
`  "Version": "2012-10-17",`
`  "Statement": [`
`    {`
`      "Effect": "Allow",`
`      "Action": "s3:ListAllMyBuckets",`
`      "Resource": "arn:aws:s3:::*"`
`    }, `

**Comment by cameroncruz** [comment]
@vertangelx adding the above will fix your issue.
