### ISSUE TITLE
Page tries to load image before finish uploading to S3

### ISSUE THREAD

**Issue by meteorjs3000** [CollectionFS/Meteor-CollectionFS#631]
When my image is uploaded to S3 using `cfs.s3` and I update a document to use the newly uploaded image, the current page will try to load the image from S3 before it has finished uploading to S3. This causes an error

    GET https://s3.amazonaws.com/bucketname/... 403 (Forbidden)

Is there a callback we can use that runs only after having successfully uploaded the file to S3?

**Comment by pburke** [comment]
Yes, you will want to use the `hasStored` method of the FS.File object. In a template, it looks like this:

    {{#if file.hasStored 'storeName'}} ... {{/if}}

There is also an `isUploaded` method, but I believe it returns true as soon as the file is uploaded to the temporary store, which is probably not what you want for S3.
