### ISSUE TITLE
ingesting images from directory

### ISSUE THREAD

**Issue by gebrits** [CollectionFS/Meteor-CollectionFS#634]
A separate process(outside of Meteor) is downloading images and saving to a local directory. 
I would like to import these images into Meteor's image pipeline. 

How would I go about this? Does Meteor have some standard image ingestion options for this?

**Comment by rhyslbw** [comment]
Check out https://github.com/CollectionFS/Meteor-CollectionFS/pull/617, which introduces a helper function that may be of use.
