### ISSUE TITLE
Upload from different apps and shared db

### ISSUE THREAD

**Issue by bitomule** [CollectionFS/Meteor-CollectionFS#635]
I've 2 different apps that share database, when I upload a file in one of those apps I get this error on the other one:

    Error: ENOENT, open '/home/action/workspace/myapp1/.meteor/local/cfs/files/_tempstore/files-0D6C3120-9BB6-4D5C-A255-CD928D64983C-0.chunk'

It's trying to upload the file I'm uploading from a different server.

Any idea on how can I make this work?

Thanks!

**Comment by bitomule** [comment]
No ideas? Any option of changing chunks collection name in different servers, maybe that fixes it.

**Comment by rhyslbw** [comment]
Have you tried defining a different tempstore for each of the apps?

**Comment by rhyslbw** [comment]
Also check this thread for more context

https://github.com/CollectionFS/Meteor-CollectionFS/issues/510

**Comment by bitomule** [comment]
How can I set different tempstores? I think the problem could be related to graphics magic.

**Comment by bitomule** [comment]
More info:

- It only seem to happen with files that should be chunked (> 2mb)
- It's related to the chunks collection in mongo, after upload document isn't removed
- It happens when the file upload has ended on the origin app

**Comment by rhyslbw** [comment]
It would be best to create a minimal repo to demonstrate the error

**Comment by bitomule** [comment]
Ok, here it is:

https://github.com/bitomule/CollectionFS-BugTest

You'll need:

- Amazon S3 keys or changing it to GridFS adapter
- Use shared mongodb (I've used sandbox from compose.io)
- 2 different copies of the app in 2 different folders

Then run both in different ports, upload in one and the other crashes.

Hope this can help finding the issue.

**Comment by for2ne** [comment]
I've seen this error when using the function transformWrite for incorrect images (text/plain instead of image/*)

**Comment by bitomule** [comment]
@for2ne no, that's not the problem. The problem it's trying to read the file from local storage but file isn't there in app2. It's only in app1.

**Comment by rhyslbw** [comment]
This needs the changes we are working on in https://github.com/CollectionFS/Meteor-CollectionFS/issues/214 to handle multiple instances sharing the same collection, as there are direct fsCollection observers in both apps and trying to run the same action.

Sorry but I don't see a way around this apart from hacking an interim solution, or maybe lookout in the linked thread for a dev branch to use (at your own risk).
