### ISSUE TITLE
CollectionFS For Windows

### ISSUE THREAD

**Issue by nspangler** [CollectionFS/Meteor-CollectionFS#636]
Since the recent https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows windows preview of meteor released, is their a plan to make collectionFS compatible with a meteor windows server? Or should it just naturally work?

**Comment by raix** [comment]
Should work, i think

**Comment by justindra** [comment]
I've just tried updating one of my projects to the windows supported meteor (1.1) and  there was a problem with ````cfs:gridfs````.

````
While checking for cfs:gridfs@0.0.31
error: No compatible binary build found  for this package.
````

**Comment by raix** [comment]
cfs:gridfs@0.0.33 is windows...

**Comment by rclai** [comment]
I tested with cfs:filesystem and it works.

```js
var fileStore = new FS.Store.FileSystem("fileStore", {
  path: "C:\\Users\\richardl\\Desktop\\myApp\\.fileStore"
});

Files = new FS.Collection('files', {
  stores: [fileStore]
});
```
