### ISSUE TITLE
503 on files after mongodump / mongorestore

### ISSUE THREAD

**Issue by clarkritchie** [CollectionFS/Meteor-CollectionFS#637]
I just did a simple ```mongodump``` / ```mongorestore``` from my hosting provider (MongoLab) to my localhost.   I see my CollectionFS collections in my local db (e.g. ```cfs.images.filerecord```, etc.) and I can see the individual documents for my images in the db when I browse the collection using Robomongo.

However, when I view my site the image links are broken and the Developer Tools reports 503:

```
:3000/cfs/files/images/aKCHNktZzeRqXYAvC/Helmet.jpg?token=eyJhdXRoVG9rZW4iO…QN1J0d0oyVWIzc0h4bFBSYWNGclgzVmQwMk03dlNTRkVyczhTMUZ0In0%3D&store=images:1 GET http://localhost:3000/cfs/files/images/aKCHNktZzeRqXYAvC/Helmet.jpg?token=e…EZQN1J0d0oyVWIzc0h4bFBSYWNGclgzVmQwMk03dlNTRkVyczhTMUZ0In0%3D&store=images 503 (Service Unavailable)
```

Any suggestion?  I need to migrate the db from our dev server to localhost for a demo.  Do I need to also tar up part of the server's filesystem ```/cfs/files``` and copy that locally?  I thought the db was sufficient.

**Comment by clarkritchie** [comment]
OK so I guess this is user error.  You have to copy the db _and_ the ```/cfs``` directory to migrate from A to B.  I thought images were stored in the db but apparently there is a filesystem component as well.

**Comment by raix** [comment]
If the filesystem storage adapter is used files are stored in filesystem, if you want pure db then look at the gridFS sa.
All files have a filerecord stored in a collection, keeping track of Security and file Info.

**Comment by raix** [comment]
Theres also a s3 sa
