### ISSUE TITLE
cfs:filesystem uploads only 1mb below size of files

### ISSUE THREAD

**Issue by zevsuld** [CollectionFS/Meteor-CollectionFS#639]
Is there any limit in cfs:filesystem upload size?  I am able to upload only 1mb below size files

**Comment by aldeed** [comment]
You might be running into the lack of support for partial downloads in that package. It's a known issue.

**Comment by zevsuld** [comment]
@aldeed yes you are right, I had partial download issue. So I disabled partial response in by nginx reverse proxy server.
