### ISSUE TITLE
how to access metadata from FS collections

### ISSUE THREAD

**Issue by michelkeyaerts** [CollectionFS/Meteor-CollectionFS#640]
How to access metadata from FS collections?
In the template gallery events, I've inserted images in FS collection with metadata:
<code> file.metadata = {owner: Meteor.user()._id,gallery:galleryId};</code>

In order to retrieve images corresponding to galleries created by the user, I tried this code in the template gallery helper : 
<code>     var result = Images.find({"metadata.gallery":currentGalleryId})</code>
where currentGalleryId is given through Session.get
It doesn't work. I also tried differents codes for hours, unsuccessfully.
I suppose it must be quite simple.  Anyway, I don't know.

**Comment by nooitaf** [comment]
`````javascript
Images.find({"metadata.gallery":currentGalleryId})
`````
That is the correct way. It will give you a cursor to those files

If you want an array...
`````javascript
Images.find({"metadata.gallery":currentGalleryId}.fetch()
`````

You can check in the browser console for one image with `Images.findOne();` and see if it has the proper properties. Copy the owner or galleryId and test `Images.find({"metadata.gallery":__a_galleryid_u_know_is_there}).fetch()` in the browser console. It should give you an array of at least the one you found with `findOne` 

Also make sure you publish and allow the collection if you removed `insecure,autopublish`

**Comment by michelkeyaerts** [comment]
Than for your help. It doesn't works yet.
I tried
<code>Images.find({'metadata.gallery':"pw44DrT79kF2q88aE"})</code>
it returns:
<code>Object { collection: Object, sorter: null, _selectorId: undefined, matcher: Object, skip: undefined, limit: undefined, fields: undefined, _projectionFn: LocalCollection._compileProjection/<(), _transform: LocalCollection.wrapTransform/wrapped(), reactive: true }</code>
with fetch():
<code>Images.find({'metadata.gallery':"pw44DrT79kF2q88aE"}).fetch()
</code>
returns an empty array 

<code>Array [  ]</code>


<code> console.log(currentGalleryId)</code>
 return "pw44DrT79kF2q88aE"


Or simply

<code>img=Images.findOne()</code>
==>
<code>Object { createdByTransform: true, _id: "LQRWShp8KZrKWc7sp", original: Object, uploadedAt: Date 2015-04-03T10:08:15.254Z, copies: Object, collectionName: "images" }</code>
And

<code>img.metadata</code>
==> <code>undefined</code>


server side:

<code> Meteor.publish("Images", function () {
    return Images.find({});
  });
</code>



insecure  is not removed. I don't understand.

**Comment by nooitaf** [comment]
Looks like your metadata doesn't get added to your image. It should show up in `findOne`.

You insert should look something like this..
`````html
<input name="files" id="files" type="file" class="fileUploader" multiple>
`````
`````javascript
  'change .fileUploader': function(e, t) {
    var galleryId = __yourgalleryid__;
    FS.Utility.eachFile(e, function(file) {
      var fileObj = new FS.File(file);
      fileObj.metadata = { owner: Meteor.userId(), galleryId:galleryId };
      Images.insert(fileObj);
    });
  },

`````

**Comment by michelkeyaerts** [comment]
Many thanks. It works now.
It missed this line <code>var fileObj = new FS.File(file);</code>
I was supposing that insert function created the fileObject from the file parameter.
That was my mistake.
Thank you again,

M.

**Comment by nooitaf** [comment]
glad to help :)

**Comment by digz6666** [comment]
How can I access metadata from meteor template?

**Comment by michelkeyaerts** [comment]
For instance:
in gallery.js
```
Template.gallery.helpers({
    images: function () {
        var result = Images.find({});
        return result;
    }
})
```
Somewhere in gallery.html template
```
{{#each images}}
<p>{{metadata.somethingInMetadata}}</p>
{{/each}}
```
