### ISSUE TITLE
cfs:gridfs is not support on windows.

### ISSUE THREAD

**Issue by phirum** [CollectionFS/Meteor-CollectionFS#645]
It seems like cfs:gridfs is not supported on windows.
I tried to install cfs:gridfs package on windows, but it's not working.
Did cfs:gridfs package support on windows or not?

**Comment by raix** [comment]
you should use the latest version

**Comment by phirum** [comment]
OK thank you, I will update it and try it again.

**Comment by raix** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/issues/636
