### ISSUE TITLE
How remove chunks if the download was interrupted?

### ISSUE THREAD

**Issue by for2ne** [CollectionFS/Meteor-CollectionFS#646]
My users upload pictures of large size. If they do not wait for the download is complete, then we get a useless file. How to remove them, if the download was interrupted?

```
images.forEach(function(image) {
              if (image.chunkCount) {
               // Like this?
              }
          });
```

**Comment by rhyslbw** [comment]
Check this https://github.com/CollectionFS/Meteor-CollectionFS/issues/415
