### ISSUE TITLE
Chunk Does not exist error

### ISSUE THREAD

**Issue by SauronTheGreat** [CollectionFS/Meteor-CollectionFS#656]
Hi, 
 I am facing a very weird issue while using gridFS.
I am trying to insert a file from my local file system on the server.
Here is the code:
   ```
        imgAsset = new FS.File(basePath+"/"+r['img'])
        imgAsset.owner = uid
        imgAsset.stored = false
        ia = assetFiles.insert(imgAsset)      
``` 
I also have a listener on the collection on 'stored' event for some processing:
```
@assetFiles.on('stored', (fileObj, storeName) ->
  if storeName is 'assetFiles'
    Fiber = Npm.require('fibers');
    Future = Npm.require('fibers/future');
    future = new Future();
    Fiber(()->
        assetFiles.update({_id:fileObj._id},{$set:{stored:true}})
    ).run()

)
```       

This works perfectly but sometimes when I run this function, I get an error saying:
xxxxxxx : does not exists

This is a chunk issue I know very similar to https://github.com/CollectionFS/Meteor-CollectionFS/issues/310

I am not sure what is causing the issue and how to go about resolving it.
Any help is really appreciated.

Here is my store definition:
```
imageStore = new FS.Store.GridFS("assetFiles",
  # transformWrite: (fileObj, readStream, writeStream) ->
  #   readStream.pipe writeStream
  #   console.log Imagemagick.identify({data:readStream});

#  mongoUrl: "mongodb://127.0.0.1:27017/test/" # optional, defaults to Meteor's local MongoDB
#  transformWrite: myTransformWriteFunction #optional
#  transformRead: myTransformReadFunction #optional
#  maxTries: 1 # optional, default 5
  chunkSize: 1024 * 1024*3 # optional, default GridFS chunk size in bytes (can be overridden per file).
)


@assetFiles = new FS.Collection("assetFiles",
  stores:[
    imageStore
  ]
)
```

The worrying part is the error does not happen always but only sometimes.
Thanks.

**Comment by geekrohit** [comment]
Facing same issue here. Running meteor 1.1.0.2 in deployment. Mongo is running fine, no errors or crashes. But the app crashes upon having that error.

**Comment by rhyslbw** [comment]
Do you have more than one app instance running?
