### ISSUE TITLE
Can't upload to S3

### ISSUE THREAD

**Issue by 255kb** [CollectionFS/Meteor-CollectionFS#662]
Hi, 

I am trying to upload files to S3 using this package and `cfs:s3` but it does not work. I haven't find any similar opened issue. 

When I start uploading, the image is added to the collection and I immediately get a warning concerning the Xhr object (cfs_upload-http.js:137):

```
FS.File {createdByTransform: false, original: Object, data: DataMan, collectionName: "images", _id: "G5ogkZkcsGPzDhnx2"…}
Warning: The provided value 'undefined' is not a valid enum value of interface XMLHttpRequestResponseType. cfs_upload-http.js?cf37b2941c8cdbfd85cdc3948f57fed4bb429081:137 
```

Then after a while (some minutes), I got several errors:
```
PUT http://localhost:3000/cfs/files/....   net::ERR_CONNECTION_RESET
Error: "Queue" network [undefined], Error: network [undefined]
[...]
```

Please find the screenshot below: 

![issue](https://cloud.githubusercontent.com/assets/7489814/7292303/1a08f93c-e99b-11e4-9a76-21523221bb7f.png)

I know this is not a credential problem as I can upload to S3 using other packages like Slingshot.
I also followed the documentation of both packages (CollectionFS and CFS-S3) and I am using the exact same code. I can also make CFS work perfectly with filesystem.

Any idea?

**Comment by aldeed** [comment]
Do you get any errors or warning on the app server? Did you do `FS.debug = true` to get extra logging? Also post your S3 store definition code, minus private credentials.

**Comment by 255kb** [comment]
OK, my bad, did not see that I had to add either filesystem or gridfs as a temporary storage... (`FS.debug = true` helped a lot ;))
Thanks for your time

**Comment by steve-ross** [comment]
Just ran into this and here was my dumb mistake:

Make sure you are subscribing to your images collection wherever you have your file upload. In my case I saw this error when I forgot to subscribe on my 'new' route. Setting debug mode on startup helped me to determine that the files were in fact getting to the server.
