### ISSUE TITLE
userId set to false in allow methods

### ISSUE THREAD

**Issue by YuukanOO** [CollectionFS/Meteor-CollectionFS#665]
When porting an application to the newer version of meteor and cfs, the userId in the allow insert/update is initialy correct and in subsequent calls (made by the chunk upload I guess) is set to false.

**Model definition**
```javascript
DocumentsData = new FS.Collection('documents_data', {
  stores: [new FS.Store.FileSystem('documents_data', { path: '~/apteor_files' })]
});

DocumentsData.allow({
  insert: function(uid, doc) {
    console.log('insert', uid);
    return canUpload(uid, doc.cat_id);
  },
  update: function(uid, doc) {
    console.log('update', uid);
    return canUpload(uid, doc.cat_id);
  }
});
```

**Client side**
```javascript
var files = tpl.find('[type=file]').files;
_.each(files, function(file_input) {
    var file = new FS.File(file_input);

    // Assign the category id
    file.cat_id = category_id;

    // Insert the file
    DocumentsData.insert(file, function(err, f) {
      // (...) Internal stuff
    });
});
```

In the server console, when uploading a single file, I got
```console
I20150424-13:19:02.769(2)? insert K9RdxmLhY7fyZC8zP
I20150424-13:19:02.794(2)? update K9RdxmLhY7fyZC8zP
I20150424-13:19:03.167(2)? insert false
```

**Comment by gibex** [comment]
Same issue when using gridFS, userId is always FALSE in download method. Any solution to this?

var pdfStore = new FS.Store.GridFS("pdfs");

Pdfs = new FS.Collection("pdfs", {
	stores: [pdfStore]
});

Pdfs.deny({
	 insert: function(){
	 	return false;
	 },
	 update: function(){
	 	return false;
	 },
	 remove: function(){
	 	return false;
	 },
	 download: function(){
	 	return false;
	 }
 });

Pdfs.allow({
	 insert: function(){
	 	return true;
	 },
	 update: function(){
	 	return false;
	 },
	 remove: function(){
	 	return false;
	 },
	 download: function(userId){
	 	return true;
	 	// if (userId) {
	 	// 	return true;
	 	// } else {
	 	// 	return false;
	 	// }
	 }
});

**Comment by YuukanOO** [comment]
Found why!

Since I depends on cfs in my own package, I add to imply the use of `accounts-password` like so:

```javascript
api.imply('accounts-password');
```

If you want to know why, it's because `upload-http` uses the auth token via `Accounts._storedLoginToken()` without requiring the `accounts-base` package (see https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/upload-http/upload-http-client.js#L195)

**Comment by shividhar** [comment]
+1. I get this error as well.

**Comment by petermikitsh** [comment]
+1 This is definitely a gotcha.

**Comment by YuHuaiChen** [comment]
Hi @YuukanOO, which `package.js` file did you add the `api.imply`?

Is it your own package's package.js? or did you fork some parts of cfs and added that in `standard-packages`? or `upload-http`?

Please help! I can't get the allow/deny to work...uid passed in just always be false

Great thanks to any help!!

**Comment by pl7y** [comment]
Hi @YuukanOO , I'm in the same boat as @YuHuaiChen .
Can you tell us where in code you had to use `api.imply('accounts-password');`?
At the moment I am developing a small meteor app (so I'm not creating any package) using `cfs` and I'm getting always a bad userId on 'download' action only. Where should I put this api.imply?

Thank  you very much in advance.

**Comment by YuukanOO** [comment]
@YuHuaiChen Sorry! Didn't see your message sooner. @pl7y I've added the `api.imply` in my package wich is using the `Meteor-CollectionFS` package. Does it solve your issue?

**Comment by pl7y** [comment]
Hi, what I really don't get (being new to Meteor) is what I should do when I'm NOT creating a package. In my case, I have just a simple app which uses gridFS for storing files. So, in this case, I don't have my own package.js. Is there somewhere else I should place the`imply` into?

Anyway, really thanks for getting back to me, very appreciated!

**Comment by YuukanOO** [comment]
@pl7y Not AFAIK. When not using a package, it should don't cause any problem =/
