### ISSUE TITLE
Is it possible to add a Dropbox adapter?

### ISSUE THREAD

**Issue by Praxie** [CollectionFS/Meteor-CollectionFS#672]
Hello. I'm working on the server-side dropbox uploading. So I need to send file to the server by chunks and upload these chunks to Dropbox at the same time.
Thanks.

**Comment by raix** [comment]
Thats the idea - to be able to have storage adapters for google/dropbox etc. We aren't there yet still need to get cfs test covered.
That said - if you are up to it - you should be able to create a storage adapter using the storage adapter package - have a look at the filesystem/gridfs/s3 storage adapters for inspiration - and ask us questions.

**Comment by Praxie** [comment]
@raix, thanks. I may need your help. 
Not sure how to integrate [these methods](http://coffeedoc.info/github/dropbox/dropbox-js/master/classes/Dropbox/Client.html#resumableUploadStep-instance)

**Comment by raix** [comment]
The storage adapter only requires a createReadStream, createWriteStream, remove and stats.
https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/filesystem/filesystem.server.js

But dropbox may have more in common with the s3 SA https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/s3/s3.server.js

Actual read/write implementation https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/s3/s3.upload.stream2.js

**Comment by Praxie** [comment]
@raix, ok. I kind of made it work...

**Comment by rhyslbw** [comment]
@Praxie If you have an MVP ready, fork the CollectionFS repo, create a feature branch with your new package and submit a PR against devel. Would be good to see a Dropbox Storage Adaptor maintained in the repo, and will likely see collaboration from other people needing the functionality.

**Comment by Praxie** [comment]
@rhyslbw, ok, I'll do it tomorrow.
though I have a little problem with file reading. Dropbox-api has no createReadStream method to return the Stream.

**Comment by raix** [comment]
@Praxie read up on streams https://nodejs.org/api/stream.html - you will see that it's a similar way XHR works (doesn't match 1:1 though)

You can create a readstream and have the xhr just add data to it or trigger errors.

**Comment by Praxie** [comment]
@raix, @rhyslbw, here is the dropbox branch: https://github.com/meteor-magic/Meteor-CollectionFS/tree/dropbox

**Comment by rhyslbw** [comment]
@Praxie Nice work! PR against devel so we can test it as part of the next merge :-)

**Comment by Praxie** [comment]
@rhyslbw https://github.com/CollectionFS/Meteor-CollectionFS/pull/675

**Comment by Praxie** [comment]
Forgot about readme... I can add it later though.
```js
var dropboxStore = new FS.Store.S3("files", {
  key: "dropboxAppSecret",
  secret: "dropboxAppSecret",
  token: "dropboxAccessToken",
  folder: "folder", //optional, which folder (key prefix) to use 
  // The rest are generic store options supported by all storage adapters
  transformWrite: myTransformWriteFunction, //optional
  transformRead: myTransformReadFunction, //optional
  maxTries: 1 //optional, default 5
});
```

**Comment by raix** [comment]
@Praxie  Its not merged yet so you can still make it :)

**Comment by migloo** [comment]
Guys, the command "meteor add cfs:dropbox" does not work. It returns an "error: no such package". Any idea why?

**Comment by rhyslbw** [comment]
@migloo It's unreleased at this point, but has been merged to devel. You can run it locally though

**Comment by migloo** [comment]
OK will do, thanks.

**Comment by Praxie** [comment]
@rhyslbw, it's merged with master branch but is not deployed on atmosphere yet.

**Comment by raix** [comment]
@rhyslbw whats your meteor account name?

**Comment by rhyslbw** [comment]
@raix `rhyslbw` there too

**Comment by rhyslbw** [comment]
@Praxie @migloo  ah sorry, I was answering that on my phone and didn't see https://github.com/CollectionFS/Meteor-CollectionFS/pull/677 before hand

**Comment by raix** [comment]
@rhyslbw I've added you to the `cfs:` org allowing publishing packages.

**Comment by rhyslbw** [comment]
Thanks @raix

**Comment by rhyslbw** [comment]
@raix or @aldeed can you jump on Gitter and hit me up? I'm having trouble publishing the dropbox package, and have a question re windows arch build
