### ISSUE TITLE
Uploading Images/Files using POST URL

### ISSUE THREAD

**Issue by kshitizrimal** [CollectionFS/Meteor-CollectionFS#674]
Hi, I am getting started using this package and I saw image upload only via event change on your getting started guide . I am using various other libraries and tools such as Redactor WYSWYG Editor which uses  POST url to upload files. I was wondering how do you upload files for such using Collection FS and what should be passed on 'event' and 'file' arguments for such uses. Thank you

**Comment by TeachMeFly** [comment]
Hi @kshitizrimal, unfortunately cfs-access-point dont support post request (https://github.com/CollectionFS/Meteor-CollectionFS/blob/devel/packages/access-point/access-point-server.js#L136), you need to use PUT requests. Anyway, it will be better to extend your editor for upload files, using native cfs methods.
