### ISSUE TITLE
How to add custom metadata to a DataURL string before inserting

### ISSUE THREAD

**Issue by xois** [CollectionFS/Meteor-CollectionFS#680]
I'm inserting a Data URL string into CollectionFS, and would like to add some metadata such as userId to  FS.File, how can I do that?

**Comment by rhyslbw** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/wiki/Insert-One-File-From-a-Remote-URL

**Comment by xois** [comment]
I mean [this Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs)
