### ISSUE TITLE
Possible to store into specified store

### ISSUE THREAD

**Issue by Danilo-dk** [CollectionFS/Meteor-CollectionFS#694]
Hello,

Instead of using graphicsmagick I wanted to resize my image on the client and upload it myself. However, AFAIK this would require a whole seperate collection for these thumbnails. Is it instead possible to specify in which store files are uploaded? This way I could upload the original to one store, then resize it and upload it to another store.

Thanks

**Comment by nooitaf** [comment]
If the client does the image resizing you could just do 2 uploads to indeed 2 different collections. Each collection has its own set of stores.

**Comment by Danilo-dk** [comment]
I would rather have both the full sized image and the thumbnail in the same collection record if that is possible. Just like when you make a second store for a collection and have the server resize it before storing it.

**Comment by nooitaf** [comment]
As a workaround you could first upload the large file, wait for the inserted _id, add that to the 2nd upload (thumb) as metadata. Or the other way around.
