### ISSUE TITLE
Any way to set server URL?

### ISSUE THREAD

**Issue by jimmiebtlr** [CollectionFS/Meteor-CollectionFS#699]
setBaseUrl is close to what I need, but the root url that CFS uses cannot be changed.

Basically, I have a mobile application that I have using the DDP of another application.

**Comment by rhyslbw** [comment]
Related to #682 ?

**Comment by jimmiebtlr** [comment]
Possibly, I originally noticed this on upload though.  The actual mongo record for the image is created, the image just never get's uploaded to the correct server.

**Comment by jimmiebtlr** [comment]
Actually, it probably is the same.  I get the actual record, but not the chunk data never even arrives on server.  So the behavior I'm seeing is a bit different from his.

**Comment by jimmiebtlr** [comment]
Also, the way I'm doing DDP already covers cfs's DDP.  It's the http upload request in access point that I'm not seeing a way to change.  I'll probably be submitting a pull request in the next week to allow setting it.  

Any recommendations, or preferences on allowing setting the upload url?

**Comment by rhyslbw** [comment]
Great stuff, just keep #682 in mind as they are indirectly related. I've not had too much to do with this part of the system, but if you get a PR in I can review

**Comment by jimmiebtlr** [comment]
I have my version working to set the client side code to hit the right endpoint on the other server, I'm running into CORS restriction.  Do you know where in CFS I would add another allowed domain?

**Comment by rhyslbw** [comment]
@raix or @aldeed Can you assist with this? @jimmiebtlr is working on a solution to being able to uploading to a different Meteor server (via http)

**Comment by jimmiebtlr** [comment]
It looks like issue #558 is my most recent problem.

**Comment by rhyslbw** [comment]
Great, looks like there's might be some progress over there. Will close this now

**Comment by jimmiebtlr** [comment]
For anyone else considering this route, I decided to go with 2 complete servers.  Consider this route, as you'll need the server for the code hot-reload anyway.  Which remove's the need for this issue.
