### ISSUE TITLE
Insert data to Collection

### ISSUE THREAD

**Issue by YouSour** [CollectionFS/Meteor-CollectionFS#700]
hi , i'm new here , i'm using cfs:filesystem
cfs:standard-packages on upload image , everything work fine but i don't know how to insert data to collection by myself , it's alway insert data automatically ! 

example : Collection 
{
    "_id" : "YsWDohDkjEPZ2a6p6", // _id here i need generate to 001 
    "userId": "0001" //  here i want to insert new filed userId to collection
    "original" : {
        "name" : "100APPLE_IMG_0167.JPG",
        "updatedAt" : ISODate("2013-01-07T14:54:13.000Z"),
        "size" : 368287,
        "type" : "image/jpeg"
    },
    "uploadedAt" : ISODate("2015-06-04T17:39:15.964Z"),
    "copies" : {
        "yourFileCollection" : {
            "name" : "100APPLE_IMG_0167.JPG",
            "type" : "image/jpeg",
            "size" : 368287,
            "key" : "yourFileCollection-YsWDohDkjEPZ2a6p6-100APPLE_IMG_0167.JPG",
            "updatedAt" : ISODate("2015-06-04T17:39:15.000Z"),
            "createdAt" : ISODate("2015-06-04T17:39:15.000Z")
        }
    }
}

i hope you reply soon as possible , thank you for advance !

**Comment by rhyslbw** [comment]
Check this out for adding data. https://github.com/CollectionFS/Meteor-CollectionFS/wiki/How-to%3A-Add-custom-metadata-to-a-file-before-inserting

Why are you wanting sequential IDs?

**Comment by YouSour** [comment]
thank you , @rhyslbw , now i can insert data to collection by myself now , and reason why i wanting sequential Id is easy than original id generate (example: YsWDohDkjEPZ2a6p6) , second reason the project i working need to generate id  (YsWDohDkjEPZ2a6p6)  to (001) . so do you have any idea about this ? :smile:

**Comment by rhyslbw** [comment]
You could store a reference to the sequential ID and treat the Mongo format ID as the application's internal reference?

**Comment by YouSour** [comment]
can you give any example ? sorry for that , i'm a little confusing here . :disappointed:

**Comment by rhyslbw** [comment]
It's going to depend on the scenario, but rather trying to customise the `_id` property of the FS.File, you could store a reference to the 'global' ID just like you are with `userId`

**Comment by YouSour** [comment]
so that mean i can't customise the _id that Fs.File generate :question:

**Comment by rhyslbw** [comment]
No. It's a standard [Mongo.Collection](https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/collection/common.js#L112) so I'm going to close this now as it's out of the package's scope

**Comment by YouSour** [comment]
ok , thank you for help ! :smiley:

**Comment by rhyslbw** [comment]
Hey just wanted to follow up on this as I can see my advise not totally correct about setting the id. You can set the ID given you have a way to ensure it's uniqueness. I'm actually now passing in a GUID that I generate with a function, which is much better than sequential. Are you needing to call an external service with the ID of the file? If so, can you not just use the return value from the insert?
