### ISSUE TITLE
upload file when click on input type submit

### ISSUE THREAD

**Issue by YouSour** [CollectionFS/Meteor-CollectionFS#701]
hi , i just found demo of upload file , i don't want upload file when click on Browse , what i want upload file when click on submit !
here link Demo of upload file : 
http://meteorpad.com/pad/HWZzeaRbWggY7Z72G/Leaderboard
thank you for advance .

**Comment by rhyslbw** [comment]
That demo is inserting on the jQuery change event. You just need to rework it so it's triggered from the submit

**Comment by YouSour** [comment]
could you correct it for me ?

**Comment by rhyslbw** [comment]
Sorry I'm stretched pretty thin across many projects right now so don't have time. Given this is not an issue with cfs I'll have to close it. Good luck!

**Comment by nooitaf** [comment]
@YouSour i changed your demo to trigger on submit. 
http://meteorpad.com/pad/zzpdePANFghRbGGmD/File%20Upload%20with%20Submit

**Comment by YouSour** [comment]
ok , thank you every much , @nooitaf & @rhyslbw for help ! :smile:
