### ISSUE TITLE
How to add custom fields to collections?

### ISSUE THREAD

**Issue by meShubham99** [CollectionFS/Meteor-CollectionFS#704]
I need to add a field named "category" which defines the document in the collection. Any way to do that. Something like this (Just to avoid any kind of confusions here)
**{
	"_id" : "PqCPEWCp6otXhxANS",
        ...
        "category" : "Funny things"
        ...
	"uploadedAt" : ISODate("2015-06-08T05:12:29.945Z")
}**

**Comment by rhyslbw** [comment]
See here: https://github.com/CollectionFS/Meteor-CollectionFS/wiki/How-to%3A-Add-custom-metadata-to-a-file-before-inserting
