### ISSUE TITLE
Guide for uploading image in an Meteor ios app

### ISSUE THREAD

**Issue by xiaopow** [CollectionFS/Meteor-CollectionFS#706]
Hi, am building an app using the meteor ios platform. After following the guide by Victor Leung, image upload works fine when loading the app with chrome browser in iphone5s. But image upload doesn't work in native app. after following the guide by Victor Leung.

**Comment by rhyslbw** [comment]
@bitomule are you able to assist?

**Comment by bitomule** [comment]
@xiaopow I'm uploading files from iOS app and I'm using a iron router server side route (99% like node) and native iOS upload using stream. It works pretty well.

**Comment by xiaopow** [comment]
Okay thanks, i will take a look into that. @bitomule
