### ISSUE TITLE
How to add relaton of postId to uploaded file

### ISSUE THREAD

**Issue by surfer77** [CollectionFS/Meteor-CollectionFS#708]
Hi,

I am trying to find a way to attach the postId to the uploaded file (a video) so then each video will belong to his specific post..  I am using CollectionFS and the amazon s3 package, the upload and preview all works well but can't make the relation between the post and video.

Really appreciate any help

**Comment by nooitaf** [comment]
You could add a property to the fileObj on upload..
`````javascript
  var fileObj = new FS.File(file);
  fileObj.userId = {userId: "1234"};
  Images.insert(fileObj,...);
`````
This meteor pad example makes use of it 
http://meteorpad.com/pad/zzpdePANFghRbGGmD/File%20Upload%20with%20Submit
