### ISSUE TITLE
S3 error

### ISSUE THREAD

**Issue by Ethaan** [CollectionFS/Meteor-CollectionFS#710]
Hi

I just added the ```cfs:standar packages``` and the ```s3 adapter```

But i got this error, wich is pretty clear.

```javascript
Error: "Queue" failed [503] Error in method "/cfs/files/:value/:value/", Error: Error: FS.TempStore.Storage is not set: Install cfs:filesystem or cfs:gridfs or set it manually     at mount... [undefined], Error: failed [503] Error in method "/cfs/files/:value/:value/", Error: Error: FS.TempStore.Storage is not set: Install cfs:filesystem or cfs:gridfs or set it manually     at mount... [undefined]
    at upload-http-client.js:33
    at http-call-client.js:69
    at _.once (underscore.js:750)
    at XMLHttpRequest.xhr.onreadystatechange (http-call-client.js:192)
```

s3 package will keep complaining about this ```TempStore``` until i install the ```gridfs``` or ```filesystem``` package? or im missing something else?

**Comment by rhyslbw** [comment]
Yes right now it's expecting one of those Storage Adaptors to be installed, although you can set it to use S3

**Comment by Ethaan** [comment]
how can i set it to use s3? i mean i have already isntalled the package

**Comment by rhyslbw** [comment]
Define it early in the loading cycle on the server like this (untested): 
````
FS.TempStore.Storage = new FS.Store.S3('_tempstore', {
  internal: true,
  path : '_tempstore'
});
''''
