### ISSUE TITLE
.url() returns null

### ISSUE THREAD

**Issue by heron88** [CollectionFS/Meteor-CollectionFS#728]
I am trying to upload files to my website and then display them by looping through the collection and accessing each object by its url. This works fine locally but after deploying it does not. Here is some of my code: 

```
Uploads = new FS.Collection('uploads',
{stores: [new FS.Store.FileSystem('uploads')]
});
```

```
'change .myFileInput':function(evt,tmpl){
 FS.Utility.eachFile(evt,function(file){
  theFile = new FS.File(file);
  .......
  Uploads.insert(theFile);
  .......
  })
  }
```

When running this locally on localhost:3000, if I run Uploads.find().fetch(); in the console, I get a list of FS.Files. After deploying, however, the same function returns a list of t.Files. Running Uploads.findOne().url(); locally on the console returns a url like
```
"/cfs/files/uploads/(_id)/(name)/?token=XXXXX"
```

When running the same function on a deployed version however, the console returns null. 

Any ideas why this is happening?

**Comment by heron88** [comment]
For those that may be curious, this was an issue with uploading two files simultaneously to the same collection. Waiting for one file to upload before starting the subsequent upload solved this issue for me.

**Comment by digelim** [comment]
I have the same problem, still not working :

`clientFile.find(fileId).url();
`
_VM5308:1 Uncaught TypeError: clientFile.find(...).url is not a function(…)_

Help anyone?
