### ISSUE TITLE
cfs-upload-http undefined error

### ISSUE THREAD

**Issue by reduxdj** [CollectionFS/Meteor-CollectionFS#741]
![screen shot 2015-07-11 at 5 30 44 pm](https://cloud.githubusercontent.com/assets/322547/8635861/dde4fe24-27f2-11e5-8d46-18ac904cf70a.png)

**Comment by reduxdj** [comment]
cfs_upload-http.js:137 The provided value 'undefined' is not a valid enum value of interface XMLHttpRequestResponseType.
http-call-client.js:101 The provided value 'undefined' is not a valid enum value of interface XMLHttpRequestResponseType.

**Comment by jganz** [comment]
duplicate
https://github.com/CollectionFS/Meteor-CollectionFS/issues/688
