### ISSUE TITLE
Thousands of /cfs/servertime calls interrupted by client

### ISSUE THREAD

**Issue by Alveoli** [CollectionFS/Meteor-CollectionFS#750]
I'm getting bombarded with "client request interrupted" warnings (it's an error code `H27` on Heroku, HTTP status code 499 "closed by client while the server is still processing its request, making server unable to send a status code back") on my server - one warning every 1-2 seconds for each client experiencing this issue.  Typically it occurs for up to an hour at a time per client, so I am getting thousands of these things.

The call that is causing this problem is `method=GET path="/cfs/servertime"`

It is always preceded by one or a few socks calls e.g. `method=GET path="/sockjs/info?cb=j3e3_z7aeu"` calls which usually return fine (status code 200), although sometimes the socks call also returns error 499.

My hunch is that the client would be experiencing some sort of CFS issue at startup, stalled, is never really able to access the CFS collections and just left the app trying again and again. Code it be related to hot code push...?

Anybody else experienced the same issue?

Ideas on how to investigate further?

**Comment by Alveoli** [comment]
I should add I'm using gridfs.

**Comment by travisdahl** [comment]
I am experiencing something similar when I deploy to Heroku. Mine is on the server side `"Server Request Interrupted"`.

I get a `NoSuchKey` error when I log the `readStream.on 'error'`. I was up all night trying to figure it out. It worked on meteor servers and locally, but not on heroku for some reason. Did you ever figure it out @Alveoli ?

**Comment by Alveoli** [comment]
Hi @travisdahl it's been such a long time, I've upgraded to Meteor 1.2 and rewritten that part of the code a few times.  The error came out of the wash... so all I offer you is the assurance that there's light at the end of the tunnel ;)
