### ISSUE TITLE
Client Side Insert valid callback 

### ISSUE THREAD

**Issue by daslicht** [CollectionFS/Meteor-CollectionFS#756]
Hello,
the documentation suggest to do an Image Insert on the client side.
https://github.com/CollectionFS/Meteor-CollectionFS#using-insert-properly
However the insert callback is called even tho the returned fileObj.url() is undefined.

Is there another callback which ensures that the fileObj.url() is valid?

**Comment by Zodiase** [comment]
url should not be used when the file's upload state is not determined.
Use a subscription with an id to subscribe to the uploading file and display it's url when uploaded.
For example:
```
{{#with uploadingFile}}
  {{#if this.isUploaded}}
    {{this.url}}
  {{/if}}
{{/with}}
```

**Comment by daslicht** [comment]
Thank you that sounds great! I will try it !

**Comment by daslicht** [comment]
I found a solution based on this post:
https://github.com/CollectionFS/Meteor-CollectionFS/issues/489
```
	Template.blogList.rendered = function() {
		var template = this;
		$('#summernote').summernote({
		    height: 400,
		    maxHeight:800,
		    minHeight:250,
		    onImageUpload: function(files, editor, $editable) {

		    	Images.insert(files[0], function (err, fileObj) {
					console.log("after insert:", fileObj._id);
					template.autorun(function (c) {
			          fileObj = Images.findOne(fileObj._id);
			          var url = fileObj.url();
			          if (url) {
			          	$("#summernote").summernote("insertImage", fileObj.url(), "Image Title"); 
			            //editor.insertImage($editable, url);
			            c.stop();
			          }
			        });
				});
		  
		  	}	
		});
	}
```

**Comment by daslicht** [comment]
@Zodiase  Is there a better way ? or is it what you would also suggest ?

**Comment by Zodiase** [comment]
Well, try not to use call autorun in an even handler because it will get registered many times... (Maybe there is a mechanism against multiple-registration but I'm not sure)

I think the better way to do is, say you have a upload page/template and assuming you are uploading one file at a time (the upload manager is half broken at the moment anyway). Have a template helper for the uploading file. Something like:
```CoffeeScript
template.helpers
	uploadingFile: () ->
		docs = Files.find(_id: Session.get 'uploadingFileId')
		return if docs.count() > 0
			docs.fetch()[0]
		else
			null
```
Then just use that helper in the template. When a new file is uploading, update the Session variable `uploadingFileId` and the template gets updated.

**Comment by Zodiase** [comment]
If you'd like to let your code receive the url, after the file is inserted (in the callback), create a cursor for it, and then use `cursor.observe` to detect changes and watch for `file.isUploaded`. It's cleaner than using autorun. Don't forget to stop the observer when you are done with it.

**Comment by daslicht** [comment]
Thank you I will try it !
My current quest is to be able to save additional data with teh image, eg simple properties like : isPublic, or isTrash etc

What is the correct place to read about using GridFS in Conjunction with CollectionFS. 
I havent found any good documentation about this combination, please.

**Comment by Zodiase** [comment]
I don't think the combination matters. The way I understand is that GridFS is just a filesystem that does the real data management work, while CollectionFS has an abstraction over it so you don't need to deal with GridFS yourself. That means you are essentially just playing with Collections in MongoDB. So if you want to add those properties, just add them to the FsFile objects and it should be fine. Although I have not tried this so don't quote this on me. In my application I have a MongoDB collection for the extra information and documents in that collection would reference the files in CollectionFS. For example:
```JavaScript
{
  name: foobar,
  isPublic: maybe,
  isTrash: nope,
  file: FsFile._id,
}
```

**Comment by Zodiase** [comment]
But the downside of this is how it complicates things; I need to do multiple inserts. So you probably want to try attaching the data directly to the FsFile object first.

**Comment by daslicht** [comment]
I tried something like this:
```
	
				Images.insert(images[0], function (err, fileObj) {
		      		   fileObj.foo = "bar"
```
but that did not work.

Will the observer work by observing fileObj.url ? 
Is fileObj.url reactive ? Or which property would you have an observe on?

**Comment by Zodiase** [comment]
You may want to attach those extra properties **before** inserting.
The reason is that, when you do
```
fileObj.foo = "bar"
```
There is nothing telling Meteor that something is changed.
To update the file *after* inserting, you'd have to use `collection.update(_id:***, foo: 'bar')`.

And yeah what you found there is just adding a namespace so your extra properties won't damage the core functionalities.

**Comment by daslicht** [comment]
Okay... 
fileObj is an FS File no?
How do I get that before inserting ?

```
  $('.froala').on('editable.beforeImageUpload', function (e, editor, images) {
		    	var self = $(this);
	
                          //images seams to be just an array of file as you get with a regular ajax upload ?

				Images.insert(images[0], function (err, fileObj) {
```

**Comment by Zodiase** [comment]
For using cursors, read here: http://docs.meteor.com/#/full/observe

In your case, to create a cursor and start observing:
```
cursor = Files.find(_id:*******)
cursor.observeChanges(changed: (id, fields) ->
  if fields.contains('isUploaded') # if `isUploaded` changed, it probably means the file is uploaded.
)
```

**Comment by daslicht** [comment]
I just read the section about observers again in the Discover Meteor Book and came up with this approach:

```
Images.findOne(fileObj._id).observe({
						changed: function() {
							console.log('changed');
                                                        //insert image to froala editor here
						}

					});
```

But when the code reach this position I get this error:
```
Exception in delivering result of invoking '/cfs.images.filerecord/insert': TypeError: undefined is not a function
```

**Comment by Zodiase** [comment]
Yes the `fileObj` in the callback is instance of FsFile.
I assume what you have in the `images` array are all objects instance of File?
Then just do as in the tutorial you found:
```
var file = images[0];
var fsFile = new FS.File(file);
```
There you go.

**Comment by daslicht** [comment]
tis gives me teh same error as above:
```
cursor = Images.findOne(fileObj._id);
					cursor.observeChanges({
						added: function (id, fields) {
							// ...
						}, // Use either added() OR(!) addedBefore()
						addedBefore: function (id, fields, before) {
							// ...
						},
						changed: function (id, fields) {
							console.log("changed!");
							// ...
						},
						movedBefore: function (id, fields) {
							// ...
						},
						removed: function (id) {
							// ...
						}
					});
```

**Comment by Zodiase** [comment]
Note that `collection.findOne` returns a document or `null`, never the cursor. To get the cursor, you need to do `collection.find`.

**Comment by daslicht** [comment]
And again, value information from your side. respect!

Thank you very much !

This is working for me now:
```
$('.froala').on('editable.beforeImageUpload', function (e, editor, images) {
		    	var self = $(this);
				//console.log(this);
				//console.log(editor);
				//var url ="http://superdevresources.com/images/meteor/meteor-free-ebooks-tutorials.png";
				var file = images[0];

				var fsFile = new FS.File(file);
				    fsFile.foo ="bar";

				Images.insert( fsFile, function (err, fileObj) {
					console.log('id: ',fileObj._id);

					cursor = Images.find(fileObj._id);
					cursor.observeChanges({
						changed: function (id, fields) {
							var url = fileObj.url()
							console.log("changed!", url);
							console.log('File: ',fileObj.foo);
							self.editable('writeImage', url, true);
						}
					});

				});
			});
```
