### ISSUE TITLE
503 (Service Unavailable) on client-side insert (PUT to /crs/files/:collection_name/...)

### ISSUE THREAD

**Issue by mokolodi1** [CollectionFS/Meteor-CollectionFS#758]
I'm trying to make an app that uploads files and then parses them on the server with a Meteor method.

When I try to [insert](https://github.com/mokolodi1/put-503-cfs-bug-reproduction/blob/master/client/templates/uploadPathway/uploadPathway.js#L16) into the [FS.Collection](https://github.com/mokolodi1/put-503-cfs-bug-reproduction/blob/master/collections/collections.js#L5), the file is not uploaded because of a 503 error.

Here is a cloneable reproduction of the bug: [https://github.com/mokolodi1/put-503-cfs-bug-reproduction](https://github.com/mokolodi1/put-503-cfs-bug-reproduction)

**Comment by tmsss** [comment]
I've managed to get it working by setting a Meteor.setInterval that checks if the file is stored via fileObj.hasStored. It is not very elegant but it works. Something like this:

    'change .profile-photo': function(event, template) {
    
        var file = $('.profile-photo').get(0).files[0];
        var fileObj = Images.insert(file);
        var interval = Meteor.setInterval( function() {
    
                 if (fileObj.hasStored('images')) {
                    var imageURL = "/cfs/files/images/" + fileObj._id;
                    Meteor.call('updateUserProfilePhoto', imageURL, function (error, result) {
                      Meteor.clearInterval(interval);
                    });
                  }
        }, 50);
    
    }
    
    });

**Comment by mokolodi1** [comment]
So I ended up contacting [Eric Dobbertin](https://github.com/aldeed) and [the exchange is summarized in this StackOverflow question](http://stackoverflow.com/questions/31546174/read-an-uploaded-file-line-by-line-fs-file-stored-using-cfsgridfs). 

This bug report may or may not describe an actual bug in CollectionFS. The real problem was that the way I was trying to upload and parse a file was the wrong way to do it. Hopefully this bug report will help some lost soul who tries to go about it the same way as me.
