### ISSUE TITLE
MaxFileSize

### ISSUE THREAD

**Issue by marcianosr** [CollectionFS/Meteor-CollectionFS#759]
Hi, 

I'm creating an app with MeteorJS-angularJS and using the FS filesystem to upload images. However I want to show feedback to the user whenever they end up in the restrictions. I only allow certain types of image extensions, that works,  but I also want to show the user that they exceeded the max file size. How can I do that?

thanks

**Comment by nooitaf** [comment]
You can read out the filesize on the client side before even using any collection-fs.
http://www.w3schools.com/jsref/prop_fileupload_files.asp

or set the maxSize of your collection
https://github.com/CollectionFS/Meteor-CollectionFS#filtering

**Comment by marcianosr** [comment]
Thanks for the answer, however I think I didn't make myself clear enough. What I meant is that when you set the MaxFileSize option in the filter method, the 'OnInvalid' method runs when it exceeds the file size, or any other file error occurs, but it doesn't specifically say what error occured. Is that possible to see that? 

If not, handling it by the way you posted is the other option.

**Comment by nooitaf** [comment]
True, the insert returns an error:
````
FS.Collection insert: file does not pass collection filters
`````
At that point you could list your filters to the user. As in "One or more of those things failed: size has to be smaller than x, filetype has to be jpeg,png,gif..". Or do some more investigative stuff client side to pinpoint the error. 

I agree, it would be nice to get at least the first filter that failed back to the client, but you might not want your client to know what your filters are.

**Comment by nooitaf** [comment]
Scratch that. CollectionFS does return a readable error string of the failed filter:
````javascript
// client.js
Images = new FS.Collection("images", {
  stores: [imageStore],
  filter:{
    maxSize: 100,
    onInvalid:function(msg){
      console.log(msg)
    }
  }
});  
````
it returns after upload of > 100byte
````
IMAG0006 3.JPG is too big
````
https://github.com/CollectionFS/Meteor-CollectionFS/blob/f28a3fcbfe86b999fcb2896363134fa9753d152e/packages/collection-filters/filters.js#L153

**Comment by marcianosr** [comment]
Pretty weird, I got this: 

```Error: FS.Collection insert: file does not pass collection filters```

This is my code: 

```
Images = new FS.Collection("images", {
  stores: [new FS.Store.FileSystem("images", {path: "~/uploads/"})],
  filter: {
    maxSize: 20, // in bytes
    allow: {
      contentTypes: ['image/*'],
      extensions: ['png', 'PNG', 'jpg', 'JPG', 'jpeg', 'JPEG']
    },

    onInvalid: function (message) {

      ImageExtNotAllowed = "WRONG_EXTENSION";

      // TO FIX: Show detailed errors
      

    }
  }
  
});
```

**Comment by nooitaf** [comment]
My code was client side, yours looks like server side. If the maxSize filter is implemented on client side, it never reaches the server. You are also missing a console.log(message) in your onInvalid block.

**Comment by marcianosr** [comment]
Ah yes! That's what I was looking for! Didn't know you also could use it for the client side. Thanks a bunch!

**Comment by nooitaf** [comment]
You are welcome :)
