### ISSUE TITLE
Gridfs-stream error on windows. 

### ISSUE THREAD

**Issue by rfox90** [CollectionFS/Meteor-CollectionFS#763]
Getting the following error on a development meteor run. 

I'm assuming that its something to do with windows. Obviously using cfs:gridfs

Using these other CFS packages:
```
'cfs:standard-packages',
'cfs:gridfs@0.0.33',
'cfs:ui',
'cfs:graphicsmagick',
'cfs:ejson-file'
```

```
W20150726-23:40:17.248(1)? (STDERR) ReferenceError: require is not defined
W20150726-23:40:17.248(1)? (STDERR)     at app\node_modules\gridfs-stream\node_modules\flushwritable\lib\FlushWritable.js:6:20
W20150726-23:40:17.248(1)? (STDERR)     at app\node_modules\gridfs-stream\node_m
odules\flushwritable\lib\FlushWritable.js:43:3
=> Exited with code: 8
```

Any ideas? I'm happy to run or do anything required if it can get you more information.

**Comment by newswim** [comment]
Does this have anything to do with windows not accepting folders with colons?

I think the convention is hyphens instead? Have to check on that..

**Comment by rfox90** [comment]
I don't think so. Nothing in the file path has colons. Its just the package names that do. Thanks for the thoughts :)

**Comment by rfox90** [comment]
Ok figured it out.
I installed the gridfs-stream npm module locally in my application root. This creates the node_modules directory and includes it in the build. Meteor then finds JS code and tries to run it within a meteor environment which causes the above error.

In the next release of meteor the node_modules folder will be excluded from build: 
https://github.com/meteor/meteor/pull/4457
