### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by yokas** [CollectionFS/Meteor-CollectionFS#780]
3 month with no update

**Comment by aaronjudd** [comment]
It's being used actively, and is supported, so I wouldn't call it dead just because there hasn't been any recent releases.

**Comment by nicolamr** [comment]
When you have a note on the Readme that says: "This branch is under active development right now (2015-03-01). It has bugs and the API may continue to change. Please help test it and fix bugs, but don't use in production yet." in August 2015 it's understandable that someone might wonder whether the project is still alive.

**Comment by pauldowman** [comment]
Many people are using it in production. The frequency of releases to Atmosphere isn't a good indicator of whether a package is reliable. Looking at the [pulse](https://github.com/CollectionFS/Meteor-CollectionFS/pulse/monthly) I see PRs being merged and issues being closed. 

It's a huge project though, and clearly could use some help. We use it a lot at [OK GROW!](http://www.okgrow.com/) (actually we have been working on [an image upload package](https://atmospherejs.com/okgrow/image-upload) that builds on it) so to thank and encourage the community I will offer up some bounty money to close a couple of issues. I'll figure out how that could work and follow up here.

**Comment by kodamirmo** [comment]
is dead now?

**Comment by nooitaf** [comment]
@kodamirmo lol, no
