### ISSUE TITLE
DOCS: createReadStream isn't the same as the original file?

### ISSUE THREAD

**Issue by keyscores** [CollectionFS/Meteor-CollectionFS#789]
Can we improve the DOCS on accessing a file from CollectionFS? The example is very specific to images.

I've uploaded a CSV file. Now I want to parse it when upload is complete (using babyparse). I have a test file, which I can successully parse as such:

   
     filePath = process.env.PWD + "/public/data/test.csv";
     parsed = Baby.parseFiles(filePath)

However with collectionFS I'm getting an invalid file:
 
     Collection.on('uploaded', function (fileObj) {
         file = fileObj.createReadStream()
         parsed = Baby.parseFiles(file)

Is there an intermediary step?

**Comment by keyscores** [comment]
@raix I'm struggling to find a way to make a file accessible on the server-side code. Can you point me to any examples?

**Comment by raix** [comment]
doesn't seem like babyparse supports streams? You could stream the file to a temp local file then have babyparse work on it?
