### ISSUE TITLE
Error usign GridFS on Cordova Android: "Error: "Queue" [undefined], Error: [undefined]

### ISSUE THREAD

**Issue by miri-am** [CollectionFS/Meteor-CollectionFS#807]
The following is only on Android (android4). It works fine on iOS. Added/removed cfs:filesystem, added insecure ... nothing works. Worked fine before when I was using cfs:filesystem but needed to move to GridFS because of move to docker.

```
I20150907-23:18:31.342(2)? I/chromium( 5827): [INFO:CONSOLE(173)] "Error: "Queue" [undefined], Error: [undefined]
I20150907-23:18:31.343(2)? I/chromium( 5827):     at o (http://meteor.local/293e307d89ca8f9b0ac22847c98fd49c582f76c2.js?meteor_js_resource=true:296:3378)
I20150907-23:18:31.343(2)? I/chromium( 5827):     at FileReader.n.getBinary.t.onerror (http://meteor.local/293e307d89ca8f9b0ac22847c98fd49c582f76c2.js?meteor_js_resource=true:278:4311)", source: http://meteor.local/plugins/cordova-plugin-console/www/console-via-logger.js (173)
```

Any ideas?

**Comment by mike623** [comment]
+1

**Comment by miri-am** [comment]
@mike623. Did you try downgrading again? Also thought this is related to my update - however, after downgrading the error still  persists for me.

**Comment by miri-am** [comment]
I put some more detailed information where it is failing into meteor forums: https://forums.meteor.com/t/error-queue-undefined-error-undefined-using-collectionfs-gridfs-on-android/9513

**Comment by miri-am** [comment]
I am quite sure now that this is caused by the update to Meteor 1.2

**Comment by miri-am** [comment]
I have setup a minimal reproduction that shows the bug: https://github.com/miri-am/fsTest

Only occurs on Android using Meteor 1.2

**Comment by miri-am** [comment]
okay, is not caused by collectionFS. Using fileReader in Android causes this: Reproduction here: https://github.com/meteor/meteor/issues/5202

**Comment by miri-am** [comment]
leaving it open because it does not allow using collectionFS on Android at the moment. Will close when other issue is resolved.

**Comment by miri-am** [comment]
still cannot get this to work. Does anybody have a working version (Meteor 1.2 on Android) of collectionFS?

**Comment by dnish** [comment]
Having same problem here with Android and CollectionFS. I try to upload a base64 data/jpeg (generated from cordova-camera-plugin). The file doesn't get stored. It fails since I've upgraded to Meteor 1.2

**Comment by aldeed** [comment]
As posted in https://github.com/meteor/meteor/issues/5202, it is a cordova android bug and the workaround is:

```js
App.accessRule("blob:*");
```

**Comment by miri-am** [comment]
Can confirm that it is working for me: using gridFS on Android with Meteor 1.2. Thanks! Maybe could be added to documentation.
