### ISSUE TITLE
Question: Why does the client have to know about the store?

### ISSUE THREAD

**Issue by derwaldgeist** [CollectionFS/Meteor-CollectionFS#831]
According to the docs:
> Your FS.Collection and FS.Store variables do not necessarily have to be global on the client or the server, but be sure to give them the same name (the first argument in each constructor) on both the client and the server.

I am wondering why the client does to have any knowledge about the FS.Store? Isn't this server-internal information you typically would not want to disclose to the client, especially if it contains information like credentials?

I'd prefer to do it this way:

Server:
```js
Images = new FS.Collection("images", {
  stores: [new FS.Store.FileSystem("images", {path: "~/uploads"})]
});
```

Client:
```js
Images = new FS.Collection("images");
```

Is there any reason why this wouldn't work?

**Comment by 0x860111** [comment]
In depends on the case.

Sure. You also can redefine collection on the client-side. And give the file (for ex. image) by server query and return just a link. Client doesn't care in that case about all image properties and additional information. 

But what if I want to show all user's uploaded image and let him to take access for deleting and sorting them? In that case I should not redefine collection on the client-side.

**Comment by derwaldgeist** [comment]
Thanks for that clarification. I was just curious why it was designed this way.

**Comment by aldeed** [comment]
It's allowed on the client for purposes of being able to write in common code and keep things simple. I'm pretty sure the stores are not needed on the client. If they are, then it's only because we use the store name in some places. But the store adapters are basically empty shells in client code.
