### ISSUE TITLE
Most packages are deprecated, how to use their functionality now

### ISSUE THREAD

**Issue by Kunal1985** [CollectionFS/Meteor-CollectionFS#833]
As i can see that the packages cfs:gridfs or cfs:filesystem have been deprecated, but the documentation still says "At least cfs:gridfs or cfs:filesystem must be added"
Please let me know how CollectionFS should be used to utilize the functionality of the deprecated packages.

**Comment by aldeed** [comment]
They are not deprecated. The separate repos are deprecated and all the packages now live in one repo.

**Comment by Kunal1985** [comment]
Perfect, thnx a lot :)
