### ISSUE TITLE
Multiple Instances crash

### ISSUE THREAD

**Issue by xanatas** [CollectionFS/Meteor-CollectionFS#834]
I have now multiple instances running and when i upload one instance to S3 the others are crashing:

Error: ENOENT, open '/Users/me/Documents/MeteorProjects/test/.meteor/local/cfs/files/_tempstore/documents-vDpMkJm4ZwBBuEZHp-0.chunk'

any way arround that?

**Comment by mxab** [comment]
CollectionFS is currently not really suited to run on multiple instance.
Depending on how desperate you are you can use my very experimental branch which is a fork of @rhyslbw branch
https://github.com/planet-training/Meteor-CollectionFS/tree/feature/jc-queue-job-query-restriction

two thinks that are currently required are:
1. have a NODE_ID environment variable which a name of each of your instances
2. In addition set this NODE_ID to the FS.JobManager.Config
```
FS.JobManager.Config.nodeId = process.env.NODE_ID;
FS.JobManager.Config.jobQueryRestriction = {
    'data.sourceId': FS.JobManager.Config.nodeId
};
```

Don't expect any further work on that branch ;)

**Comment by xanatas** [comment]
allright thanks for the quick update! might give it a go!

**Comment by welelay** [comment]
same problem when using meteorhacks:cluster, which spawns multiple workers. The environment variable to watch is CLUSTER_WORKER_ID.

**Comment by dnish** [comment]
@aldeed Would be cool if we could integrate this into the official package. I didn't know that CollectionFS wasn't optimized for multiple instances, we just integrated it because it was a good experience to see how easy file uploads can be.

**Comment by welelay** [comment]
@rhyslbw Is multi-instance/multi-worker support implemented, then?

**Comment by rhyslbw** [comment]
@welelay No, but this Github issue is a duplication. Track this to follow along:

https://github.com/CollectionFS/Meteor-CollectionFS/pull/667

**Comment by welelay** [comment]
@rhyslbw ok good, thanks for the link to the PR.
I've read it through but I have another question : 

Is switching the tempstore to gridfs like this:
```
FS.TempStore.Storage = new FS.Store.GridFS('_tempstore', { internal: true });
```
without your pull request enough to get away with ENOTFOUND errors when workers try to access chunks already handled by other instances?
In other words, is switching to the gridfs tempstore enough to have multiple apps/instances in production?

**Comment by rhyslbw** [comment]
@welelay No, the problem is not related to the storage method but the underlying architecture. To better understand this check out https://github.com/CollectionFS/Meteor-CollectionFS/wiki/Insert-process-codebase-walk-through

**Comment by welelay** [comment]
Got it, thanks :-)
