### ISSUE TITLE
Multiple copies when using meteor-cluster and GridFS

### ISSUE THREAD

**Issue by dnish** [CollectionFS/Meteor-CollectionFS#836]
I'm using CollectionFS on a GridFS replica set. When users upload a file, the file is added 3 times to the database, everytime with different id's - but all other values are the same.

We have 3 Meteor servers running, connected by meteor-cluster. Is it possible, that CollectionFS has problems with multiple instances? Is there any fix to prevent this behavior?

**Comment by nooitaf** [comment]
related to https://github.com/CollectionFS/Meteor-CollectionFS/issues/834#issuecomment-147712556 ?
