### ISSUE TITLE
Image upload to Dropbox not working on live server

### ISSUE THREAD

**Issue by mohsinali1317** [CollectionFS/Meteor-CollectionFS#839]
I am trying to upload images to dropbox, it is working locally but not when I publish it to test server. This is how my store looks

    var dropboxStore = new FS.Store.Dropbox("playerProfilePictures", {
    key: "",
    secret: "",
    token: "", // Don’t share your access token with anyone.
    transformWrite: createThumb, //optional
    });

**Comment by mohsinali1317** [comment]
Still no answers or comments?

**Comment by timmakken** [comment]
Is your "test" server the free meteor.com server?

**Comment by mohsinali1317** [comment]
Yes and I found out that you can\t use image magick there. Thanks for responding though.
