### ISSUE TITLE
Error storing uploaded file to TempStore: ENOENT, no such file or directory '/var/www/cfs/files/_tempstore/images-BnFhPf79SsMQsqBaZ-0.chunk'

### ISSUE THREAD

**Issue by greggman** [CollectionFS/Meteor-CollectionFS#846]
I just setup a pretty simple site as far as CollectionFS is concerned and I got this error bringing down the site

```
        throw er; // Unhandled 'error' event
              ^
Error: Error storing uploaded file to TempStore: ENOENT, no such file or directory '/var/www/cfs/files/_tempstore/images-BnFhPf79SsMQsqBaZ-0.chunk'
    at EventEmitter.<anonymous> (packages/cfs_collection/packages/cfs_collection.js:161:1)
    at EventEmitter.emit (events.js:98:17)
    at WriteStream.<anonymous> (packages/cfs_tempstore/packages/cfs_tempstore.js:343:1)
    at WriteStream.emit (events.js:117:20)
    at WriteStream.<anonymous> (packages/cfs_filesystem/packages/cfs_filesystem.js:99:1)
    at WriteStream.emit (events.js:117:20)
    at fs.js:1610:14
    at Object.oncomplete (fs.js:108:15)
```

Is this a known issue or something I forgot to set up maybe. I have no idea how the internals of CollectionFS works. I'm using the file system adaptor

The sum total of my CollectionFS code is

```
Images = new FS.Collection("images", {
  stores: [
    new FS.Store.FileSystem("images", {
      path: IMAGE_PATH,
      beforeWrite: function(fileObj) {
        fileObj.name("thumbnail.png");  // Because it's a dataURL there's no name
        return {
          extension: 'png',
          type: 'image/png',
        };
      },
    }),
  ],
});

if (Meteor.isServer) {
  Images.allow({
    'insert': function() {
        return true;
    },
    'download': function() {
         return true;
    },
  });
}

Meteor.methods({
 saveDataURL: function(screenshotDataURL) {
  Images.insert(screenshotDataURL, function(err, fileObj) {
    Doc.insert({
      owner: Meteor.userid(),
      createdAt: new Date(),
      screenshotDataId: fileObj._id,
    });
  });
...
```

**Comment by nooitaf** [comment]
Does the folder `/var/www/cfs/files/_tempstore/` exist and/or has the user executing the app the rights to access and write to this folder?

**Comment by greggman** [comment]
Yes it exist and yes, AFAICT it has the permissions. I'm running in a docker container, everything is root. Also given that ColllectionFS created that folder shouldn't it have permission?

Anyway I'll see if I can repo. Do all files go though chunks saved in tempstore or only if they are big? I'll try up loading a big dataURL. AFAIK though the biggest I've uploaded so far is about 300k

**Comment by nooitaf** [comment]
You can also try to `meteor add cfs:gridfs` so that the tempstore uses gridfs(mongo) in place of the filesystem. It does that by default if gridfs is installed.

In addition you could add:
`````javascript
// Its important to set `internal: true` this lets the SA know that we
// are using this internally and it will give us direct SA api
FS.TempStore.Storage = new FS.Store.GridFS('_tempstore', { internal: true });
`````
https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/tempstore/internal.api.md#fstempstorestorage-storageadapterserver

**Comment by greggman** [comment]
So .... I tried that locally and saved an image and

```
The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
cfs_upload-http.js:206 PUT http://localhost:3000/cfs/files/images/nNfxdWX5MrsZinJbi?chunk=0&filename=u…VG9rZW4iOiJ5V3pSVDNCWDg0ZFd1ZHNDU2RoTGd0RW5LeDllaHpmY0tjcEgyQWQyT1hQIn0%3D 404 (Not Found)httpCall @ cfs_upload-http.js:206gotBinaryCallback @ cfs_upload-http.js:342reader.onload @ cfs_data-man.js:307
cfs_power-queue.js:494 Error: "Queue" failed [404] Not Found [404] [undefined], Error: failed [404] Not Found [404] [undefined]
    at cfs_upload-http.js:351
    at cfs_upload-http.js:77
    at underscore.js:750
    at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494taskCallbackDone @ cfs_power-queue.js:576(anonymous function) @ cfs_upload-http.js:351(anonymous function) @ cfs_upload-http.js:77(anonymous function) @ underscore.js:750xhr.onreadystatechange @ cfs_upload-http.js:200
cfs_upload-http.js:109 The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.
```

Note: I've see the `The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType` all the time before but that other error is new

NOTE: these error messages are on the client. Just guessing but I think the issue might be something tries to download the image before it's finished?

If one person saves and another person is viewing the gallery the `Doc.insert` in the code above if I understand correctly, happens before the images has fully been uploaded. So, someone else (or the same person with another tab open) will see the new doc and it will immediately try to access the new image

BTW: it's all being used here http://www.vertexshaderart.com 

The entire thing is checked into github (http://github.com/greggman/vertexshaderart)

**Comment by greggman** [comment]
Now it seems to have gotten itself into a state on my local machine where it can no longer save. By local I mean  in dev when I run meteor and go to http://localhost:3000

I've got gridfs in like you mentioned. Every time I try to save an image I get these errors and meteor crashes

W20151028-14:55:55.440(9)? (STDERR) 
W20151028-14:55:55.441(9)? (STDERR) /Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:246
W20151028-14:55:55.441(9)? (STDERR)         throw message;      
W20151028-14:55:55.441(9)? (STDERR)               ^
W20151028-14:55:55.443(9)? (STDERR) Error: 56306364147540767715e195 does not exist
W20151028-14:55:55.443(9)? (STDERR)     at /Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/gridfs/gridstore.js:200:22
W20151028-14:55:55.443(9)? (STDERR)     at /Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
W20151028-14:55:55.443(9)? (STDERR)     at /Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:778:35
W20151028-14:55:55.443(9)? (STDERR)     at Cursor.close (/Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:1009:5)
W20151028-14:55:55.443(9)? (STDERR)     at Cursor.nextObject (/Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:778:17)
W20151028-14:55:55.443(9)? (STDERR)     at commandHandler (/Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/cursor.js:741:14)
W20151028-14:55:55.443(9)? (STDERR)     at /Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
W20151028-14:55:55.443(9)? (STDERR)     at Server.Base._callHandler (/Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
W20151028-14:55:55.443(9)? (STDERR)     at /Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
W20151028-14:55:55.444(9)? (STDERR)     at [object Object].MongoReply.parseBody (/Users/gregg/.meteor/packages/cfs_gridfs/.0.0.33.11uxblu++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)

The message is always about `56306364147540767715e195` which suggests it's looking at some old data and can never get past that.

**Comment by nooitaf** [comment]
You can try `meteor reset` which clears the mongo-data of the meteor app.
If you want/need to keep some data, you could dive into the `meteor mongo` (meteors internal mongo shell) and drop all cfs related collections.

**Comment by greggman** [comment]
I'm going to close this issue. I'm not using CollectionFS anymore. I'm sure I was just doing something stupid but my needs were pretty simple so I just wrote my own. I'll revisit if I do something more complex. Awesome stuff BTW
