### ISSUE TITLE
I can't upload any image. Always get : Error: Error: Storage name already exists: "_tempstore"

### ISSUE THREAD

**Issue by THPubs** [CollectionFS/Meteor-CollectionFS#876]
I saw many issues regarding this error but looks like most of them get fixed by just an app restart. But my issue does not. Think it's different. I earlier used FS Filesystem and then later switched to Gridfs. Might this be the issue?

The full error I get in the browser console :

    Error: "Queue" failed [503] Error in method "/cfs/files/:value/:value/", Error: Error: Storage name already exists: "_tempstore"     at new FS.StorageAdapter (packages/cfs_storage-adapter/... [undefined], Error: failed [503] Error in method "/cfs/files/:value/:value/", Error: Error: Storage name already exists: "_tempstore"     at new FS.StorageAdapter (packages/cfs_storage-adapter/... [undefined]
        at cfs_upload-http.js:351
        at cfs_upload-http.js:77
        at underscore.js:750
        at XMLHttpRequest.xhr.onreadystatechange (cfs_upload-http.js:200)PowerQueue.runTaskDone @ cfs_power-queue.js:494taskCallbackDone @ cfs_power-queue.js:576(anonymous function) @ cfs_upload-http.js:351(anonymous function) @ cfs_upload-http.js:77(anonymous function) @ underscore.js:750xhr.onreadystatechange @ cfs_upload-http.js:200

**Comment by THPubs** [comment]
Im also getting this error :

    Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'images' of undefined
        at Object.httpGetHandler (packages/cfs_access-point/packages/cfs_access-point.js:261:1)
        at Object.accessPoint.get (packages/cfs_access-point/packages/cfs_access-point.js:594:1)
        at packages/cfs_http-methods/packages/cfs_http-methods.js:582:1

**Comment by THPubs** [comment]
All the issues disappear when using the meteor's local mongo. Any special way to setup the local mongo for this plugin to work?

**Comment by garden786** [comment]
can you please give me some code.I can't tell you what you are doing wrong without seeing the code

**Comment by nooitaf** [comment]
There should be no special way. Switching storage adapters might be an issue though. So you might have to start clean, or figure out a way to move them over.

Refering to `Storage name already exists`, you could try to drop and remove the `_tempstore` collection in mongo, so gridfs can go through the creation process. 

If you got your data backed up you could also try a [`meteor reset`](http://docs.meteor.com/#/full/meteorreset) which completely resets/clears your local mongo/app.
