### ISSUE TITLE
How to add an existing file on the server to the collection?

### ISSUE THREAD

**Issue by maranqz** [CollectionFS/Meteor-CollectionFS#880]

**Comment by nooitaf** [comment]
You could provide a local path or serve it via http somehow.

---
The insert method can directly accept a variety of different file representations as its first argument:

- File object (client only)
- Blob object (client only)
- Uint8Array
- ArrayBuffer
- Buffer (server only)
- A full URL that begins with "http:" or "https:"
- A local filepath (server only)
- A data URI string

https://github.com/CollectionFS/Meteor-CollectionFS#initiate-the-upload
