### ISSUE TITLE
How to use a remote server to store the file collection?

### ISSUE THREAD

**Issue by maranqz** [CollectionFS/Meteor-CollectionFS#881]
There is a ready option for it.

**Comment by nooitaf** [comment]
Define "remote server" please

**Comment by maranqz** [comment]
cfs:filesystem
Remote server: PC is in the same local network, on which the files should be stored.

**Comment by nooitaf** [comment]
Install nfs server on the remote machine and mount the shared directory on the local machine. Then just use the path to the mounted directory.

**Comment by maranqz** [comment]
Thank you.
