### ISSUE TITLE
After removing/drop the cfs collection start 404 not found error

### ISSUE THREAD

**Issue by kenjoe** [CollectionFS/Meteor-CollectionFS#882]
Hi everyone! I'm using collectionFS, the upload process is OK but when I tried to drop the cfs collection, It start's showing 404 not found on the browser console, seems like the images stays somewhere and not totally remove.. any reply is greatly appreciated...!

**Comment by nooitaf** [comment]
Did you remove them in meteor or with mongo shell?

**Comment by kenjoe** [comment]
I removed it in mongo shell..

**Comment by nooitaf** [comment]
Well, then you have to remove more or even everything cfs related in mongo shell.

The better way is doing it with meteor shell: `Images.remove({})`

**Comment by kenjoe** [comment]
I did db.cfs.profile_images.filerecord.drop();

then after that, I uploaded a new image, and everytime I login, the error show's 404 not found.

**Comment by nooitaf** [comment]
did you remove __everything__ cfs related from mongo and restart the app?

**Comment by kenjoe** [comment]
no, only the profile_images collection. I think sir this is a cache on minimongo? Because everytime I login the GET request of image that was deleted before always triggered?

**Comment by nooitaf** [comment]
Well, delete your browser cache to try it. But i guess you might have to go in and delete all cfs related collections in your mongo and restart your app.

**Comment by kenjoe** [comment]
@nooitaf I already delete all cfs collections an restart my app.. but the error still there.. :(

**Comment by nooitaf** [comment]
If all cfs related collections in mongo are gone it can't be cfs. so you might want to check for other errors.
