### ISSUE TITLE
Moving the application on a different subpath breaks all links

### ISSUE THREAD

**Issue by mquandalle** [CollectionFS/Meteor-CollectionFS#884]
Meteor supports deploying an application under a subpath using the `ROOT_URL` environment variable:

```
ROOT_URL="http://localhost:3000/subpath/" meteor
```

Under such a deployment files are uploaded and served under the absolute path `/subpath/cfs/collectionName/hash/file.png`. So problem is that if the application is later moved to another subpath (eg `/subpath2`) then the collectionFS files URLs won’t be uploaded.

A correct implementation to handle that use case would be to save the file path without the application path prefix, ie `cfs/collectionName/hash/file.png` instead of `/subpath/cfs/collectionName/hash/file.png` and to happen to path prefix in the `url()` method, in a similar way to what `FlowRouter.path` is doing it for instance.

I would be happy to write a PR with this implementation, if you can point me in the correct direction.

**Comment by Buom01** [comment]
Is it solved ? Because I did the same, and for me, images are correctly served in subpath
The only difference is that I havent the trailing `/` like `ROOT_URL=http://localhost:3000/subpath meteor`
I'm also storing my images in mongo

**Comment by mquandalle** [comment]
Serving images under a subpath is working. What is not working is moving your application from subpathA to subpathB because it breaks all the links.

**Comment by Buom01** [comment]
OK, a solution can be a 302 redirect in server side, or a wrapper in client to replace the old path to the new

For me I think that I will use an other package, this one is realy to bugged !
