### ISSUE TITLE
CollectionFS crashes app on heroku - Cannot read property 'resize' of undefined

### ISSUE THREAD

**Issue by shailendra735** [CollectionFS/Meteor-CollectionFS#889]
My app works fine on local. However, all my heroku builds are failing. I had been able to deploy the app successfully once but that day I restarted the server while the image upload was in progress and I've been getting this error since then:
```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch.
Stopping process with SIGKILL
FS.Transform.createWriteStream transform function failed, Error:
Exception in queued task: TypeError: Cannot read property 'resize' of undefined
State changed from starting to crashed
Process exited with status 137
```

My code for transformation:

```
transformWrite: function(fileObj, readStream, writeStream) {
    try {
      gm(readStream, fileObj.name()).resize(width, height, opts.resize).interlace(opts.interlace).stream().pipe(writeStream);
    } catch (error) {
      throw new Meteor.Error(error);
    }
  }
```
Currently, I've been able to get the site up minus collectionFS. I've emptied the chunks collection too. Any fixes?

**Comment by travisdahl** [comment]
@shailendra735 I think I am having the same problem on heroku. I think we need to install graphicsmagick on heroku but I haven't figured out how to do that yet because if you add the gm buildpack it adds the src files into a `vendor` directory and then meteor sees them and the templating errors out when it sees the html files.

**Comment by shailendra735** [comment]
@travisdahl We've moved ahead and got rid of CollectionFS.

**Comment by da314pc** [comment]
@travisdahl Here is a git url for a graphicsmagick buildpack that will work for meteor. 

https://github.com/impossible-bureau/heroku-buildpack-graphicsmagick.git
