### ISSUE TITLE
migrate from gridfs to s3

### ISSUE THREAD

**Issue by mike623** [CollectionFS/Meteor-CollectionFS#893]
found doc from :
https://github.com/CollectionFS/Meteor-CollectionFS/wiki/How-to:-Convert-a-file-already-stored

but I can only migrate file size 0 to s3 but I can migrate without  using for each, but migrate one by one

not work

        syncImage(){
          Images.find().forEach(function (fileObj) {
            console.log(fileObj);
            var readStream = fileObj.createReadStream('images');
            var writeStream = fileObj.createWriteStream('s3images');
            readStream.pipe(writeStream);
          });
          console.log("f");
        },

work but not every time, need retry

        syncImage2(num){
            var fileObj = Images.find().fetch()[num]
            console.log(fileObj);
            var readStream = fileObj.createReadStream('images');
            var writeStream = fileObj.createWriteStream('s3images');
            readStream.pipe(writeStream);
          console.log("f");
        },

**Comment by brylie** [comment]
@mike623 did you get this migration worked out? We want to migrate between FS collections as well.

**Comment by mike623** [comment]
also follow #747

**Comment by brylie** [comment]
I followed #747, and commented at the end of the discussion.
