### ISSUE TITLE
what is the token in FS.File.url for?

### ISSUE THREAD

**Issue by PolGuixe** [CollectionFS/Meteor-CollectionFS#903]
This may be a noob question, but I don't see the use. I can't access the file using the url without the token.

**Comment by nooitaf** [comment]
It's an [auth token](https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/access-point/api.md#fsfileurloptionsanywhere). So you could do `{{url auth='false'}}`

--- 

https://github.com/CollectionFS/Meteor-CollectionFS#security
- To determine who can download the actual file, use "download" allow/deny functions. This is a custom type of allow/deny function provided by CollectionFS. The first argument is the userId and the second argument is the FS.File being requested for download. An example:
```javascript
Images.allow({
    download: function(userId, fileObj) {
        return true
    }
})
```

**Comment by pl7y** [comment]
Problem is, userId value in `download` function is not set correctly: see #711 .
So `return true` is actually the only thing you can do, with **no security controls** on file access...

**Comment by ppryde** [comment]
@nooitaf Just a note, I think you will need `{{url auth=false}}` without the quotes around false otherwise it evaluates to truthy value being a string

**Comment by nooitaf** [comment]
@ppryde i, fixed it :)
