### ISSUE TITLE
does this plugin function in windows?

### ISSUE THREAD

**Issue by elkadiri-wd** [CollectionFS/Meteor-CollectionFS#913]
plz tell me can this plugin function in windows? if so, why it gives me these errors while running:
 bumpversion.js:1:15: Unexpected token ILLEGAL
 publish.js:1:15: Unexpected token ILLEGAL
and in which version of meteor it can run?

thank you!

**Comment by mngkvn** [comment]
It works on mine running windows and latest version of meteor. Did you double check your code ?

**Comment by harryadel** [comment]
Hey there buddy, A bit late to the party but this issue was caused by `publish.js` and `bumpversion.js` where Meteor'd attempt to run them. It's fixed now.
