### ISSUE TITLE
GET image from DDP.js

### ISSUE THREAD

**Issue by Mokto** [CollectionFS/Meteor-CollectionFS#926]
Hi,

I'm using a React Native application with your great plugin.

In my web app, I can use the url() function to get something like :
/cfs/files/imagesFiles/FILE_ID?token=MYTOKEN

In my React-Native application, I can only access to the imageFile _id.
So I generate an url like the one above, but :

1) It seems that MYTOKEN does not match with Meteor.loginToken in my web app when generated with url()
2) It seems that my react native application does not pass into the download validation function.

Thank you !

**Comment by pl7y** [comment]
Is this related to #711 ?

**Comment by Mokto** [comment]
Not really, but I forgot to tell that I found a solution to generate the good token.




`const url = '/cfs/files/imagesFiles/'+imageFile.$value._id+'?token='+btoa(JSON.stringify({authToken: token}));`
