### ISSUE TITLE
cfs_base-package.js:108 Method '/cfs.images22.filerecord/update' not found

### ISSUE THREAD

**Issue by dmitrika** [CollectionFS/Meteor-CollectionFS#985]
Hey there!

I'm trying to upload images from url with gridFS and meteor METEOR@1.3.5.1, but facing problems while uploading.

![screenshot 2016-08-12 08 34 35](https://cloud.githubusercontent.com/assets/10303257/17613646/2afe6282-6068-11e6-8da7-f9013e230c13.png)

My file.js at imports/api/files.js

```
FS.debug = true;

export default Images = new FS.Collection("images22", {
    stores: [new FS.Store.GridFS("images22", {path: "~/uploads"})]
});

Images.allow({
    insert: function () {
        return true;
    },
    remove: function () {
        return true;
    },
    download: function () {
        return true;
    },
    update: function () {
        return true;
    },
});
```

Adding it in my App.js, and triggering in on event, after input submit. Idea is grab input value as a link and download file to server. It's inside React component, actually.

```
    handleSubmit(event) {
        event.preventDefault();
        const link = this.refs.input.value.trim();

        const fileObj = new FS.File();
        fileObj.attachData(link, function () {
            console.log(arguments);
        });
        Images.insert(fileObj, function (err, fileObj) {
            console.log(arguments);
        });
        this.refs.input.value = '';
    },

```

What can be wrong? :(

**Comment by dmitrika** [comment]
If I change code a little bit:

```
const fileObj = new FS.File();
		fileObj.attachData(link, function () {
			console.log(arguments);
			Images.insert(fileObj, function (err, fileObj) {
				console.log(arguments);
			});
		});
```

It also will callback with error.
![screenshot 2016-08-12 08 43 47](https://cloud.githubusercontent.com/assets/10303257/17613731/faef9826-6068-11e6-9454-d18391f6d8fb.png)

**Comment by nooitaf** [comment]
iirc, link insert is server only.
