### ISSUE TITLE
Not able to get URL of .indd file

### ISSUE THREAD

**Issue by ghost** [CollectionFS/Meteor-CollectionFS#986]
I am storing .indd file in cfs:gridfs and i am not gettng url of that file on meteor galaxy but i am able to get url on localhost. This issue only occur with .indd file if i was store .pdf / .doc / .jpg then it will work perfectly on both side localhost and meteor galaxy.

Please provide any way to get url of .indd file on meteor galaxy.

**Comment by nooitaf** [comment]
Did you find a solution?

**Comment by nooitaf** [comment]
maybe related https://github.com/CollectionFS/Meteor-CollectionFS/issues/1022

**Comment by nooitaf** [comment]
A small detail that might be relevant is, that on a mac `.indd` files are not actually files but folders.
