### ISSUE TITLE
Error: Request Entity Too Large

### ISSUE THREAD

**Issue by aldo235** [CollectionFS/Meteor-CollectionFS#989]
can some one help me, in my local i can upload image more then 4MB but in server if i upload more then 1MB i got this error

**Comment by raix** [comment]
are you guys using nginx or something like that?

**Comment by aldo235** [comment]
im using PM2 meteor for deploy

**Comment by nooitaf** [comment]
Does PM2 meteor install nginx? 
You add `FS.debug=true` in global code to get more info.
You could try `meteor --production` locally and see if you get the same error.
