### ISSUE TITLE
Not working on Production Server

### ISSUE THREAD

**Issue by kenshinman** [CollectionFS/Meteor-CollectionFS#991]
Hi Please i have asked a question on stackoverflow. Here is the link

[http://stackoverflow.com/questions/40990075/meteor-cfs-gridfs-not-working-production-server-but-works-fine-on-local-server](url)

File uploads work perfectly on my localhost but when i deploy to production server, I get this error

    `Error in method "/cfs/files/:value/:value/", Error: TypeError: Cannot read property 'postimages' of undefined
        at Object.httpGetHandler (packages/cfs_access-point/packages/cfs_access-point.js:357:1)
        at Object.accessPoint.get (packages/cfs_access-point/packages/cfs_access-point.js:675:1)
        at packages/cfs_http-methods/http.methods.server.api.js:581:1`
Is this a common error.

i am running on  `meteor 1.3.5.1` and also using the `gridfs` with `standard-package`

Thanks

**Comment by truongnx2** [comment]
I have same issue. Pls help

**Comment by nooitaf** [comment]
I would try adding `update` to your allows. Rules on production could be more strict? Or see if you get the same error, if you run `meteor --production` locally. You could also enable the global `FS.Debug = true` and see what errors that throws.
