### ISSUE TITLE
The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType

### ISSUE THREAD

**Issue by varunajmera0** [CollectionFS/Meteor-CollectionFS#996]
it gives this error . it is not working.
Packages: cfs:base-package
cfs:filesystem
cfs:collection
cfs:collection-filters
cfs:standard-packages
cfs:power-queue
cfs:micro-queue
cfs:reactive-list
cfs:ui
cfs:upload-http
cfs:transfer
cfs:tempstore
cfs:ejson-file
cfs:worker
cfs:upload-ddp
cfs:data-man
cfs:storage-adapter
cfs:http-publish
cfs:http-methods
cfs:filesaver
cfs:reactive-property
cfs:gridfs

**Comment by nooitaf** [comment]
https://github.com/CollectionFS/Meteor-CollectionFS/issues/688
